### ISSUE TITLE
Issue joining tables when filters are applied

### ISSUE THREAD

**Issue by jasonhjohnson** [zzzprojects/EntityFramework-Plus#117]
The following gives a very unclear/vaugue error when I have query filters applied:

```
var result= await (from p in context.Table1
            join b in context.Table2 on p.KeyId equals b.KeyId
            where b.OtherKeyId == entity.OtherKeyId
            select p).FirstOrDefaultAsync();    
```

If I do the following it works:

```
var result= await (from p in context.Table1.AsNoFilter()
            join b in context.Table2.AsNoFilter() on p.KeyId equals b.KeyId
            where b.OtherKeyId == entity.OtherKeyId
            && p.TenantId.Equals(GetTenantId())
            select p).FirstOrDefaultAsync();    
```

Obviously I'd prefer not to have to disable the query filters and manually add them (TenantId), but, I'm not sure what's going wrong here.

Thanks,
Jason

**Comment by JonathanMagnan** [comment]
Hello Jason,

Which version of Entity Framework are you using?

The answer will be highly different depending on this answer.

Best Regards,

Jonathan

**Comment by jasonhjohnson** [comment]
Geez sorry I should have mentioned that. EF Core.

**Comment by JonathanMagnan** [comment]
Hello @jasonhjohnson ,

I'm currently checking this issue. I can make it work when using the "cross join" and specifying the join clause in the where clause instead

```csharp
var result= await (from p in context.Table1
                             from b in context.Table2
                             where p.KeyId equals b.KeyId
                                        && b.OtherKeyId == entity.OtherKeyId
                             select p).FirstOrDefaultAsync();    
```

I will continue to check work it doesn't work when specifying a join.

**Comment by JonathanMagnan** [comment]
Hello @jasonhjohnson ,

Unfortunately, I believe we will not fix it and wait for the next version of Entity Framework Core.

**However, you can still use the cross join trick to make it work.**

Without using our library, we can easily reproduce this problem. It seems as soon as the join entities is filtered, casted, or anything else, the query fail. The issue is not on our side but caused by Entity Framework Core.

This will work:
```csharp
var result = ctx.Entities2.Where(y => y.Entity.TenantId == 1)
                .Join(ctx.Entities,
                    entity => entity.ColumnInt,
                    entity2 => entity2.ColumnInt,
                    (entity, entity2) => entity).ToList();
```

This will not work:
```csharp
var result = ctx.Entities
                .Join(ctx.Entities2.Where(y => y.Entity.TenantId == 1),
                    entity => entity.ColumnInt,
                    entity2 => entity2.ColumnInt,
                    (entity, entity2) => entity).ToList();
```

Where the join clause contains something else than the DbSet, it seems Entity Framework Core cannot handle it.

```
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2, Expression arg3, Expression arg4)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.<>c__DisplayClass64_0.<VisitJoinClause>b__0()
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index, Action baseVisitAction, MethodInfo operatorToFlatten, Boolean groupJoin)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.JoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Z.EntityFramework.Plus.Lab.EFCore.Form_Request_Filter..ctor() in C:\Users\Jonathan\Desktop\Z\zzzproject\Z.EntityFramework.Plus\Z.EntityFramework.Plus.Lab.EFCore\Form_Request_Filter.cs:line 60
   at Z.EntityFramework.Plus.Lab.EFCore.Program.Main() in C:\Users\Jonathan\Desktop\Z\zzzproject\Z.EntityFramework.Plus\Z.EntityFramework.Plus.Lab.EFCore\Program.cs:line 16
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by jasonhjohnson** [comment]
@JonathanMagnan Thanks. In the event I go with something like the query below, would it still apply by EF+ QueryFilters that are setup? 

```
var result= await (from p in context.Table1
                   from b in context.Table2
                   where p.KeyId equals b.KeyId
                         && b.OtherKeyId == entity.OtherKeyId
                   select p).FirstOrDefaultAsync();    
```

**Comment by JonathanMagnan** [comment]
Hello @jasonhjohnson ,

Yes, in EF Core, the DbSet is already filtered by our library. We don't use the Interceptor trick like we do in EF6.

So everything you do with the DbSet already contains the filter (which cause the issue with the Join method).

Best Regards,

Jonathan
