### ISSUE TITLE
UpdateAsync results in Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.InMemoryQueryContextFactory' ...

### ISSUE THREAD

**Issue by vmachacek** [zzzprojects/EntityFramework-Plus#149]
Hello, I have an issue when unit testing my code the exception happens during the `UpdaAsync` call 
```
using (var context = _checkoutContextFactory.Create())
            {
                await context.Baskets
                    .Where(t => t.OrderId == orderId && t.OrderId != null)
                    .UpdateAsync(t => new Models.BasketStoreContainer { OverallPaymentStatus = paymentStatus });
            }
```

this is how I create test context

```
var builder = new DbContextOptionsBuilder<CheckoutContext>();

builder.UseInMemoryDatabase();
var checkoutContext = new CheckoutContext(builder.Options);
BatchDeleteManager.InMemoryDbContextFactory = () => new CheckoutContext(builder.Options);          
return checkoutContext;
```

And this is call stack of exception
```
Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.InMemoryQueryContextFactory' to type 'Microsoft.EntityFrameworkCore.Query.Internal.RelationalQueryContextFactory'.
   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 source)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by JonathanMagnan** [comment]
Hello @vmachacek ,

The v1.4.41 has been released.

We released the first version to try to support this features.

Could you test it and let us know if that's working?

Note: You need to specify a context factory to make it work.

Example:

```csharp
BatchUpdateManager.InMemoryDbContextFactory = () => new MyContext(db.Options);

int value = 24234;
_context.Foos.Where(x => x.ColumnInt < 10).Update(foo => new Foo {Name = foo.Name + "2", T2 = value } );
```

**Comment by JonathanMagnan** [comment]
Hello @vmachacek ,

I will close this issue. Feel free to re-open it if you still have the bug.

Best Regards,

Jonathan

**Comment by agustins** [comment]
Hello @JonathanMagnan! 

`BatchUpdateManager.InMemoryDbContextFactory` is implemented as static. 
Could you implement per instance?

I have tests running in parallel and using diferents contexts, so InMemoryDbContextFactory changes at the middle of the execution...

Tell me if I wasn't clear to explain my problem.

Thanks in advance.
