### ISSUE TITLE
IncludeFilter() + Future()/FutureValue() combinations is not working

### ISSUE THREAD

**Issue by Iamcerba** [zzzprojects/EntityFramework-Plus#179]
Possibly this related with already created [issue](https://github.com/zzzprojects/EntityFramework-Plus/issues/10).

**Steps to reproduce:**

1.
```cs
using (var context = new NewsDbContext())
{
    IQueryable<News> news = context
        .News
        .IncludeFilter(e => e.Medias.Where(m => !m.IsDeleted))
        .Where(e => !e.IsDeleted)
        .OrderBy(e => e.CreatedUtc);

    QueryFutureValue<long> total = news.DeferredLongCount().FutureValue();

    news = news.Skip(1).Take(10);

    QueryFutureEnumerable<News> results = news.Future();

    var result = new PagedResult<News>()
    {
        Results = results.ToList(),
        Total = total.Value
    };
}
```

_Note:_ **LazyLoading enabled.**

I'm always receiving exception:

_Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com_

**Stack trace:**

```cs
at Z.EntityFramework.Plus.InternalExtensions.GetObjectQuery[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.QueryDeferredExtensions.DeferredLongCount[TSource](IQueryable`1 source)
   at …
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewsService.Web.Api.Services.v1.Implementations.NewsControllerService.<GetNews>d__7.MoveNext() in …

```

**Comment by JonathanMagnan** [comment]
Hello @Iamcerba ,

Thank you for the information.

We will look at this issue during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Iamcerba ,

Unfortunately, `Query IncludeFilter` is not compatible with `Query Deferred` feature which causes the issue.

We plan to revamp this library during the summer to improve features and fix some issue like this one.

Due to time restriction, we cannot do this fix right now but we will for sure look at it and try to fix it during the summer.

Best Regards,

Jonathan

**Comment by Iamcerba** [comment]
Hello @JonathanMagnan,

Thank you for quick reply, will wait for fix.

In addition to this I would like to mention that **IncludeFilter** / **IncludeOptimized** also doesn't work when I try to load nested navigation properties (filtered or not).

From the [docs ](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-IncludeFilter-%7C-Entity-Framework-Include-Related-Entities-using-Where-Filter):

> // LOAD blogs and related active posts and comments.
var blogs = ctx.Blogs.IncludeFilter(x => x.Posts.Where(y => !y.IsSoftDeleted))
                     .IncludeFilter(x => x.Posts.Where(y => !y.IsSoftDeleted)
                                                .Select(y => y.Comments
                                                              .Where(z => !z.IsSoftDeleted)))
                     .ToList();

1. "Posts" returned in the result as expected:
var blogs = ctx.Blogs.IncludeFilter(x => x.Posts.Where(y => !y.IsSoftDeleted).ToList();

2. The same query with additional nested include. As a result "Posts" **completely empty**:
var blogs = ctx.Blogs.IncludeFilter(x => x.Posts.Where(y => !y.IsSoftDeleted).Select(y => y.Comments.Where(z => !z.IsSoftDeleted))).ToList();

Standard .Include() works as expected.

**Comment by JonathanMagnan** [comment]
Yup,

We made the mistake when we created this library to make all features "standalone".

It's nice since they work all separately but that was a mistake since they have no "synergy" between features.

However, in your query, you can fix it by providing all paths.

```csharp
var blogs = ctx.Blogs.IncludeFilter(x => x.Posts.Where(y => !y.IsSoftDeleted))
					 .IncludeFilter(x => x.Posts.Where(y => !y.IsSoftDeleted).Select(y => y.Comments.Where(z => !z.IsSoftDeleted)))
					 .ToList();
```

**Comment by Iamcerba** [comment]
@JonathanMagnan,

It works, thank you! You saved my day :)
