### ISSUE TITLE
BatchUpdate and BatchDelete fails for ObjectContext

### ISSUE THREAD

**Issue by neurospeech** [zzzprojects/EntityFramework-Plus#193]
I have a project that uses ObjectContext (old style), both BatchUpdate and BatchDelete fails as they are expecting DbContext. The fix would be simple and small.

**Comment by neurospeech** [comment]
I have added support for pure ObjectContext, I have tested it and it seems to work fine.

However, it does work correctly for constant values, but it fails for self referencing entities for example,

```
       .Update( x => new Account {
           Suspended = true
       });
```

But it fails for

```
       .Update( x => new Account {
           Suspended = !x.Orders.Any()
       });
```

Such complex updates are possible in current version with DbContext?

**Comment by JonathanMagnan** [comment]
Hello @neurospeech ,

Thank you for your Pull, we will look at it during the weekend as well as the `x.Orders.Any()`

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @neurospeech ,

We made a test today, it works successfully with DbContext. We will do the same test when the `ObjectContext` will be implemented.

```csharp
using (var ctx = new EntityContext())
{
	ctx.EntitySimples.Update(x => new EntitySimple
	{
		BoolValue = !x.Rights.Any()
	});
}
```

**Comment by neurospeech** [comment]
This is the exception I am getting,

```
[xUnit.net 00:00:11.8358672]       System.ArgumentOutOfRangeException : Length cannot be less than zero.
[xUnit.net 00:00:11.8363572]       Parameter name: length
[xUnit.net 00:00:11.8379265]       Stack Trace:
[xUnit.net 00:00:11.8388197]            at System.String.Substring(Int32 startIndex, Int32 length)
[xUnit.net 00:00:11.8391935]         C:\Users\ackav\OneDrive\Documents\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchUpdate.Shared\BatchUpdate.cs(846,0): at Z.EntityFramework.Plus.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, SchemaEntityType`1 entity)
[xUnit.net 00:00:11.8395557]         C:\Users\ackav\OneDrive\Documents\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchUpdate.Shared\BatchUpdate.cs(185,0): at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
[xUnit.net 00:00:11.8399444]         C:\Users\ackav\OneDrive\Documents\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchUpdate.Shared\Extensions\Update.cs(52,0): at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
[xUnit.net 00:00:11.8403052]         C:\Users\ackav\OneDrive\Documents\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchUpdate.Shared\Extensions\Update.cs(26,0): at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
[xUnit.net 00:00:11.8406727]         D:\users\akash\VSOnline\Casting800\MAIN\Source\CastingWebApp\CastingWebApp\Common\BatchExtensions.cs(16,0): at CastingWebApp.BatchExtensions.Update[T](IQueryable`1 query, Expression`1 updateExpression)
[xUnit.net 00:00:11.8410048]         D:\users\akash\VSOnline\Casting800\MAIN\Source\CastingWebApp\CastingWebApp.Tests\Web\BatchTest.cs(23,0): at CastingWebApp.Tests.Web.BatchTest.BatchUpdate()

```
