### ISSUE TITLE
Null reference exception when calling remove

### ISSUE THREAD

**Issue by attrib75** [zzzprojects/EntityFramework-Plus#248]
Hi, I'm getting a null reference exception when removing an object from a dbset and calling save changes.  Thank you,   

```csharp
 c.MyDbSet.Remove(thing); 
    c.SaveChanges();
   
 public override int SaveChanges()
        {
            try
            {
                var audit = new Audit();
                audit.PreSaveChanges(this);  < ------ Null reference exception here
                var rowAffecteds = base.SaveChanges();
                audit.PostSaveChanges();

                if (audit.Configuration.AutoSavePreAction != null)
                {
                    audit.Configuration.AutoSavePreAction(this, audit);
                    base.SaveChanges();
                }

                return rowAffecteds;
            
            }
```

-------------------------Stack Trace
  at Z.EntityFramework.Plus.AuditConfiguration.IsAuditedEntity(ObjectStateEntry entry)
   at Z.EntityFramework.Plus.Audit.PreSaveChanges(Audit audit, DbContext context)
   at Z.EntityFramework.Plus.Audit.PreSaveChanges(DbContext context)

**Comment by JonathanMagnan** [comment]
Hello @attrib75 ,

I will need more information to reproduce it.

Do you think you can reproduce it using a similar code?

```csharp
using System.Data.Entity;
using System.Linq;
using System.Windows.Forms;

namespace Z.EntityFramework.Plus.Lab
{
    public partial class Form_Request_Audit : Form
    {
        public Form_Request_Audit()
        {
            InitializeComponent();

            // CLEAN
            using (var ctx = new EntityContext())
            {
                ctx.AuditEntryProperties.RemoveRange(ctx.AuditEntryProperties);
                ctx.AuditEntries.RemoveRange(ctx.AuditEntries);
                ctx.EntitySimples.RemoveRange(ctx.EntitySimples);

                ctx.SaveChanges(false);
            }

            // SEED
            using (var ctx = new EntityContext())
            {
                ctx.EntitySimples.Add(new EntitySimple {ColumnInt = 1});
                ctx.SaveChanges(false);
            }

            // TEST
            using (var ctx = new EntityContext())
            {
                ctx.EntitySimples.Remove(ctx.EntitySimples.ToList()[0]);
                ctx.SaveChanges(true);
            }
        }

        public class EntityContext : DbContext
        {
            static EntityContext()
            {
                // TO enable AutoSave in database
                AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
                    (context as EntityContext)?.AuditEntries.AddRange(audit.Entries);
            }

            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }
            public DbSet<AuditEntry> AuditEntries { get; set; }
            public DbSet<AuditEntryProperty> AuditEntryProperties { get; set; }

            public int SaveChanges(bool useAudit)
            {
                if (useAudit)
                {
                    return SaveChanges();
                }
                return base.SaveChanges();
            }

            public override int SaveChanges()
            {
                var audit = new Audit();
                audit.PreSaveChanges(this);
                var rowAffecteds = base.SaveChanges();
                audit.PostSaveChanges();

                if (audit.Configuration.AutoSavePreAction != null)
                {
                    audit.Configuration.AutoSavePreAction(this, audit);
                    base.SaveChanges();
                }

                return rowAffecteds;
            }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }

            public int ColumnInt { get; set; }
        }
    }
}
```

Best Regards,

Jonathan

**Comment by mafucka** [comment]
Hello @JonathanMagnan 

You can reproduce it by modifying _Audit_EntityDeleted:Entity_Proxy_ at _Z.Test.EntityFramework.Plus.EF6_

```cs
        [TestMethod]
        public void Entity_Proxy_Right()
        {
            TestContext.DeleteAll(x => x.AuditEntryProperties);
            TestContext.DeleteAll(x => x.AuditEntries);
            TestContext.DeleteAll(x => x.Entity_Proxy_Rights);
            TestContext.DeleteAll(x => x.Entity_Proxies);

            using (var ctx = new TestContext())
            {
                ctx.Entity_Proxy_Rights.Add(new Entity_Proxy_Right()
                {
                    Left = new Entity_Proxy()
                });

                ctx.SaveChanges();
            }

            var audit = AuditHelper.AutoSaveAudit();
            audit.Configuration.Exclude(x => true);

            using (var ctx = new TestContext())
            {
                TestContext.DeleteAll(ctx, x => x.Entity_Proxy_Rights);
                ctx.SaveChanges(audit);
            }
        }
```
and also modify _Entity_Proxy_Right_ (not necessary)

```cs
namespace Z.Test.EntityFramework.Plus
{
    public class Entity_Proxy_Right
    {
        public int ID { get; set; }

        public int ColumnInt { get; set; }

        public virtual Entity_Proxy Left { get; set; }
    }
}
```

NRE throw when it try to check relation:
```cs
var rightIsAudited = audit.CurrentOrDefaultConfiguration.IsAuditedEntity(rightEntity);
```

**Comment by JonathanMagnan** [comment]
Hello @attrib75 , @mafucka ,

Sorry for the long delay, the v1.7.8 has been released.

We added a check to make sure the value is not null on the line where the error happened.

Feel free to reopen if you still have the issue.

Best Regards,

Jonathan
