### ISSUE TITLE
ArgumentException with CountAsync have no predicate

### ISSUE THREAD

**Issue by 2501272126** [zzzprojects/EntityFramework-Plus#293]
EFCore 2.0.1 + Z.EntityFramework.Plus.QueryFilter.EFCore 1.7.1

test code:
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Z.EntityFramework.Plus;

namespace ConsoleApp2 {
    class Program {
        static void Main(string[] args) {
            using (var dbContext = new MyDbContext()) {
                dbContext.Entities.Count(); //worked
                dbContext.Entities.Count(m => m.Id > 0); //worked
                dbContext.Entities.CountAsync(m => m.Id > 0); //worked
                dbContext.Entities.CountAsync(); //Exception
            }

            Console.ReadLine();
        }
    }

    public class MyDbContext : DbContext {
        static MyDbContext() {
            QueryFilterManager.ForceCast = true;
            QueryFilterManager.Filter<ISoftDelete>("SoftDelete", q => q.Where(x => x.IsDeleted == 0));
            QueryFilterManager.Filter<IMultiTenant>("MultiTenant", q => q.Where(x => x.TenantId == 1));
        }

        public MyDbContext() {
            QueryFilterManager.InitilizeGlobalFilter(this);
        }

        public virtual DbSet<Entity> Entities { get; set; }
        
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFGetStarted.ConsoleApp.NewDb;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            base.OnModelCreating(modelBuilder);
        }
    }

    public class Entity : ISoftDelete, IMultiTenant {
        public int Id { get; set; }

        public int IsDeleted { get; set; }

        public int TenantId { get; set; }
    }

    public interface ISoftDelete {
        int IsDeleted { get; set; }
    }

    public interface IMultiTenant {
        int TenantId { get; set; }
    }
}

```
System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'System.Collections.Generic.IAsyncEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer]' cannot be used for parameter of type 'System.Collections.Generic.IAsyncEnumerable`1[System.Object]' of method 'System.Collections.Generic.IAsyncEnumerable`1[ConsoleApp2.Entity] Cast[Entity](System.Collections.Generic.IAsyncEnumerable`1[System.Object])'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleCast(EntityQueryModelVisitor entityQueryModelVisitor, CastResultOperator castResultOperator)
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.<>c.<.cctor>b__33_3(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel __)
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleCast(HandlerContext handlerContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\jerry\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs:line 14

**Comment by JonathanMagnan** [comment]
Hello @2501272126 ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @2501272126 ,

We looked at this issue but unfortunately, there is nothing we can do for now on our side.

Our library under the hood performs some cast. I can easily reproduce this error without our library

```csharp
var count1 = ctx.MyTables
    .Where(x => x.SomeKey > 5)
    .Cast<IMyTable>()
    .Cast<MyTable>()
    .Count(x => true);  // worked

var count2 = ctx.MyTables
    .Where(x => x.SomeKey > 5)
    .Cast<IMyTable>()
    .Cast<MyTable>()
    .Count(x => true); // worked

var count3 = ctx.MyTables
    .Where(x => x.SomeKey > 5)
    .Cast<IMyTable>()
    .Cast<MyTable>()
    .CountAsync(x => true); // worked

var count4 = ctx.MyTables
    .Where(x => x.SomeKey > 5)
    .Cast<IMyTable>()
    .Cast<MyTable>()
    .CountAsync(); // Exception
```

It looks more like an error in `Entity Framework` and how they handle differently CountAsync with an expression and without the expression.

Let me know if you need a better explanation.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
In seems weird but a workaround until it gets fixed is to always include a predicate such as `x => true`... It will always be true but at least, it will work...

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_
