### ISSUE TITLE
Null exception performing BulkDelete

### ISSUE THREAD

**Issue by BloodBaz** [zzzprojects/EntityFramework-Plus#294]
A number places where existing code has started to raise exceptions when performing a `DeleteFromQuery` operation.  The exception is pretty buried:

     at (Object , String , StringComparison )
     at StringExtensions.(String , String )
     at ..(Schema , ComplexPropertyMapping )
     at Z.Internal.EntityFramework.Extensions.BLL.GetModel..(ComplexPropertyMapping )
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at Z.Internal.EntityFramework.Extensions.BLL.GetModel..(EntityTypeMapping )
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at Z.Internal.EntityFramework.Extensions.BLL.GetModel..(EntitySetMapping )
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at ..(Schema , Schema , SchemaMapping )
     at ..(Schema , SchemaMapping , Schema )
     at ..(String , String , String , String )
     at ..(DbContext )
     at ..(DbContext )
     at DbContextExtensions.GetModel(DbContext this)
     at DbContextExtensions.[](IQueryable`1 , Action`1 , CancellationToken )
     at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query, Action`1 bulkOperationFactory)
     at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query)`

The code that calls `DeleteFromQuery` is as follows:

    if(delList.Length > 0)
        ctx.GroupUsers
            .Where(g => g.UserID == userID &&
                delList.Contains(g.GroupID))
            .DeleteFromQuery();`

Where `GroupUsers` is a simply many-many between Groups and Users and `delList` is an `int` array with non-duplicated elements.

**Comment by JonathanMagnan** [comment]
Hello @BloodBaz ,

The problem happens when we get your model. 

It's possible that your model has been modified? Do you think you could provide us your model to check it: info@zzzprojects.com

**Database First**
Simply send us your .edmx file.

**Code First**
You can generate your XML model by using the following method. 

``` csharp
public string GetModelXDocument(DbContext context)
{
    XDocument doc;
    using (var memoryStream = new MemoryStream())
    {
        using (XmlWriter xmlWriter = XmlWriter.Create(memoryStream, new XmlWriterSettings { Indent = true }))
        {
            EdmxWriter.WriteEdmx(context, xmlWriter);
        }

        memoryStream.Position = 0;

        doc = XDocument.Load(memoryStream);
    }
    return doc.ToString();
}
```

**Comment by JonathanMagnan** [comment]
Hello @BloodBaz ,

I believe we have we haven't heard back from you.

Let me know if you can provide the information we asked.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @BloodBaz ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan
