### ISSUE TITLE
Exception (IDENTITY_INSERT is OFF) when inserting AuditEntry

### ISSUE THREAD

**Issue by dnataraj** [zzzprojects/EntityFramework-Plus#3]
When I try to insert an an entity being audited, we get :
``
Fail: Microsoft.AspNet.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      Microsoft.Data.Entity.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert explicit value for identity column in table 'AuditEntry' when IDENTITY_INSERT is set to OFF.
         at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at System.Data.SqlClient.SqlDataReader.get_MetaData()
         at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
         at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
         at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
         at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
         at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
         at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
``
We are using EF 7.0.0-rc1-final. We're just introducing Auditing to a working application. Are we missing a step? Thanks.

**Comment by dnataraj** [comment]
Actually this was a misunderstanding on my part. I didn't realize that a new instance of Audit was needed per SaveChanges() - got this working!

**Comment by zzzprojects** [comment]
We added in the documentation a comment to allow to re-use the save audit in multiple SaveChanges. We hope to improve our documentation very soon.

```csharp
AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
    // ADD "Where(x => x.AuditEntryID != 0)" to allow multiple SaveChanges with same Audit
    (context as EntityContext).AuditEntries.AddRange(audit.Entries);
```
