### ISSUE TITLE
SQL syntax error on MariaDB batchupdate

### ISSUE THREAD

**Issue by rmadisonhaynie** [zzzprojects/EntityFramework-Plus#311]
I'm having some issues with batch update, claiming a SQL syntax error.

Here is my code:
My MemberInitExpression:
`        public Expression<Func<InsertionOrder, InsertionOrder>> NewModelExpression(IDictionary<string, InsertionOrder> updateRecords)
        {
            return (x) => new InsertionOrder()
            {
                IoSignedByClient = updateRecords[x.GetKey()].IoSignedByClient,
                LanguageCode = updateRecords[x.GetKey()].LanguageCode
            };
        }`
UpdateAsync invocation:
` await dbSet.Where(x => updatedRecords.ContainsKey(x.GetKey()))
                .UpdateAsync(new T().NewModelExpression(updatedRecords));`

This is the storeCommand from BatchUpdate

> UPDATE `InsertionOrders` AS A
INNER JOIN ( SELECT `x`.`IOName`, `x`.`IoSignedByClient`, `x`.`LanguageCode`
FROM `InsertionOrders` AS `x`
           ) AS B ON A.`IOName` = B.`IOName`
SET A.`IoSignedByClient` = `x`.`IOName`, `x`.`IoSignedByClient`, `x`.`LanguageCode`,
A.`LanguageCode` = `x`.`IOName`, `x`.`IoSignedByClient`, `x`.`LanguageCode`

Seems like some issue with using expressions as the updated value?
I'm using Pomelo.EntityFrameworkCore.MySql Version=2.0.1
Stack trace below..
Any help would be great! Thank you

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `x`.`LanguageCode`,
A.`LanguageCode` = `x`.`IOName`, `x`.`IoSignedByClient`, `' at line 5

at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 106
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__65.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 297
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__64.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 287
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MySqlConnector.Core.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MySqlConnector.Core.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 60
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.<>c__DisplayClass2_0`1.<UpdateAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sync.Biz.ShieldAccess.<SegmentData>d__7`1.MoveNext() in C:\GitLab\Sync\Biz\ShieldAccess.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sync.Biz.ShieldAccess.<UpdateDb>d__2`1.MoveNext() in C:\GitLab\Sync\Biz\ShieldAccess.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sync.Biz.ShieldSync.<SyncWithShield>d__4`2.MoveNext() in C:\GitLab\Sync\Biz\ShieldSync.cs:line 41

**Comment by JonathanMagnan** [comment]
Hello @rmadisonhaynie ,

Thank you for reporting. I believe this issue is caused because we do not support `Pomelo` yet and our library assume probably that's SQL Server by default.

We will look at it and try to fix it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rmadisonhaynie ,

We started to investigate this issue, it seems everything already works with `Pomelo` but something seems weird.

As you probably know, the goal for `BatchUpdate` is to get everything executing in database side.

However, when you use the following code `updateRecords[x.GetKey()]`, the `x` is a row that exists only on the database side and the `updateRecords` on the server side. This logic simply cannot work. You cannot retrieve the server-side value using some database side value because this kind of value is not loaded in the context.

I'm not sure if my explanation is clear but let me know if you need a better one.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rmadisonhaynie ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
