### ISSUE TITLE
NullReferenceException while performs an implicit conversion from QueryFutureValue to TResult.

### ISSUE THREAD

**Issue by maratoss** [zzzprojects/EntityFramework-Plus#333]
Hi! i have got NullReferenceException when run the following code
```cs
Employee orderHeadEmployee = orderHead.Employee 
	?? (orderHead.EmployeeId != 0 
		? context.EmployeeList
			.DeferredSingleOrDefault(x => x.EmployeeId == orderHead.EmployeeId)
			.FutureValue() 
		: null);
```

but this works with explicit cast to Employee:
```cs
Employee orderHeadEmployee = orderHead.Employee 
	?? (orderHead.EmployeeId != 0 
		? context.EmployeeList
			.DeferredSingleOrDefault(x => x.EmployeeId == orderHead.EmployeeId)
			.FutureValue() 
		: (Employee)null); // cast
```
StackTrace:
```
   at Z.EntityFramework.Plus.QueryFutureValue`1.op_Implicit(QueryFutureValue`1 futureValue) in D:\repositories\EntityFramework-Plus\src\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureValue.cs:line 149
   at OS.Tests.Integration.asdasd.test() in tests.Integration\asdasd.cs:line 15
```

this snippet also throws exception:
```cs
            QueryFutureValue<Employee> futureValue = null;
            Employee emp = futureValue;
```

**Comment by JonathanMagnan** [comment]
Hello @maratoss ,

Thank you for reporting. We will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @maratoss ,

My developer tried it but didn't successfully reproduce the issue.

Could you provide us a test project with the issue?

He will look again using the project.

Best Regards,

Jonathan

**Comment by maratoss** [comment]
i added test to show the problem

**Comment by JonathanMagnan** [comment]
Hello @maratoss ,

The v1.7.7 has been released with your fix.

Thank a lot for your contribution.

Best Regards,

Jonathan
