### ISSUE TITLE
Batch Delete does not work when query is built with FromSql

### ISSUE THREAD

**Issue by Coder3333** [zzzprojects/EntityFramework-Plus#342]
I am using FromSQL from Microsoft.EntityFrameworkCore.RelationalQueryableExtensions to generate an EF query.  When I do this, batch delete throws an error.  As long as I do not use FromSQL, batch delete works fine.  This is with Z.EntityFramework.Plus.EFCore 1.7.17.

`                
                using (var e = db.GetEntities<ESUtilsxTestsEntities>())
                {
                    var originalRecords = e.TestDatas.ToList();

                    var recordToDelete = originalRecords.First();

                    var param = new SqlParameter("@param1", recordToDelete.TestDataId);
                    var query =
                    e.TestDatas.FromSql($"select d.* from [ESUtilsTest].[TestData] d where d.[TestDataId] = @param1"
                    , param);

                    // this line correctly returns the result from the query
                    var result = query.AsQueryable().ToList();

                    // batch delete does not work with a query built with FromSql 
                    query.AsQueryable().Delete();

                    // as long as I do not use FromSql, this works
                    e.TestDatas.Where(d => d.TestDataId == recordToDelete.TestDataId)
                        .Delete();

                    var modifiedRecords = e.TestDatas.ToList();

                    AssertES.False(modifiedRecords.Any(r => r.TestDataId == recordToDelete.TestDataId)
                        , "Did not delete record");

                }

`

Stack trace from error:
No mapping exists from object type System.Object[] to a known managed provider native type.
   at System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Object value, Boolean inferLen, Boolean streamAllowed)
   at System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters)
   at System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)

**Comment by JonathanMagnan** [comment]
Hello @Coder3333 ,

The `Batch Delete` feature requires a LINQ Query. We cannot support `FromSql` as we are not certain of the Entity Type, of the column returned by the query, etc...  

Unfortunately, there is no plan currently to support something like this.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Coder3333 ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
