### ISSUE TITLE
Select projection are not supported in EF+ Query IncludeFilter

### ISSUE THREAD

**Issue by MNF** [zzzprojects/EntityFramework-Plus#350]
I’ve tried to use IncludeFilter and got 

> System.Exception: Oops! Select projection are not supported in EF+ Query IncludeFilter. For more information, contact us: info@zzzprojects.com
>    at Z.EntityFramework.Plus.QueryIncludeFilterProvider`1.CreateQuery[TElement](Expression expression)
>    at System.Linq.Queryable.GroupBy[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)

The code that calls IncludeFilter does not directly call select projection
```

        var query = dbContext.tblProfiles
                .IncludeFilter(pax => pax.tblOptions.Where(pfo => pfo.OptionType == "MyType"));
```
It had GroupBy as  subsequent call.

Could you please provide better error description in exception, as well as document extra limitation in the http://entityframework-plus.net/query-include-filter

**Comment by JonathanMagnan** [comment]
Hello @MNF ,

Thank you for reporting.

Projection limitation has been added to our new websites that should go in prod within a few days.

We will try to work in a few months again on `EF+` to remove some limitations on current features.

Best Regards,

Jonathan
