### ISSUE TITLE
Audit - NullReferenceException when deleting a record and using a property formatter

### ISSUE THREAD

**Issue by GugaWedge** [zzzprojects/EntityFramework-Plus#381]
I believe this issue might be related to https://github.com/zzzprojects/EntityFramework-Plus/issues/239 .

Using vs 1.8.4 of Z.EntityFramework.Plus.EF6 and Z.EntityFramework.Plus.Audit.EF6.
Using EntityFramework 6.2.0.

When deleting a model using the standard EF  .Remove method of a db set and saving the context changes an exception is thrown if i have defined any property formatters, even if they are not related to that model.

ex: if i define 

AuditManager.DefaultConfiguration.Format<UnrelatedModel>(x => x.AnyProperty, x => "my formatted text");

and try to do

await var anotherModel = dbContext.AnotherDbSet.FirstAsync();
dbContext.AnotherDbSet.Remove(anotherModel);
await dbContext.SaveChangesAsync();

an exception is thrown:

System.NullReferenceException: Object reference not set to an instance of an object.
 at Z.EntityFramework.Plus.AuditConfiguration.FormatValue(Object entity, String propertyName, Object currentValue)
 at Z.EntityFramework.Plus.AuditEntryProperty.get_NewValueFormatted()
 at lambda_method(Closure , Object )
 at System.Data.Entity.Core.Objects.DelegateFactory.GetValue(EdmProperty property, Object target)
 at System.Data.Entity.Core.Objects.StateManagerMemberMetadata.GetValue(Object userObject)
 at System.Data.Entity.Core.Objects.EntityEntry.GetCurrentEntityValue(StateManagerTypeMetadata metadata, Int32 ordinal, Object userObject, ObjectStateValueRecord updatableRecord, Int32 parentEntityPropertyIndex)
 at System.Data.Entity.Core.Objects.ObjectStateEntryDbUpdatableDataRecord.GetRecordValue(Int32 ordinal)
 at System.Data.Entity.Core.Objects.DbUpdatableDataRecord.GetValue(Int32 i)
 at System.Data.Entity.Core.Mapping.Update.Internal.ExtractorMetadata.RetrieveMember(IEntityStateEntry stateEntry, IExtendedDataRecord record, Boolean useCurrentValues, EntityKey key, Int32 ordinal, ModifiedPropertiesBehavior modifiedPropertiesBehavior)
 at System.Data.Entity.Core.Mapping.Update.Internal.ExtractorMetadata.ExtractResultFromRecord(IEntityStateEntry stateEntry, Boolean isModified, IExtendedDataRecord record, Boolean useCurrentValues, UpdateTranslator translator, ModifiedPropertiesBehavior modifiedPropertiesBehavior)
 at System.Data.Entity.Core.Mapping.Update.Internal.RecordConverter.ConvertStateEntryToPropagatorResult(IEntityStateEntry stateEntry, Boolean useCurrentValues, ModifiedPropertiesBehavior modifiedPropertiesBehavior)
 at System.Data.Entity.Core.Mapping.Update.Internal.ExtractedStateEntry..ctor(UpdateTranslator translator, IEntityStateEntry stateEntry)
 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.LoadStateEntry(IEntityStateEntry stateEntry)
 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.PullModifiedEntriesFromStateManager()
 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ProduceCommands()
 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
 at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
 at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
 at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
 at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
 at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
 at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
 at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
 at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
 at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
 at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
 at System.Data.Entity.Internal.InternalContext.SaveChanges()
 at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
 at System.Data.Entity.DbContext.SaveChanges()

I believe the issue comes from the FormatValue.cs file (https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.Audit.Shared/AuditConfiguration/FormatValue.cs) inside the if statement at line 39. Not sure which one of the statements inside that if statement is causing the NRE, but maybe the entity is null on delete and therefore entity.GetType() might be the culprit.

**Comment by JonathanMagnan** [comment]
Hello @GugaWedge ,

Thank you, we will look at it.

**Comment by JonathanMagnan** [comment]
Hello @GugaWedge ,

The v1.8.5 has been released which should fix this issue.

Let me know if that works correctly.

By the way, we are currently working on the v2.x of all our features. They will be added first in our new project: http://entityframework-classic.net/ In short, we will include tons of new built-in features and performance improvement in our fork. For example, we already optimized some case in our fork to be 10x faster than EF6 v6.2 and we are already compatible with .NET Core.

Do you have any features or one of your developer would like we add in our fork? It could be anything as long as it’s related to Entity Framework.

Best Regards,

Jonathan

**Comment by GugaWedge** [comment]
Thank you Jonathan.

I will pull the version and test.

One thing that comes to mind is some form of attribute driven formatting for the audits. For example, if some of my models have encrypted properties that I still want to be audited but would like the property value to be store as a fixed string ("<ENCRYPTED>") i could just decorate those properties or even better use existing attributes to define that:

AuditManager.DefaultConfiguration.FormatPropertyValueIfHasAttribute<MyCustomAttribute>(x => "<ENCRYPTED>")

I'll have a think about it and speak to the other devs here to see if they have any other ideas.

Regards,

Hugo

**Comment by JonathanMagnan** [comment]
Great ;)

Thank a lot for your suggestion. Yes, being able to "hide" some value is a very good suggestion that we have noted.

Best Regards,

Jonathan
