### ISSUE TITLE
The column 'X' was specified multiple times for 'Y'

### ISSUE THREAD

**Issue by psyren89** [zzzprojects/EntityFramework-Plus#418]
Related to #176, I am having the same issue using EF Core 2.1 and MSSQL with Z.EntityFramework.Plus.BatchDelete.EFCore 1.8.2.

An example of my code:
```c#
var foosToDelete = context.Foos.Where(f => !context.Bars.Any(b => b.Code == f.Code));
foosToDelete.Update(_ => new Foo { DeletedAt = DateTime.Now });
```

produces:
```
System.Data.SqlClient.SqlException : The column 'Id' was specified multiple times for 'B'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
...
```

**Comment by psyren89** [comment]
Further to this, after running the SQL Server Profiler, it seems the SQL EF Core is generating is very strange:
```
SELECT [a].[Id], [a].[Code], [a].[CreatedAt], [a].[DeletedAt], [a].[ModifiedAt], [a].[Name], [a].[Id], [a].[Level5_Code], [a].[Level5_Name], [a].[Id], [a].[Level4_Code], [a].[Level4_Name], [a].[Id], [a].[Level3_Code], [a].[Level3_Name], [a].[Id], [a].[Level2_Code], [a].[Level2_Name]
FROM [Aaa] AS [a]
```

**Comment by JonathanMagnan** [comment]
Hello @psyren89 ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by psyren89** [comment]
I'll see what I can do. The issue appears to be related to owned entities.

**Comment by psyren89** [comment]
See these related issues, and a sample project:
https://github.com/aspnet/EntityFrameworkCore/issues/12491
https://github.com/rzlsoftware/EfCoreSqlQueryWithOwnedEntity

**Comment by BBGONE** [comment]
I experience the same error - but it seems that it is only if i use - UseRowNumberForPaging
```
optionsBuilder.UseSqlServer(connection, (options)=> {
                // to support SQL SERVER 2008
                options.UseRowNumberForPaging();
            });
```
the resulting select query is
```
exec sp_executesql N'SELECT [t].[CustomerID], [t].[CompanyName], [t].[ModifiedDate], 
[t].[NameStyle], [t].[PasswordHash], [t].[PasswordSalt], [t].[rowguid], 
[t].[SalesPerson], [t].[Suffix], [t].[Title], [t].[CustomerID0], 
[t].[EmailAddress], [t].[Phone], [t].[FirstName], [t].[LastName], [t].[MiddleName]
FROM (
    SELECT [c].[CustomerID], [c].[CompanyName], [c].[ModifiedDate], [c].[NameStyle], [c].[PasswordHash], 
[c].[PasswordSalt], [c].[rowguid], [c].[SalesPerson], [c].[Suffix], [c].[Title], 
[c].[CustomerID] AS [CustomerID0], [c].[EmailAddress], [c].[Phone], 
[c].[CustomerID] AS [CustomerID0], [c].[FirstName], [c].[LastName], 
[c].[MiddleName], 
ROW_NUMBER() OVER(ORDER BY [c].[LastName], [c].[MiddleName], [c].[FirstName]) AS [__RowNumber__]
    FROM [SalesLT].[Customer] AS [c]
) AS [t]
WHERE ([t].[__RowNumber__] > @__p_0) AND ([t].[__RowNumber__] <= (@__p_0 + @__p_1))',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=50
```
which doubles [CustomerID0] column names

the Customer entity has two owned entities  CustomerName  and CustomerContact:

```
public partial class Customer
    {
        public Customer()
        {
            CustomerAddress = new HashSet<CustomerAddress>();
            SalesOrderHeader = new HashSet<SalesOrderHeader>();
        }

        public int CustomerId { get; set; }
        public bool NameStyle { get; set; }
        public string Title { get; set; }
        public CustomerName CustomerName { get; set; }
        public CustomerContact CustomerContact { get; set; }
        public string Suffix { get; set; }
        public string CompanyName { get; set; }
        public string SalesPerson { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime ModifiedDate { get; set; }
  
        public ICollection<CustomerAddress> CustomerAddress { get; set; }
        public ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
    }
}
```

### Further technical details

EF Core version: Microsoft.EntityFrameworkCore.2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Visual Studio 2017 15.8.8
This bug can be tested on working project: https://github.com/BBGONE/JRIApp.Core
Querying  Customers results in error:
at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
Errors = {System.Data.SqlClient.SqlErrorCollection}
Message = "Column \"CustomerID0\" for \"t\" used more then one time."

**Comment by BBGONE** [comment]
P.S. - As an IT developer i would suggest you (who will resolve this issue) to pass all column lists through a HashSet - to exclude repeated occurences.  I see this issue was first observed  and reported in june 2018, and is still unresolved.

**Comment by turhany** [comment]
I get this error in ef core, is there any progress for solution or workaround?

**Comment by megumus** [comment]
I have same error. when i am using UpdateFromQueryAsync, it's generated shadow property (id) for owned entity. Do you have a solution for this?

**Comment by BBGONE** [comment]
@megumus Did you try Net.Core 2.2 (and it has the related entity framework for this version)? I tried (upgraded the project), and it seems all works fine in my case (before i had the same error).

**Comment by megumus** [comment]
@BBGONE yes we use .net core 2.2.0 and latest version of EntityFramework.Plus

**Comment by cyptus** [comment]
i got the same issue with current versions.
