### ISSUE TITLE
Runtime error in mapping files when using TPH inheritance

### ISSUE THREAD

**Issue by johnknoop** [zzzprojects/EntityFramework-Plus#429]
We have an abstract base class called NotificationScheme with a few subclasses, like EmailNotificationScheme, AssigneeNotificationScheme etc. These are happed to a single table with discriminator column. We've used DevArt´s Entity Developer to generate the mapping files, and everything works like a charm when running the application.

This is how the NotificationScheme mapping looks:

```
    public partial class EmailNotificationSchemeMapping : EntityTypeConfiguration<EmailNotificationScheme> {

        public EmailNotificationSchemeMapping() {
            this
                .Map(tph => { 
                    tph.Requires("Recipient").HasValue("Email");
                    tph.ToTable("NotificationScheme");
                });
            this.Property(p => p.EmailAddress)
                    .IsRequired()
                    .IsUnicode(false);
            OnCreated();
        }

        partial void OnCreated();

    }
```

When I run this in a test using Effort as in-memory database however, the code above causes this exception:

```
Message: System.MissingMethodException : Method not found: 'System.Data.Entity.ModelConfiguration.Configuration.EntityMappingConfiguration`1<!0> System.Data.Entity.ModelConfiguration.Configuration.EntityMappingConfiguration`1.ToTable(System.String)'.

Stack trace:
at BreezeProduction.Models.Entity.Local.Mapping.EmailNotificationSchemeMapping.<>c.<.ctor>b__0_0(EntityMappingConfiguration`1 tph)
   at System.Data.Entity.ModelConfiguration.EntityTypeConfiguration`1.Map(Action`1 entityMappingConfigurationAction)
   at BreezeProduction.Models.Entity.Local.Mapping.EmailNotificationSchemeMapping..ctor() in C:\work\breeze\src\BreezeProduction\Models\Entity\Local\Mapping\EmailNotificationSchemeMap.cs:line 22
   at BreezeProduction.Models.Entity.Local.BreezeLocalDatabase.OnModelCreating(DbModelBuilder modelBuilder) in C:\work\breeze\src\BreezeProduction\Models\Entity\Local\LocalDatabase.BreezeLocalDatabase.cs:line 251
   at System.Data.Entity.Internal.LazyInternalContext.CreateModelBuilder()
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet`1.Add(TEntity entity)
```

Looking at the stack trace, the exception doesn't occur in any of your code, but since it works when running against a real MySql database, I still thought I might report this here. Any ideas what this might be?

**Comment by johnknoop** [comment]
Wrong repository 🤦‍♂️
