### ISSUE TITLE
PostgreSQL Delete throws Exception

### ISSUE THREAD

**Issue by Cooksauce** [zzzprojects/EntityFramework-Plus#455]
Occurs when calling the following method while using EF Core and PostgreSQL:

`IQueryable.Delete()`

Exception (Items inside the ** symbols are removed file paths):
{System.ArgumentException: Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'System.Linq.EnumerableQuery`1[*redacted(custom type)*]'.
   at System.Reflection.RtFieldInfo.CheckConsistency(Object target)
   at System.Reflection.RtFieldInfo.InternalGetValue(Object obj, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 source)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at *redacted* in *redacted*
   at System.Reflection.RtFieldInfo.CheckConsistency(Object target)
   at System.Reflection.RtFieldInfo.InternalGetValue(Object obj, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 source)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at *redacted* in *redacted*

**Comment by JonathanMagnan** [comment]
Hello @Cooksauce ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
