### ISSUE TITLE
Batch update with joins: Multi-part identifier could not be bound

### ISSUE THREAD

**Issue by fschmied** [zzzprojects/EntityFramework-Plus#463]
When I call `Update` in a complex scenario involving many joins, invalid SQL is generated. The error message and stack trace are:
```
System.Data.SqlClient.SqlException : The multi-part identifier "Extent4.String" could not be bound.
The multi-part identifier "Join1.Status" could not be bound.
The multi-part identifier "Join1.Restrictions_Restriction1" could not be bound.
The multi-part identifier "Join1.Restrictions_Restriction2" could not be bound.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
   at EFPlusReproSampleTest.Repro() in C:\Development\SignPath.Application\src\SignPath.Application.Domain.ReadModel.Tests\CoreDomain\Implementation\CrossCuttingConcerns\EFPlusReproSampleTest.cs:line 27
```

Here's a full repro sample (put into an NUnit test):
```
  [TestFixture]
  public class EFPlusReproSampleTest
  {
     [Test]
    public void Repro ()
    {
      var changedUpdatedEntityIds = new[] { Guid.NewGuid() };

      var changedJoinedEntity1Ids = new[] { Guid.NewGuid() };
      var changedIndirectlyJoinedEntityIds = new[] { Guid.NewGuid() };

      var changedJoinedEntity2Ids = new[] { Guid.NewGuid() };

      
      var dbContext = new ReproDbContext("Data Source=localhost;Initial Catalog=EFPlusReproSample;Integrated Security=SSPI;ConnectRetryCount=0;Application Name=ReproSample");
      dbContext.Database.CreateIfNotExists();

      dbContext.Set<UpdatedEntity>()
          .Where(
              sp => changedUpdatedEntityIds.Contains(sp.UpdatedEntityId)
                    || changedJoinedEntity2Ids.Contains(sp.JoinedEntity2.JoinedEntity2Id)
                    || changedJoinedEntity1Ids.Contains(sp.JoinedEntity1.JoinedEntity1Id)
                    || changedIndirectlyJoinedEntityIds.Contains(sp.JoinedEntity1.IndirectlyJoinedEntity.IndirectlyJoinedEntityId))
          .Update(
              u => new UpdatedEntity
                    {
                      Status = !u.IsActive
                          ? UpdatedEntityStatus.Inactive
                          : u.RestrictedBool && u.JoinedEntity2.String == null
                              ? UpdatedEntityStatus.Invalid
                              : u.JoinedEntity1.Status != JoinedEntity1Status.Valid
                                  ? UpdatedEntityStatus.Invalid
                                  : u.JoinedEntity1.Restrictions.Restriction1 && u.RestrictedNumber == 0
                                      ? UpdatedEntityStatus.Invalid
                                      : u.JoinedEntity1.Restrictions.Restriction2 && !u.RestrictedBool
                                          ? UpdatedEntityStatus.Invalid
                                          : UpdatedEntityStatus.Valid
                    });
    }
  }

  class ReproDbContext : DbContext
  {
    public ReproDbContext (string nameOrConnectionString)
        : base(nameOrConnectionString)
    {
    }

    protected override void OnModelCreating (DbModelBuilder modelBuilder)
    {
      base.OnModelCreating(modelBuilder);

      modelBuilder.Entity<UpdatedEntity>()
          .HasKey(x => x.UpdatedEntityId);
      modelBuilder.Entity<UpdatedEntity>()
          .HasRequired(x => x.JoinedEntity1)
          .WithMany();
      modelBuilder.Entity<UpdatedEntity>()
          .HasRequired(x => x.JoinedEntity2)
          .WithMany(y => y.UpdatedEntities);

      modelBuilder.Entity<JoinedEntity1>()
          .HasKey(x => x.JoinedEntity1Id)
          .HasOptional(x => x.IndirectlyJoinedEntity)
          .WithRequired();

      modelBuilder.ComplexType<RestrictionsComplexType>();

      modelBuilder.Entity<IndirectlyJoinedEntity>()
          .HasKey(x => x.IndirectlyJoinedEntityId);
    }
  }

  public class UpdatedEntity
  {
    public Guid UpdatedEntityId { get; set; }

    public Guid JoinedEntity1Id { get; set; }
    public JoinedEntity1 JoinedEntity1 { get; set; }

    public Guid JoinedEntity2Id { get; set; }
    public JoinedEntity2 JoinedEntity2 { get; set; }

    public bool IsActive { get; set; }
    public UpdatedEntityStatus Status { get; set; }
    public int RestrictedNumber { get; set; }
    public bool RestrictedBool { get; set; }
  }

  public enum UpdatedEntityStatus
  {
    Valid,
    Invalid,
    Inactive
  }

  public class JoinedEntity1
  {
    public Guid JoinedEntity1Id { get; set; }
    public RestrictionsComplexType Restrictions { get; set; }
    public JoinedEntity1Status Status { get; set; }
    public IndirectlyJoinedEntity IndirectlyJoinedEntity { get; set; }
  }

  public enum JoinedEntity1Status
  {
    Valid,
    Pending,
    Inactive
  }

  public class RestrictionsComplexType
  {
    public bool Restriction1 { get; private set; }

    public bool Restriction2 { get; private set; }
  }

  public class IndirectlyJoinedEntity
  {
    public Guid IndirectlyJoinedEntityId { get; set; }
  }

  public class JoinedEntity2
  {
    public Guid JoinedEntity2Id { get; set; }
    public JoinedEntity2Status Status { get; set; }
    public ICollection<UpdatedEntity> UpdatedEntities { get; set; }
    public string String { get; set; }
  }

  public enum JoinedEntity2Status
  {
    Valid,
    Invalid,
    Inactive
  }
```

- EF version: 6.1.3
- EF Plus version: 1.8.21
- Database Provider: SqlServer

**Comment by fschmied** [comment]
Might be similar to #447, but I'm still posting a new issue because it might be a separate case.
(#107 also had a similar problem.)

**Comment by JonathanMagnan** [comment]
Hello @fschmied ,

Thank you for the information,

Looking at your expression in the `Update`, I don't think we support this kind of scenario but we will still look at it to make sure.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @fschmied ,

The support for `joins` has been added.

However, to make it works, you will need to include first all tables you will use to set your values as we retrieve the information from the query that's generated from Entity Framework.

Example:

```csharp
dbContext.Set<UpdatedEntity>().Include(x => x.JoinedEntity1).Include(x => x.JoinedEntity2)
	.Where(
		sp => changedUpdatedEntityIds.Contains(sp.UpdatedEntityId)
			  || changedJoinedEntity2Ids.Contains(sp.JoinedEntity2.JoinedEntity2Id)
			  || changedJoinedEntity1Ids.Contains(sp.JoinedEntity1.JoinedEntity1Id)
			  || changedIndirectlyJoinedEntityIds.Contains(sp.JoinedEntity1.IndirectlyJoinedEntity.IndirectlyJoinedEntityId))
	.Update(
		u => new UpdatedEntity
		{
			Status = (!u.IsActive
				? UpdatedEntityStatus.Inactive
				: u.RestrictedBool && u.JoinedEntity2.String == null
					? UpdatedEntityStatus.Invalid
					: u.JoinedEntity1.Status != JoinedEntity1Status.Valid
						? UpdatedEntityStatus.Invalid
						: u.JoinedEntity1.Restrictions.Restriction1 && u.RestrictedNumber == 0
							? UpdatedEntityStatus.Invalid
							: u.JoinedEntity1.Restrictions.Restriction2 && !u.RestrictedBool
								? UpdatedEntityStatus.Invalid
								: UpdatedEntityStatus.Valid ) 
		});
```

Let me know if that's working as expected.
