### ISSUE TITLE
Batch update with parameters and navigation properties doesn't work

### ISSUE THREAD

**Issue by RudeySH** [zzzprojects/EntityFramework-Plus#471]
### Description
Batch updates using one-to-many navigation properties work. Batch updates using parameters work. Batch updates using both one-to-many navigation properties AND parameters don't work.

### Exception
```
Exception message: The multi-part identifier "Project1.C1" could not be bound.
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.<>c__DisplayClass2_0`1.<UpdateAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

### Fiddle or Project
https://dotnetfiddle.net/mE34Ez

### Further technical details
- EF version: 6.2.0
- EF Plus version: 1.8.23 (latest as of 8 April 2019)
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

Thank you for reporting, we will try to look at it this week.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

After some investigation, we choose to pause this request until we re-write the code of the library.

As you noticed, we support some scenario with the count but unfortunately, since most part of the library is generated via `Entity Framework`, we are also limited in what we can support.

However, we will keep this request open in our internal issue tracker and make sure we support it when the Batch Update feature will be revamped.

Best Regards,

Jonathan

**Comment by RudeySH** [comment]
OK, thanks for the info. If you're keeping track of this in an internal issue tracker, feel free to close this one.

**Comment by RudeySH** [comment]
It's been a while but I just ran into this again. I can confirm this bug is still in the latest version of this library:

```C#
// this works (uses one-to-many navigation property)
context.Customers.Update(c => new Customer { OrderCount = c.Orders.Count() });
			
// this also works (uses parameter)
var name = "Customer_A";
context.Customers.Where(c => c.Name == name).Update(c => new Customer { OrderCount = 0 });
			
// this doesn't work (uses parameter and one-to-many navigation property)
context.Customers.Where(c => c.Name == name).Update(c => new Customer { OrderCount = c.Orders.Count() });
```

However, I just realized everything seems to work fine when the parameter is an array.

```
// but this WILL work (uses array parameter and one-to-many navigation property)
var names = new[] { "Customer_A" };
context.Customers.Where(c => c.Name == name).Update(c => new Customer { OrderCount = c.Orders.Count() });
```

I'm guessing the reason array parameters work because arrays aren't actually parameters in the SQL, instead the array values just get inlined into the query.
