### ISSUE TITLE
Navigation properties don't work properly in batch updates (EF6)

### ISSUE THREAD

**Issue by RudeySH** [zzzprojects/EntityFramework-Plus#475]
### Description
While using navigation collections seems to work great in 1.8.25, I just ran into an issue using navigation properties. I have departments and companies. Both entities have a `Name` property. When I use batch updates to set the department's name equal to it's company's name, it doesn't work.

```
context.Departments.Update(d => new Department { Name = d.Company.Name }); // doesn't work as expected
```

It doesn't throw. The generated SQL query just uses the wrong `Name` column in the assignment, and the name of the departments are never changed.

The batch update **will** throw if the receiving entity of an assignment doesn't have equal column names like in my example above. See the fiddle for more details.

### Exception
```
Exception message: Invalid column name 'Name'.
Stack trace:
[System.Data.SqlClient.SqlException: Invalid column name 'Name'.]
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
```

### Fiddle or Project
https://dotnetfiddle.net/jqHUbl

### Further technical details
- EF version: 6.2.0
- EF Plus version: 1.8.25 (latest as of 10 April 2019)
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

Thank you for the Fiddle. We will look at it to determine if you have reached a limitation of our library or if that's possible for us to support it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

## Problem 2
It is possible to make it works by using the Include method:

```csharp
context.Employees.Include(x => x.Department).Update(e => new Employee
			{
				DepartmentName = e.Department.Name
			});
```

The SQL is generated via `Entity Framework`, so using the `Include` allow to add some more properties to be used later in the Update statement.

## Problem 1
Unfortunately for this one, nothing will be done at this moment. We support the case when property name are different but not when property name are similar.

We will eventually fully re-write this features and we will make sure we support this case when it will be done.

**Comment by RudeySH** [comment]
Alright, good to know `Include` partially fixes the issue. Because this issue won't be fixed at this moment, should we close this issue then?

**Comment by JonathanMagnan** [comment]
Yes, let close it, there is enough open issue like this ;(
