### ISSUE TITLE
Exception is being thrown: 'The space 'CSSpace' has no associated collection'

### ISSUE THREAD

**Issue by mikehac** [zzzprojects/EntityFramework-Plus#497]
### Description
When trying to do bulk delete as following:
```cs
public DbSet<DevicePackageHistory> DevicePackageHistories { get; set; }
DbContext _unitOfWork = new DbContext();
_unitOfWork.DevicePackageHistories.Where(dph => dph.ID == 3).Delete();`
```

### Exception
Exception message:
The space 'CSSpace' has no associated collection.
Stack trace:
   at System.Data.Metadata.Edm.MetadataWorkspace.GetItemCollection(DataSpace dataSpace, Boolean required)
   at System.Data.Metadata.Edm.MetadataWorkspace.GetItems(DataSpace dataSpace)
   at Z.EntityFramework.Plus.Internal.Model.GetModelNames(DbContext this)
   at Z.EntityFramework.Plus.Internal.Model.GetDatabaseFirst(DbContext context)
   at Z.EntityFramework.Plus.InternalExtensions.GetModel(DbContext context)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query)

But when I run this:
```cs
        DbContext _unitOfWork = new DbContext();
	if (_unitOfWork.DevicePackageHistories.Where(dph => dph.ID==0).Count() == 0)
	{
		_unitOfWork.DevicePackageHistories.Where(dph => dph.ID==0).Delete();
	}
```
Everything works fine.
What am I doing wrong?

### Further technical details
- EF version:5.0.0
- EF Plus version:1.9.3
- Database Provider:MS SQL

**Comment by JonathanMagnan** [comment]
Hello @mikehac ,

Could you provide a runnable solution with this issue?

It happens when we try to read your model. Without a project, this kind of issue is a way to hard to reproduce.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by mikehac** [comment]
Hi @JonathanMagnan 
[Here](https://github.com/mikehac/EntityFrameworkPlusTest.git) is my repository which contains runnable solution and sql script to create a ms db. We have checked this issue on 3 machines with windows 10x64, Microsoft SQL server 2012 r2. It fails when you run the exe file directly, not in debug mode.
The exceptions is:
Unhandled Exception: System.InvalidOperationException: The space 'CSSpace' has no associated collection.
  at System.Data.Metadata.Edm.MetadataWorkspace.GetItemCollection(DataSpace dataSpace, Boolean required)
  at System.Data.Metadata.Edm.MetadataWorkspace.GetItems(DataSpace dataSpace)
  at Z.EntityFramework.Plus.Internal.Model.GetModelNames(DbContext this)
  at Z.EntityFramework.Plus.Internal.Model.GetDatabaseFirst(DbContext context)
  at Z.EntityFramework.Plus.InternalExtensions.GetModel(DbContext context)
  at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
  at EntityFrameworkPlusTest.Program.Main(String[] args) in C:\Users\user\Desktop\EntityFrameworkPlusTest-master\EntityFrameworkPlusTest\Program.cs:line 14

**Comment by JonathanMagnan** [comment]
Thank for the project, we will look at it this week.

**Comment by JonathanMagnan** [comment]
Hello @mikehac ,

The v1.9.5 has been released.

Could you try it and let me know if that's working.

**Comment by mikehac** [comment]
Hi @JonathanMagnan ,
Thank you so much for trying to help me, I'll check it tomorrow at work and inform you with the results.
Best regards,

**Comment by mikehac** [comment]
Hi @JonathanMagnan 
It seems working, no exceptions.
Good work!!
