### ISSUE TITLE
multiple includefilters on more than 3rd level

### ISSUE THREAD

**Issue by vlapenkov** [zzzprojects/EntityFramework-Plus#499]
Existing query on EF core looks this way
 ```
_db.Contracts.Include(x => x.ContractKind)
                .Include(x => x.ContractParticipants)
                    .ThenInclude(x => x.ParticipantType)
                .Include(x => x.BillObjects)
                    .ThenInclude(x => x.Rfsubject)
                   .Include(x => x.BillObjects)
                         .ThenInclude(x => x.LinkBillObjectWithEnergyLinkObjects)
                          .ThenInclude(x => x.EnergyLinkObject)
                          .ThenInclude(x => x.LinkEnergyLinkObjectWithBillPoints)
                          .ThenInclude(x => x.BillPoint)
                          .ThenInclude(x => x.LinkBillPointWithMeterPoints)
```
I need to filter by date on 7th and 9th query strings, like : 
`ThenInclude(x => x.LinkBillObjectWithEnergyLinkObjects).Where(link=>link,StartDate<param1)`
and  `.ThenInclude(x => x.BillPoint).Where (billPoint=>billPoint.StartDate<param2)`

Can i do that?      If yes, please write query i don't understand how to do it.

**Comment by JonathanMagnan** [comment]
Hello @vlapenkov ,

From what I remember, you cannot mixes `Include` or `ThenInclude` with `IncludeFilter`, you need to use `IncludeFilter` all the way.

We opened a task here to add support to `ThenIncludeFilter`, I don't think it will be hard (I might be wrong).

I don't have your model so the following code contains probably a lot of error but will give you an idea about how to do it:

```csharp
_db.Contracts.IncludeFilter(x => x.ContractKind)
               .IncludeFilter(x => x.ContractParticipants)
                  .IncludeFilter(x => x.ContractParticipants.x.ParticipantType)
               .IncludeFilter(x => x.BillObjects)
                  .IncludeFilter(x => x.BillObjects.x.Rfsubject)
                  .IncludeFilter(x => x.BillObjects)
                         .IncludeFilter(x => x.BillObjects.SelectMany(y => y.LinkBillObjectWithEnergyLinkObjects.Where(link => link.StartDate<param1)))
                         .IncludeFilter(x => x.BillObjects.EnergyLinkObject)
                         .IncludeFilter(x => x.BillObjects.SelectMany(y => y.LinkEnergyLinkObjectWithBillPoints))
                         .IncludeFilter(x => x.BillObjects.SelectMany(y => y.BillPoint.Where(billPoint => billPoint.StartDate<param2))
                         .IncludeFilter(x => x.BillObjects.SelectMany(y => y.LinkBillPointWithMeterPoints));
```

I will try to work on the `ThenIncludeFilter` during the weekend to check if we can easily support it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by vlapenkov** [comment]
Thank you. I examined filters and they worked on either level.

**Comment by JonathanMagnan** [comment]
Great :)

We will let you know when the `ThenFilter` will be ready.

We tried this week but it was more complicated than expected.

**Comment by omatrot** [comment]
Hi @JonathanMagnan .
I would be interrested by the ThenIncludeFilter feature.
Is it still planned?
If not, any guideline on how to achieve it?
Thanks in advance.

**Comment by JonathanMagnan** [comment]
Hello @omatrot ,

The last time we tried the `ThenIncludeFilter`, we didn't succeed to complete it. We will eventually make it happen but at this moment, we don't find enough time.

Everything you can do with the `ThenIncludeFilter`, you were able to do it in `EF6` with the `Include` method. So to achieve it, you simply need something like:

```csharp
context.A.Include(x => x.B).Include(x => x.B.SelectMany(y => y.C));
```

**Comment by omatrot** [comment]
@JonathanMagnan I'm not sure I'm following:

Here is my actual query:

```
context.AlertDetailsDbSet

                    .Include(ad => ad.TrackedVehicule).ThenInclude(v => v.Device).ThenInclude(d => d.Registration)
                    .Include(ad => ad.TrackedVehicule).ThenInclude(v => v.GpsBoxTypeNavigation).ThenInclude(bt => bt.Icon)
                    .Include(ad => ad.TrackedVehicule).ThenInclude(v => v.VehiculeGpsBoxInfo).ThenInclude(a => a.VehiculeConfigurationNavigation)
                    //.Include(ad => ad.TrackedVehicule).ThenIncludeFilter(v => v.FleetDetail.Where(fd => fd.RowEnabled == true)).IncludeFilter(v2 => v2.FleetDetail.Select(u => u.Fleet).Where(f => f.RowEnabled == true && f.CompanyId == companyID))
                    .Include(ad => ad.Alert).ThenInclude(a => a.AlertInstructions)
```

I've added a commented out "ThenIncludFilter" to express what I'm trying to achieve.

Early in the thread, you say that we have to IncludeFilter all the way.
I've tried that but it fails, so the following query:

```
                    context.AlertDetailsDbSet

                    .IncludeFilter(ad => ad.TrackedVehicule).IncludeFilter(ad => ad.TrackedVehicule.Device).IncludeFilter(ad => ad.TrackedVehicule.Device.Registration)
                    .IncludeFilter(ad => ad.TrackedVehicule).IncludeFilter(ad => ad.TrackedVehicule.GpsBoxTypeNavigation).IncludeFilter(ad => ad.TrackedVehicule.GpsBoxTypeNavigation.Icon)
                    .IncludeFilter(ad => ad.TrackedVehicule).IncludeFilter(ad => ad.TrackedVehicule.VehiculeGpsBoxInfo).IncludeFilter(ad => ad.TrackedVehicule.VehiculeGpsBoxInfo.VehiculeConfigurationNavigation)
                    //.Include(ad => ad.TrackedVehicule).ThenIncludeFilter(v => v.FleetDetail.Where(fd => fd.RowEnabled == true)).IncludeFilter(v2 => v2.FleetDetail.Select(u => u.Fleet).Where(f => f.RowEnabled == true && f.CompanyId == companyID))
                    .IncludeFilter(ad => ad.Alert).IncludeFilter(ad => ad.Alert.AlertInstructions)
```
Throws the following exception:

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Processing of the LINQ expression 'source => (IEnumerable<AlertInstructions>)source' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RTE.Technologies.SafeProtect.Common.DummyConsole.Program.Main(String[] args) in C:\Users\olivier.matrot\source\repos\SafeProtect\SafeProtect.Common\SafeProtect.Common.Data.ConsoleTest\Program.cs:line 226

  This exception was originally thrown at this call stack:
    Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessSelectMany(Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.NavigationExpansionExpression, System.Linq.Expressions.LambdaExpression, System.Linq.Expressions.LambdaExpression)
    Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(System.Linq.Expressions.MethodCallExpression)
    System.Linq.Expressions.MethodCallExpression.Accept(System.Linq.Expressions.ExpressionVisitor)
    System.Linq.Expressions.ExpressionVisitor.Visit(System.Linq.Expressions.Expression)
    Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(System.Linq.Expressions.Expression, bool)
    Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(System.Linq.Expressions.Expression)
    Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(System.Linq.Expressions.Expression)
    .(System.Linq.IQueryable, System.Action<System.Linq.IQueryable>, out Microsoft.EntityFrameworkCore.Query.RelationalQueryContext, out object)
    Z.EntityFramework.Extensions.EFPlusExtensions.EFPlusCreateCommand(System.Linq.IQueryable, System.Action<System.Linq.IQueryable>, out Microsoft.EntityFrameworkCore.Query.RelationalQueryContext, out object)
    Z.EntityFramework.Plus.BaseQueryFuture.CreateExecutorAndGetCommand(out Microsoft.EntityFrameworkCore.Query.RelationalQueryContext)
    ...
    [Call Stack Truncated]
Inner Exception 1:
InvalidOperationException: Processing of the LINQ expression 'source => (IEnumerable<AlertInstructions>)source' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.


```

But if I remove the last IncludeFilter line, then it works.

Do I have a solution to my problem to IncludeFiter all the way and achieving a ThenIncludeFilter ?

**Comment by omatrot** [comment]
I made the ThenIncludeFilter work :)
Here is the uncommented line:
`                    .IncludeFilter(ad => ad.TrackedVehicule).IncludeFilter(ad => ad.TrackedVehicule.FleetDetail.Where(fd => fd.RowEnabled == true)).IncludeFilter(ad => ad.TrackedVehicule.FleetDetail.Select(u => u.Fleet).Where(f => f.RowEnabled == true && f.CompanyId == companyId))
`
The remaining problem is that I can't IncludeFilter the last line:
`.IncludeFilter(ad => ad.Alert).IncludeFilter(ad => ad.Alert.AlertInstructions)`
