### ISSUE TITLE
EF plus  fromcache is not tastable?

### ISSUE THREAD

**Issue by grinay** [zzzprojects/EntityFramework-Plus#505]
Hello . I'm writing integrations tests , and face into thing, that FromCache method isn't tastable.
Please help to test it with InMemoryDb if it possible. 
I'm getting this error. 
 Unable to cast object of type 'Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryContext' to type 'Microsoft.EntityFrameworkCore.Query.RelationalQueryContext'.
   at Z.EntityFramework.Plus.InternalExtensions.CreateCommand(IQueryable source, RelationalQueryContext& queryContext) in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus._Core.Shared\EFCore\IQueryable`\CreateCommand.cs:line 161
   at Z.EntityFramework.Plus.QueryCacheManager.GetCacheKey(IQueryable query, String[] tags) in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryCache.Shared\QueryCacheManager.cs:line 340
   at Z.EntityFramework.Plus.QueryCacheManager.GetCacheKey[T](QueryDeferred`1 query, String[] tags) in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryCache.Shared\QueryCacheManager.cs:line 667
   at Z.EntityFramework.Plus.QueryCacheExtensions.FromCacheAsync[T](QueryDeferred`1 query, MemoryCacheEntryOptions options, CancellationToken cancellationToken, String[] tags) in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryCache.Shared\Extensions\QueryDeferred`\FromCacheAsync.cs:line 287

**Comment by grinay** [comment]
Found answer. 
QueryCacheManager.CacheKeyFactory = (queryable, strings) => queryable.ToString() + string.Join(";", strings);
Thanks.
