### ISSUE TITLE
Batch Update fails for enum column and NpgSql

### ISSUE THREAD

**Issue by Stalso** [zzzprojects/EntityFramework-Plus#514]
### Description
I know that you already had [similar issue](https://github.com/zzzprojects/EntityFramework-Plus/issues/353), and in the thread I saw, that it was fixed in v1.8.17 . But it seems to happen again. When I try to call `Update` method and update enum value I am getting exception. My call looks like this 

    await _stageSharingDescriptionRepository.UpdateManyAsync(
                 x => projectStageIds.Contains(x._id) && x.SourceProjectId == projectId,
                 sd => new StageSharingDescription {AccessLevel = accessLevel});

where `AccessLevel ` is enum. This enum is registered like this. In `ApplicationDbContext` static constructor I have made this call

    NpgsqlConnection.GlobalTypeMapper.MapEnum<AccessLevelEnum>();

And in `OnModelCreating` I made this:

    builder.ForNpgsqlHasEnum<AccessLevelEnum>();

### Exception
```
Exception message: 42804: column "AccessLevel" is of type access_level_enum but
 expression is of type integer
Stack trace:
 at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 446
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 332
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1218
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory) in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.BatchUpdate.Shared\BatchUpdate.cs:line 407
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at AwmApi.TaskManagement.Application.ContentAccessServices.ProjectServices.ProjectShareService.ShareForUser(Int32 projectId, ShareItemForUserViewModel model, Int32 userId) in E:\projects\Avant\AwmApi\src\TaskManagement\AwmApi.TaskManagement.Application\ContentAccessServices\ProjectServices\ProjectShareService.cs:line 106
```
### Further technical details
- EF version: 2.2.6
- EF Plus version: 2.0.7
- Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL v2.2.4

**Comment by JonathanMagnan** [comment]
Hello @Stalso ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by rjalexander** [comment]
I am having the same issue as well. The enum for the SET is being passed in as an integer parameter rather than as a postgres enum value.

**Comment by JonathanMagnan** [comment]
Hello @rjalexander ,

If we don't get a project, we cannot investigate it.

Feel free to answer with a runnable project or fiddle and we will re-open this issue.
