### ISSUE TITLE
Pomelo.MySql and BatchUpdate issue 2.0

### ISSUE THREAD

**Issue by Kir-Antipov** [zzzprojects/EntityFramework-Plus#516]
### Description

I faced the same problem as the guy in this issue: https://github.com/zzzprojects/EntityFramework-Plus/issues/341

But I'm not so lazy as not to make a minimal reproducible example :D

### Exception

Exception message:
``` 
MySql.Data.MySqlClient.MySqlException: 'Unknown column 'x.Bar' in 'field list''
```
Stack trace:
```
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 98
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__94.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 307
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__93.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 292
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.TextCommandExecutor.<ExecuteReaderAsync>d__1.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__61.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 276
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 77
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at ConsoleApp1.Program.Main(String[] args) in ConsoleApp1\ConsoleApp1\Program.cs:line 34
```

### Fiddle or Project

Example is really primitive:

```csharp
using System.Linq;
using System.Diagnostics;
using Z.EntityFramework.Plus;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1
{
    public class ApplicationContext : DbContext
    {
        public DbSet<Foo> Foos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySql(connectionString);
        }
    }

    public class Foo
    {
        public long Id { get; set; }
        public int Bar { get; set; }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            using (var context = new ApplicationContext())
            {
                context.Database.EnsureCreated();
                context.Foos.Add(new Foo { Id = 1, Bar = 1 });
                context.SaveChanges();

                int updated = context.Foos.Where(x => x.Id == 1).Update(x => new Foo { Bar = x.Bar + 1 }); // Exception here
                Debug.Assert(updated == 1);
                Debug.Assert(context.Foos.Find(1L).Bar == 2);
            }
        }
    }
}
```

### Further technical details
- EF version: `Microsoft.EntityFrameworkCore 2.2.6`
- EF Plus version: `Z.EntityFramework.Plus.EFCore 2.0.7`
- Database Provider: `Pomelo.EntityFrameworkCore.MySql 2.2.0`

**Comment by JonathanMagnan** [comment]
Thank you,

We will look at it and at your pull ;)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Kir-Antipov ,

Your pull has been merged.

If you still have an issue, let us know and we will re-open this request.

Best Regards,

Jonathan

**Comment by Kir-Antipov** [comment]
@JonathanMagnan, I'm currently using my compiled fork, so I know, that issue has gone)
Waiting for official update of the library :)

**Comment by JonathanMagnan** [comment]
Hello @Kir-Antipov ,

It has been already released during the weekend.

At this moment, this repo is not synchronized with our internal repo (We have some internal stuff at this moment we need to clean first)... that's why the released happened after the merge.

Best Regards,

Jonathan
