### ISSUE TITLE
IncludeFilter not working in specific situation

### ISSUE THREAD

**Issue by mhosman** [zzzprojects/EntityFramework-Plus#534]
Trying to use something like this (using EF Core 3.0):

`_context.CustomerLocations.IncludeFilter(c => c.Zones.Where(x => x.Polygon.Contains(c.Point)));`

I get:

`System.Exception: Oops! Select projection are not supported in EF+ Query IncludeFilter. For more information, contact us: info@zzzprojects.com
   at Z.EntityFramework.Plus.QueryIncludeFilterProvider`1.CreateQuery(Expression expression)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, ParsingConfig config, String predicate, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where[TSource](IQueryable`1 source, ParsingConfig config, String predicate, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where[TSource](IQueryable`1 source, String predicate, Object[] args)
   at CustomerApi.Controllers.Customer.CustomerLocationsController.GetLocations(Int32 page, Int32 limit, String filter, String order, Boolean expand, Boolean ignoreQueryFilters) in /Users/usr/Documents/GitHub/api/CustomerApi/Controllers/Customer/CustomerLocationsController.cs:line 61
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at CustomerApi.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in /Users/usr/Documents/GitHub/api/CustomerApi/Startup.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by mhosman** [comment]
Just worked without EF Plus:

`.Include(c => c.Zones.Select(x => x.Polygon.Contains(c.Point)));`

**Comment by JonathanMagnan** [comment]
Hello @mhosman ,

It looks you use LINQ Dynamic which makes a projection under the hood which is not compatible with our features.

Unfortunately, there is nothing we can do here as we are not compatible with projection ;(

However, it's possible for you to replace all your LINQ dynamic call by the [C# Eval Expression](https://entityframework-plus.net/linq-dynamic) library. The library is not free but you can replace all your dynamic call by a library that really evaluates and compile code at runtime.

Let me know if that answers correction to your issue.

Best Regards,

Jonathan

**Comment by mhosman** [comment]
Thanks Johnathan!
