### ISSUE TITLE
Query Include Filter (Load Multiple Levels) not working

### ISSUE THREAD

**Issue by stephen-atkinson-va** [zzzprojects/EntityFramework-Plus#537]
The online example throws an exception. https://entityframework-plus.net/online-examples/SK934m

Unhandled exception. System.InvalidOperationException: Processing of the LINQ expression '(source) => source' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessSelectMany(NavigationExpansionExpression source, LambdaExpression collectionSelector, LambdaExpression resultSelector)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at .(IQueryable , Action`1 , RelationalQueryContext& , Object& )
   at Z.EntityFramework.Extensions.EFPlusExtensions.EFPlusCreateCommand(IQueryable source, Action`1 action, RelationalQueryContext& queryContext, Object& compiledQuery)
   at Z.EntityFramework.Plus.BaseQueryFuture.CreateExecutorAndGetCommand(RelationalQueryContext& queryContext) in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\BaseQueryFuture.cs:line 447
   at Z.EntityFramework.Plus.QueryFutureBatch.CreateCommandCombined() in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureBatch.cs:line 317
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries() in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureBatch.cs:line 137
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.GetEnumerator() in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureEnumerable.cs:line 66
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Z.EntityFramework.Plus.QueryIncludeFilterParentQueryable`1.CreateEnumerable() in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryIncludeFilterCore.Shared\QueryIncludeFilterParentQueryable`.cs:line 153
   at Z.EntityFramework.Plus.QueryIncludeFilterParentQueryable`1.GetEnumerator() in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryIncludeFilterCore.Shared\QueryIncludeFilterParentQueryable`.cs:line 79
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main()
Command terminated by signal 6

**Comment by JonathanMagnan** [comment]
Look like something has been modified on EF Core 3.x,

Using `SelectMany` instead of `Select` make the query work again. So a `list of comments` is returned instead of a `list of list of comments`

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by stephen-atkinson-va** [comment]
Hi Jonathan,

All good :). Thanks for the quick response!

Cheers,
Stephen
