### ISSUE TITLE
DeleteAsync() fails with column b.Id does not exist

### ISSUE THREAD

**Issue by rpatrick00** [zzzprojects/EntityFramework-Plus#542]
### Description

I have a PostgreSQL table named case_fees with a composite primary key (tenant_name, case_id, and id).  I am doing a bulk reload of the fees for a case so I want to delete all existing rows in the underlying table where the tenant_name and case_id match (notice that I am not looking at the third element of the primary key, id, which the id of a fee).

Basically, I want to execute the following query:

DELETE FROM case_fees WHERE tenant_name = "sd_ca" AND case_id = "668"

My code looks like this:

int rowsAffected = await this.dbContext.Fees.AsQueryable().Where(f => f.TenantName == tenantName).Where(f => f.CaseId == unencryptedCaseId).DeleteAsync();

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
2019-10-19 16:21:00.404 -05:00 [Verbose] [PLADPLTRPATRICK] [0HLQKR8TO3L47:00000001] Deleting Fees for tenant sd_ca and case 668
2019-10-19 16:21:00.463 -05:00 [Debug] [PLADPLTRPATRICK] [0HLQKR8TO3L47:00000001] Compiling query model:
'from Fee f in DbSet<Fee>
where [f].TenantName == __tenantName_0
where [f].CaseId == __unencryptedCaseId_1
select new <>f__AnonymousType0{
    TenantName = [f].TenantName,
    CaseId = [f].CaseId,
    Id = [f].Id
}
'
2019-10-19 16:21:00.470 -05:00 [Debug] [PLADPLTRPATRICK] [0HLQKR8TO3L47:00000001] Optimized query model:
'from Fee f in DbSet<Fee>
where [f].TenantName == __tenantName_0
where [f].CaseId == __unencryptedCaseId_1
select new <>f__AnonymousType0{
    TenantName = [f].TenantName,
    CaseId = [f].CaseId,
    Id = [f].Id
}
'
2019-10-19 16:21:00.501 -05:00 [Debug] [PLADPLTRPATRICK] [0HLQKR8TO3L47:00000001] (QueryContext queryContext) => IEnumerable<<>f__AnonymousType0> _InterceptExceptions(
|__ source: IEnumerable<<>f__AnonymousType0> _ShapedQuery(
|   |__ queryContext: queryContext,
|   |__ shaperCommandContext: SelectExpression:
|   |       SELECT f.tenant_name AS "TenantName", f.case_id AS "CaseId", f.id
|   |       FROM case_fees AS f
|   |       WHERE (f.tenant_name = @__tenantName_0) AND (f.case_id = @__unencryptedCaseId_1),
|   |__ shaper: (QueryContext queryContext | ValueBuffer f) => new <>f__AnonymousType0{
|           TenantName = string TryReadValue(f, 0, Fee.TenantName),
|           CaseId = string TryReadValue(f, 1, Fee.CaseId),
|           Id = string TryReadValue(f, 2, Fee.Id)
|       }
|__ ),
|__ contextType: data_sync_service.Server.ApplicationDbContext,
|__ logger: DiagnosticsLogger<Query>,
|__ queryContext: Unhandled parameter: queryContext)

...

2019-10-19 16:21:00.654 -05:00 [Error] [PLADPLTRPATRICK] [0HLQKR8TO3L47:00000001] Loading cases file failed: SaveCaseFeesToDatabase() for tenant sd_ca failed to save 101 case fees for case 668: SaveFees() failed to store fees for tenant sd_ca and case ID 668: 42703: column b.Id does not exist
data_sync_service.Server.Exceptions.CasesStoreRepositoryException: SaveCaseFeesToDatabase() for tenant sd_ca failed to save 101 case fees for case 668: SaveFees() failed to store fees for tenant sd_ca and case ID 668: 42703: column b.Id does not exist ---> data_sync_service.Server.Exceptions.DatabaseRepositoryException: SaveFees() failed to store fees for tenant sd_ca and case ID 668: 42703: column b.Id does not exist ---> Npgsql.PostgresException: 42703: column b.Id does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 444
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 332
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1218
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query) in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.BatchDelete.Shared\BatchDelete.cs:line 378
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at data_sync_service.Server.Repositories.DatabaseRepository.SaveFees(String tenantName, String unencryptedCaseId, List`1 fees) in d:\src\cap\data-sync-service\data-sync-service\Server\Repositories\DatabaseRepository.cs:line 53
   --- End of inner exception stack trace ---
   at data_sync_service.Server.Repositories.DatabaseRepository.SaveFees(String tenantName, String unencryptedCaseId, List`1 fees) in d:\src\cap\data-sync-service\data-sync-service\Server\Repositories\DatabaseRepository.cs:line 69
   at data_sync_service.Server.Repositories.CasesStoreRepository.SaveCaseFeesToDatabase(String tenantName, List`1 caseFeeWrappers) in d:\src\cap\data-sync-service\data-sync-service\Server\Repositories\CasesStoreRepository.cs:line 127
   --- End of inner exception stack trace ---
   at data_sync_service.Server.Repositories.CasesStoreRepository.SaveCaseFeesToDatabase(String tenantName, List`1 caseFeeWrappers) in d:\src\cap\data-sync-service\data-sync-service\Server\Repositories\CasesStoreRepository.cs:line 140
   at data_sync_service.Server.Repositories.CasesStoreRepository.StoreCases(String tenantName, List`1 cases) in d:\src\cap\data-sync-service\data-sync-service\Server\Repositories\CasesStoreRepository.cs:line 48
   at data_sync_service.Server.Controllers.api.CaseDataSyncController.LoadFile(CaseDataLoadRequest payload) in d:\src\cap\data-sync-service\data-sync-service\Server\Controllers\api\CaseDataSyncController.cs:line 72
```

### Further technical details
- EF version:  2.2.4
- EF Plus version:  2.0.8
- Database Provider:  PostgreSQL 11.5-R1

It seems like the problem has to do with the generated query trying to use the Id field when that should not be required for this delete query....

**Comment by JonathanMagnan** [comment]
Hello @rpatrick00 ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
