### ISSUE TITLE
DateTime to DateTimeOffset conversion error

### ISSUE THREAD

**Issue by john-32767** [zzzprojects/EntityFramework-Plus#543]
### Description
Error when using FutureValue (DeferredLongCount) along with entity list query Future()

### Exception
```
Exception message:
System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.

Stack trace:
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in C:\projects\npgsql-entityframeworkcore-postgresql\src\EFCore.PG\Storage\Internal\NpgsqlExecutionStrategy.cs:line 28
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.SetResult(IEnumerator`1 enumerator) in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureEnumerable.cs:line 178
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.SetResult(DbDataReader reader) in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureEnumerable.cs:line 171
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries() in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureBatch.cs:line 177
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.GetEnumerator() in C:\Repos\ZZZ\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureEnumerable.cs:line 66
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

```

### Fiddle or Project
```csharp
  var projectFutures = Context.Projects.Future();
  var countFuture = Context.Projects.DeferredLongCount().FutureValue();
 
  var projects = projectFutures.ToList(); //error here
  var totalRecords = countFuture.Value;
```

### Further technical details
- The table Projects has DateTimeOffset columns;
- If countFuture is removed (or used in the default manner), everything works out;
- EF version: Microsoft.EntityFrameworkCore (2.2.4)
- EF Plus version: Z.EntityFramework.Plus.EFCore (2.0.16)
- Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL (2.2.4)

**Comment by JonathanMagnan** [comment]
Hello @john-32767 n,

Do you think you could provide a **runnable project** sample with this issue?

It will help my developer investigate the issue more efficiently.

_We cannot count the number of time an issue were looking easy to reproduce like this one but we lost time and something important was missing to be mentioned. So we now always ask for a runnable scenario._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by john-32767** [comment]
Hi @JonathanMagnan,

I've created a console demo project ([DatetimeOffsetError.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3777955/DatetimeOffsetError.zip)).
Below is also a screenshot of the issue.
Also the Postgres instance I've used 11.2 (PostgreSQL 11.2 on x86_64-pc-mingw64, compiled by gcc.exe (Rev5, Built by MSYS2 project) 4.9.2, 64-bit)

![2019-10-28_11-16-59](https://user-images.githubusercontent.com/31926443/67666697-fe54be80-f974-11e9-9422-bbce1001093d.jpg)

**Comment by JonathanMagnan** [comment]
Hello @john-32767 ,

Just to let you know we looked at it again this weekend.

Hopefully, we hope to have found a fix this time. We will continue to investigate on Monday and test our fix but so far, everything looks good.

**Comment by john-32767** [comment]
That's good news @JonathanMagnan, thanks!

**Comment by JonathanMagnan** [comment]
Our pleasure!

We will get back to you as soon as we test it!

**Comment by JonathanMagnan** [comment]
Hello @john-32767 ,

The v2.0.26 has been released.

Could you try it and confirm for us that the issue has been fixed?

**Comment by john-32767** [comment]
Hi @JonathanMagnan,

It is working as expected.
Tested with the following versions (.net core based counterpart packages):

![image](https://user-images.githubusercontent.com/31926443/68239380-8725c700-0013-11ea-9db3-4ba31e0dce60.png)

Thanks!
