### ISSUE TITLE
.Delete() and .DeleteAsync() extensions throw exception in EF Core 3.1 preview 3

### ISSUE THREAD

**Issue by shaulbehr** [zzzprojects/EntityFramework-Plus#548]
### Description
.Delete() and .DeleteAsync() extensions throw exception in EF Core 3.1 preview 3

### Steps to reproduce:
Very easy. With any DbContext, and any DbSet:
```
await using var db = new MyDbContext();
await db.Things.DeleteAsync();
```
Exception:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at .(IQueryable , RelationalQueryContext& )
   at Z.EntityFramework.Plus.BatchDelete.CreateCommand(IQueryable query, IEntityType entity)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.<>c__DisplayClass2_0`1.<DeleteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Further technical details
- EF version: 3.1.0-preview3.19554.8
- EF Plus version: 3.0.22
- Database Provider: npgsql

**Comment by JonathanMagnan** [comment]
Hello @shaulbehr ,

Thank you for reporting, we are already on this issue with the latest preview ;)

I will keep you updated but I believe we are very close to having it fixed.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @shaulbehr ,

The v3.0.23 has been released.

Could you try it and confirm that everything is now working as expected with the latest preview version?

**Comment by shaulbehr** [comment]
You are awesome. Fixed, thank you!
