### ISSUE TITLE
When using a nullable DateTime property with a ValueConverter assigned to it and assigning a null value, UpdateFromQuery fails with the error "Object must implement IConvertible".

### ISSUE THREAD

**Issue by SimonLuckenuik** [zzzprojects/EntityFramework-Plus#555]
### Description
When using a nullable DateTime property with a ValueConverter assigned to it and assigning a null value, UpdateFromQuery fails with the error "Object must implement IConvertible". Without the value converter, everything works correctly. The value converter is working correctly when using entity framework only. The goal of the converter is to make sure that only UTC DateTime values are stored and read from the database.

Thanks!

```csharp
using System;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;

namespace BatchUpdateRepro
{
    class Program
    {
        [Obsolete]
        static void Main(string[] args)
        {
            var connectionString = "{your_connection_string}";
            var options = new DbContextOptionsBuilder<ExampleDbContext>()
                .UseLoggerFactory(new LoggerFactory(new[] {
                    new ConsoleLoggerProvider((_, level) => level >= Microsoft.Extensions.Logging.LogLevel.Debug, true)
                }))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors()
                .UseNpgsql(connectionString, b => b.EnableRetryOnFailure())
                .Options;

            var rnd = new Random();
            
            // adding new entities: success
            using (var dbContext = new ExampleDbContext(options))
            {
                
                var examples = new[]
                {
                    new Example { Id = rnd.Next(), DateTime = DateTime.Now, NullableDateTime = null},
                    new Example { Id = rnd.Next(), DateTime = DateTime.Now, NullableDateTime = null},
                    new Example { Id = rnd.Next(), DateTime = DateTime.Now, NullableDateTime = null},
                    new Example { Id = rnd.Next(), DateTime = DateTime.Now, NullableDateTime = DateTime.Now},
                    new Example { Id = rnd.Next(), DateTime = DateTime.Now, NullableDateTime = DateTime.Now},
                    new Example { Id = rnd.Next(), DateTime = DateTime.Now, NullableDateTime = DateTime.Now }
                };

                dbContext.Examples.AddRange(examples);
                dbContext.SaveChanges();
            }

            // loading entity and updating it: success
            using (var dbContext = new ExampleDbContext(options))
            {
                var example1 = dbContext.Examples.Last();
                example1.DateTime = DateTime.Now;
                example1.NullableDateTime = null;

                var example2 = dbContext.Examples.First();
                example2.DateTime = DateTime.Now;
                example2.NullableDateTime = DateTime.Now;

                dbContext.SaveChanges();
            }


            // bulk updating entities: error
            using (var dbContext = new ExampleDbContext(options))
            {
                // Updating to non-null value : Works
                dbContext.Examples.Where(e => e.Id > 0).UpdateFromQuery(e => new Example { DateTime = DateTime.Now, NullableDateTime = DateTime.Now });

                //  System.InvalidCastException
                //      HResult=0x80004002
                //  Message=Object must implement IConvertible.
                //      Source=System.Private.CoreLib
                //  StackTrace:
                //  at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
                //  at System.Convert.ChangeType(Object value, Type conversionType)
                //  at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
                //  at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
                //  at Z.EntityFramework.Extensions.BatchUpdate.`1.(Object )
                //  at Z.EntityFramework.Extensions.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, IEntityType entity, Dictionary`2 convertToProviderDict)
                //  at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
                //  at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory)
                //  at BatchUpdateRepro.Program.Main(String[] args) in d:\temp\UpdateNotWorkingForNull\UpdateNotWorkingForNull\Program.cs:line 63

                dbContext.Examples.Where(e => e.Id > 0).UpdateFromQuery(e => new Example { DateTime = DateTime.Now,  NullableDateTime = default(DateTime?) });
            }
        }
    }

    public class UtcNullableDateTimeValueConverter : ValueConverter<DateTime?, DateTime?>
    {
        public UtcNullableDateTimeValueConverter()
            : base(
                v => v.HasValue ? v.Value.ToUniversalTime() : v, 
                v => v.HasValue ? DateTime.SpecifyKind(v.Value, DateTimeKind.Utc) : v, 
                null)
        {
        }
    }

    public class UtcDateTimeValueConverter : ValueConverter<DateTime, DateTime>
    {
        public UtcDateTimeValueConverter()
            : base(
                v => v.ToUniversalTime(), 
                v =>DateTime.SpecifyKind(v, DateTimeKind.Utc), 
                null)
        {
        }
    }


    public class ExampleDbContext : DbContext
    {
        private readonly ValueConverter<string, Guid> _guidConverter = new ValueConverter<string, Guid>(v => new Guid(v), v => v.ToString("N").ToUpperInvariant());
        public DbSet<Example> Examples { get; set; }

        public ExampleDbContext(DbContextOptions<ExampleDbContext> options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.HasDefaultSchema("efplus");

            var model = builder.Entity<Example>();
            model.ToTable("exampleconvert");
            model.HasKey(e => e.Id);
            model.Property(e => e.Id).HasColumnName("id");
            model.Property(e => e.NullableDateTime).HasColumnName("datetime_null").HasConversion(new UtcNullableDateTimeValueConverter());
            model.Property(e => e.DateTime).HasColumnName("datetime_not_null").HasConversion(new UtcDateTimeValueConverter());
        }
    }

    public class Example
    {
        public int Id { get; set; }
        public DateTime? NullableDateTime { get; set; }
        public DateTime DateTime { get; set; }
    }
}
```

Database Table:
```sql
            create schema efplus
            create table efplus.exampleconvert
            (
                id int not null primary key,
                datetime_null TIMESTAMP null,
                datetime_not_null TIMESTAMP not null
            )
```

### Exception

```csharp
                System.InvalidCastException
                    HResult = 0x80004002
                  Message = Object must implement IConvertible.
                        Source = System.Private.CoreLib
                  StackTrace:
                at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
                  at System.Convert.ChangeType(Object value, Type conversionType)
                  at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
                  at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<> c__DisplayClass3_0`2.< SanitizeConverter > b__0(Object v)
                  at Z.EntityFramework.Extensions.BatchUpdate.`1.(Object )
                  at Z.EntityFramework.Extensions.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, IEntityType entity, Dictionary`2 convertToProviderDict)
                  at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
                  at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory)
                  at BatchUpdateRepro.Program.Main(String[] args) in d:\temp\UpdateNotWorkingForNull\UpdateNotWorkingForNull\Program.cs:line 63
```

### Fiddle or Project
[UpdateNotWorkingForNull.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3933054/UpdateNotWorkingForNull.zip)

### Further technical details
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.2.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.2.4" />
    <PackageReference Include="Z.EntityFramework.Extensions.EFCore" Version="2.7.22" />

**Comment by SimonLuckenuik** [comment]
Was raised in wrong repo: 
Ref: https://github.com/zzzprojects/EntityFramework-Extensions/issues/308
