### ISSUE TITLE
Batch update does not work for keyless tables

### ISSUE THREAD

**Issue by joshfriend** [zzzprojects/EntityFramework-Plus#557]
### Description
Attempting to call `.Update()` on a query for a table with `.HasNoKey()` set on its model builder throws an exception [here](https://github.com/zzzprojects/EntityFramework-Plus/blob/4182a3930724088cd2262a84d1f9ec93d595343a/src/shared/Z.EF.Plus.BatchUpdate.Shared/BatchUpdate.cs#L836).

I have a keyless table for holding app config values that has only one row. I would like to run a statement like:

```sql
UPDATE "Configuration" SET "SomeConfigValue" = 123;
```

I've tried several variations of EF queries:

```csharp
await _context.Configuration
  .UpdateAsync(c => new Configuration { SomeConfigValue = 9999 });
await _context.Configuration.Where(x => true)
  .UpdateAsync(c => new Configuration { SomeConfigValue = 9999 });
```

### Exception
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Z.EntityFramework.Plus.BatchUpdate.CreateCommand(IQueryable query, IEntityType entity, List`1 values)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.<>c__DisplayClass2_0`1.<UpdateAsync>b__0()
```

### Further technical details
- EF version: 3.1
- EF Plus version: 3.0.24
- Database Provider: Postgres

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

We are supposed to review this feature this month, so we will certainly look at it very soon.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by MirandaDotNet** [comment]
Hi, Jonathan,
It seems that something else got broken - Update doesn't work at all - no props are updated.
From my test project:

```
 [Fact]
        public void TestInMemoryBatchUpdate()
        {
            //this is fine - for straightforward update for entities that don''t have navigation props
            _context.Addresses.AsQueryable().Update(x => new Address { AddressLine = "dummy" });

            Assert.True(_context.Addresses.ToList().All(x => x.AddressLine == "dummy"));
        }
```

This fails.

Also note that comparing to my initial version of test proj, I had to call **ToList()**. It seems that after 
 __context.Addresses.AsQueryable().Update(_  something is off with context entities, because regular All (__context.Addresses.All(x => x.AddressLine == "dummy")_) would return true.
