### ISSUE TITLE
Exception: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')

### ISSUE THREAD

**Issue by XardasLord** [zzzprojects/EntityFramework-Plus#559]
### Description
We are using Audit logs from your framework. We have audit log configuration in our EfDbContext constructor like this:
```
public EfDbContext(DbContextOptions options, IUserInfoProvider userInfoProvider) : base(options)
{
	_userInfoProvider = userInfoProvider;
	_enableAuditLogs = enableAuditLogs;

        ConfigureAuditLogs();
}

private static void ConfigureAuditLogs()
{
	AuditManager.DefaultConfiguration.UseUtcDateTime = true;
			
	AuditManager.DefaultConfiguration.IgnoreEntityAdded = true;
	AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
			
	AuditManager.DefaultConfiguration.ExcludeProperty();
	AuditManager.DefaultConfiguration.Exclude(x => true);

	AuditManager.DefaultConfiguration.Include<Farmer>();
	AuditManager.DefaultConfiguration.IncludeProperty<Farmer>(x => new
		{x.Id, x.PhoneNumber});

	AuditManager.DefaultConfiguration.Include<MarketSplitPercentage>();
	AuditManager.DefaultConfiguration.IncludeProperty<MarketSplitPercentage>(x => new
		{x.Id, x.FarmerId, x.MarketId, x.SplitPercentage});

	AuditManager.DefaultConfiguration.Include<Market>();
	AuditManager.DefaultConfiguration.IncludeProperty<Market>(x => new
		{x.Id, x.PaymentAmount, x.PaymentType, x.Split});

	AuditManager.DefaultConfiguration.Include<Merchant>();
	AuditManager.DefaultConfiguration.IncludeProperty<Merchant>(x => new
		{x.Id, x.AgriwalletFee, x.MpesaFee, x.ManagerNumber});

	AuditManager.DefaultConfiguration.Include<Wallet>();
	AuditManager.DefaultConfiguration.IncludeProperty<Wallet>(x => new
		{x.Id, x.DebtLimit, x.Active, x.PhoneNumber, x.IsDeleted, x.WithdrawalsEnabled});

	AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
	{
		(context as EfDbContext)?.AuditEntries.AddRange(audit.Entries);
	};
}
```

And then we have overriden the SaveChangesAsync method like in your documentation:
```
public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
{
	var audit = new Audit();
	audit.CreatedBy = _userInfoProvider?.UserName;
	audit.PreSaveChanges(this);

	var rowsAffected = await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
			audit.PostSaveChanges();

	if (audit.Configuration.AutoSavePreAction != null)
	{
		audit.Configuration.AutoSavePreAction(this, audit);
		await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
	}

	return rowsAffected;
}
```

The execption which I provided below is throwing totally random. Mostly it is successfull but sometimes it throws the exception below. What can cause this problem? The problem seems to be connected with your audit mechanism.

### Exception
```
Exception message: System.ArgumentException : Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
Stack trace: 
System.ArgumentException : Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Z.EntityFramework.Plus.AuditConfiguration.Clone()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AgriWallet.Repository.Context.EfDbContext.SaveChangesAsync(CancellationToken cancellationToken) in E:\localRepositories\agriwallet.server\src\AgriWallet.Repository\Context\EfDbContext.cs:line 128
   at AgriWallet.Repository.UnitOfWork.CommitAsync() in E:\localRepositories\agriwallet.server\src\AgriWallet.Repository\UnitOfWork.cs:line 133
   at AgriWallet.Services.FarmerService.AddFarmerWithoutValidationAsync(FarmerCreateDto farmerCreateDto, Boolean approvalNeeded, Nullable`1 merchantId) in E:\localRepositories\agriwallet.server\src\AgriWallet.Services\Services\FarmerService.cs:line 86
   at AgriWallet.Services.FarmerService.AddFarmerAsync(FarmerCreateDto farmerCreateDto, Boolean approvalNeeded, Nullable`1 merchantId) in E:\localRepositories\agriwallet.server\src\AgriWallet.Services\Services\FarmerService.cs:line 130
```

### Further technical details
- .NET Core version: 3.1
- EF version: 3.1.0
- EF Plus version: 3.0.31
- Database Provider: PostreSQL (Npgsql.EntityFramerowkCore.PostgreSQL v3.1.0)

**Comment by JonathanMagnan** [comment]
Hello @XardasLord ,

I might be wrong (I don't have the full code) but I believe the method `ConfigureAuditLogs` is called multiple times.

Every time you create a context `EfDbContext`, you also automatically call the `ConfigureAuditLogs`. Which mean, you configure the `Auditing` multiple time which may lead to some concurrency issue exactly like this one.

I recommend you to move the call of the audit configuration in a static constructor (called only once) like this:

```csharp
public static EfDbContext()
{
	ConfigureAuditLogs();
}
```

You can also move it to any other method called only once. The point here is not configuring our auditing multiple time to avoid concurrency error.

Let me know if that makes sense.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by XardasLord** [comment]
@JonathanMagnan Thank you for your fast respond,

It seems to me that it was the problem as you said. I moved the configuration to the static constructor of my context and now it doesn't throw an exception on our test environment.
We will introduce this fix on our production environment after the Christmas and after New Year, because we don't want to do this in this period of time.

Thank you so much! :)

**Comment by JonathanMagnan** [comment]
Awesome ;)

Have a great Christmas holiday.

Best Regards,

Jon
