### ISSUE TITLE
Error when working with relationships defined on OnModelCreating of Context

### ISSUE THREAD

**Issue by jardg** [zzzprojects/EntityFramework-Plus#567]
### Description
Hi I'm having problems when working with relationships and the  Z.EntityFramework.Plus.EFCore library. I have three entities. One entity receipt which key is composed by { f.Serial, f.InvoiceId, f.Date }, another Payment with key { f.InvoiceSerial, f.InvoiceId, f.InvoiceDate, f.ReceiptNumber } and the last one Serie with key Id. So Receipt entity includes the rest of entities as properties using virtual and configuring the relationships as the following(I skip the mappings of Payment and Serie but I can provide if needed):

```
 {
                var typeBuilder = modelBuilder.Entity<Receipt>();
                typeBuilder.HasKey(f => new { f.InvoiceSerial, f.InvoiceId, f.InvoiceDate, f.ReceiptNumber });

                typeBuilder.HasOne(p => p.Payment)
                            .WithMany()
                            .HasForeignKey(p => new { p.InvoiceId, p.InvoiceSerial, p.InvoiceDate, p.UnpaidReceiptNumber })
                            .HasPrincipalKey(k => new { k.InvoiceId, k.InvoiceSerial, k.InvoiceDate, k.ReceiptNumber });

                typeBuilder.HasOne(p => p.Serie)
                         .WithOne()
                         .HasForeignKey<Serie>(k => k.Word)
                         .HasPrincipalKey<Receipt>(p => p.InvoiceSerial);
 }
```
My problem is that when I use the Z.EntityFramework.Plus.EFCore library when I delete for example the receipt with InvoiceSerial  "A15" and InvoiceId 5 all the receipts with that InvoiceSerial get deleted aswell.  Similar behaviour happens when I retrieve all receipts and then I create a new receipt with InvoiceSerial "A15" and unique invoiceId and receiptNumber. In this case I get "another instance with the same key value for {'InvoiceSerial'} is already being tracked". The problem dissapears when I delete the relationships defined on the mappings. Seems like when I define the relationships the entity asumes that  the new key for Receipt is invoiceSerial instead of the one defined at the begining.

### Exception

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The instance of entity type 'Receipt' cannot be tracked because another instance with the same key value for {'InvoiceSerial'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at ConsoleApp1.Program.Main(String[] args) in C:\Proyectos\PruebaEFKeys\ConsoleApp1\ConsoleApp1\Program.cs:line 29

```

Is there a way of working with relationships like in the example or is something that needs fix? Thanks in advance for the help!. I can provide a Fiddle or a project if needed. 
### Further technical details
- EF version: 3.1.0
- EF Plus version: 3.0.32
- Database Provider: SQL Server using package Microsoft.EntityFrameworkCore.SqlServer (3.1.0)

**Comment by JonathanMagnan** [comment]
Hello @jardg,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by jardg** [comment]
I just e-mailed a sample project to that address. Thanks a lot for the attention.

**Comment by JonathanMagnan** [comment]
Awesome Jardg! 

I received it and gave it to my developer. 

We will get back to you soon :)

**Comment by jardg** [comment]
Finally looked like the error was related with how it was configured our EF Core mappings and the database configuration. When removing the package looked like the problem disappeared and I thought it was related with the library.
I close the issue. Thanks a lot for the great support!
