### ISSUE TITLE
Include filters not working

### ISSUE THREAD

**Issue by FilipFilipov** [zzzprojects/EntityFramework-Plus#57]
I just found this library and it seems very promising, but I can't get the Include filters to work. The following code for example

```csharp
Snippet test;
using (var context = new SnippyDbContext())
{
    test = context.Snippets
        .IncludeFilter(s => s.Comments.Where(c => c.Id == 3))
        .FirstOrDefault(s => s.Id == 1);
}
var num = test.Comments.Count;
```
throws an ObjectDisposedException or gets all of the Comments if IncludeOptimized is used instead.

Looking at the database log I can tell that it's generating and sending the correct sql, but the context doesn't seem to be registering the comments as loaded and initiates its lazy loading right after, pulling all the comments for that snippet. So what am I doing wrong?

**Comment by zzzprojects** [comment]
Thank you for reporting,

We didn't success to reproduce the ObjectDisposedException error. However, we get the same behavior as you.

When using with Lazy Loading, the SQL generated is good but the proxy class still retrieve all related comments as soon as we access the properties.

We will check more about the issue this weekend.

**Comment by babin93** [comment]
Hi
I also encountered this issue. Do you know if there is any version of the library I could use temporarly that doesn't have this issue ?

**Comment by zzzprojects** [comment]
Hello @babin93 ,

Unfortunately no, I don't think any version have ever worked with Lazy Loading.

**Comment by zzzprojects** [comment]
Hello,

We did some progression on this issue. We believe we successfully make it work with Lazy Loading.

 We must still make some test and refactoring since the code for this feature is starting to become very complicated to support.

We will keep you updated with our progression.

**Comment by FilipFilipov** [comment]
Thank you for your hard work.

**Comment by zzzprojects** [comment]
Hello @FilipFilipov ,

The v1.4.10 is now available.

IncludeFilter && IncludeOptimized should now work with Lazy loading.

Let me know if the issue has been corrected.

Best Regards,

Jonathan

**Comment by FilipFilipov** [comment]
Well, you're half-right - for the particular query I was testing IncludeFilter now works, but IncludeOptimized doesn't. The scenario is, I have a table DashboardPerUsers, where every record points to one User and one Dashboard, but also has an Index, so it counts as its own entity. I want to get a User's non-deleted Dashboards with their non-deleted Widgets, so I do this...

```
var userDashboards = db.DashboardPerUsers
  .Where(dpu => dpu.Userid == userId && !dpu.Dashboard.IsDeleted)
  .OrderBy(dpu => dpu.Index)
  .ThenBy(dpu => dpu.Dashboard.Name)
  .ThenBy(dpu => dpu.Dashboard.TabIndex)
  .Select(dpu => dpu.Dashboard)
  .IncludeOptimized(d => d.Widgets.Where(w => !w.IsDeleted));
```

... and when I materialize it, I get this.

```
System.ArgumentException : Expression of type 'System.Data.Entity.Core.Objects.ObjectQuery`1[MarketingDb.Domain.EntityFramework.Model.Entities.DashboardPerUser]' cannot be used for parameter of type 'System.Linq.IQueryable`1[MarketingDb.Domain.EntityFramework.Model.Entities.Dashboard]' of method 'System.Linq.IOrderedQueryable`1[MarketingDb.Domain.EntityFramework.Model.Entities.Dashboard] OrderBy[Dashboard,Guid](System.Linq.IQueryable`1[MarketingDb.Domain.EntityFramework.Model.Entities.Dashboard], System.Linq.Expressions.Expression`1[System.Func`2[MarketingDb.Domain.EntityFramework.Model.Entities.Dashboard,System.Guid]])'
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Z.EntityFramework.Plus.QueryAddOrAppendOrderExpressionVisitor`1.AddOrAppendOrderBy(Expression expression, String propertyName, Boolean useOrderBy)
   at Z.EntityFramework.Plus.QueryAddOrAppendOrderExpressionVisitor`1.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Z.EntityFramework.Plus.QueryAddOrAppendOrderExpressionVisitor`1.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Z.EntityFramework.Plus.QueryAddOrAppendOrderExpressionVisitor`1.VisitMethodCall(MethodCallExpression node)
   at Z.EntityFramework.Plus.QueryAddOrAppendOrderExpressionVisitor`1.AddOrAppendOrderBy(IQueryable`1 query, String[] keyNames, Boolean ascending, Object comparer)
   at Z.EntityFramework.Plus.QueryAddOrAppendOrderExtensions.AddToRootOrAppendOrderBy[T](IQueryable`1 query, String[] columns)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.CreateEnumerable()
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
```

It doesn't seem to make a difference whether it has an OrderBy clause or not either.

**Comment by FilipFilipov** [comment]
The new version also seems to have quite a performance regression. I've been using the Update and Delete methods a lot as part of my database integration tests and after updating to v1.4.10 today their execution time nearly doubled.

**Comment by zzzprojects** [comment]
Hello @FilipFilipov ,

Thank you, I will check both issues today.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @FilipFilipov ,

For the first issue, it caused because of the Select.

We try to add or append the order by to the existing order by or the root when the select result should be used instead.

Now, when a "Select" or "SelectMany" method is found, we use the latest one to add the OrderBy

```csharp
if (node.Method.Name == "MergeAs" || node.Method.Name == "Select" || node.Method.Name == "SelectMany")
{
	// ADD "OrderBy" | "ThenBy" to the query
	for (var i = 0; i < KeyNames.Length; i++)
	{
		expression = AddOrAppendOrderBy(expression, KeyNames[i], i == 0);
	}
}
else
{
	expression = base.VisitMethodCall(node);
}
```

We are currently doing some additional test to make sure everything is fine. A new version should be available very soon.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @FilipFilipov ,

The v1.4.11 is now available
https://www.nuget.org/packages/Z.EntityFramework.Plus.EF6/

Let me know if this issue is fixed.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
About the performance issue for Update and Delete,

I have not started to look at it, but I have a strong hypothesis.

Does your project use the EF+ Query Filter feature? We did a major change which could impact the performance of all queries. I will give you more detail if this is the case.

**Comment by FilipFilipov** [comment]
I can confirm that IncludeOptimized works with v1.4.11. Thanks for patching it so quickly. By the way, is there any case where you'd want to use IncludeFilter over IncludeOptimized?

You are also right about the Query Filter. In fact, I had one for the Dashboards and the Widgets to remove the deleted ones, that I completely forgot about.

Interestingly, this allows me to rewrite my above query without the ```.Where(w => !w.IsDeleted)``` check, but not without the ``` && !dpu.Dashboard.IsDeleted``` check. What parts of a query do these filters cover exactly?

**Comment by FilipFilipov** [comment]
Another thing I just noticed - any multi-level Include (both flavors) with a Select in it seems to return an empty set.

**Comment by FilipFilipov** [comment]
Okay, I may have spoken too soon. There's some inconsistent behavior where the query with IncludeOptimized will sometimes not sort the results correctly. Or possibly never sorts them correctly, it's hard to tell because there are only two objects expected in this test, so there a 50% chance they will be sorted even without an OrderBy.

Anyway, here's the query again:
```
var userDashboards = db.DashboardPerUsers
  .Where(dpu => dpu.Userid == userId && !dpu.Dashboard.IsDeleted)
  .OrderBy(dpu => dpu.Index)
  .ThenBy(dpu => dpu.Dashboard.Name)
  .ThenBy(dpu => dpu.Dashboard.TabIndex)
  .Select(dpu => dpu.Dashboard)
  .IncludeOptimized(d => d.Widgets)
  .ToList();
```

The generated sql doesn't seem to change between successful or failed test runs, but just in case here it is:
```
-- EF+ Query Future: 1 of 2
SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[Userid] AS [Userid], 
    [Project1].[DashboardId] AS [DashboardId], 
    [Project1].[C1] AS [C1], 
    [Project1].[Id1] AS [Id1], 
    [Project1].[Name] AS [Name], 
    [Project1].[Query] AS [Query], 
    [Project1].[Transpose] AS [Transpose], 
    [Project1].[X] AS [X], 
    [Project1].[Y] AS [Y], 
    [Project1].[Cache] AS [Cache], 
    [Project1].[CacheExpires] AS [CacheExpires], 
    [Project1].[CacheLifetime] AS [CacheLifetime], 
    [Project1].[DashboardId1] AS [DashboardId1], 
    [Project1].[PaletteId] AS [PaletteId], 
    [Project1].[Created] AS [Created], 
    [Project1].[Modified] AS [Modified], 
    [Project1].[IsDeleted] AS [IsDeleted], 
    [Project1].[Colspan] AS [Colspan], 
    [Project1].[Rowspan] AS [Rowspan], 
    [Project1].[Type] AS [Type], 
    [Project1].[Configuration] AS [Configuration], 
    [Project1].[KendoUiConfiguration] AS [KendoUiConfiguration], 
    [Project1].[IsReadOnly] AS [IsReadOnly], 
    [Project1].[Tooltip] AS [Tooltip], 
    [Project1].[WidgetBackgroundId] AS [WidgetBackgroundId], 
    [Project1].[IsCustomQuery] AS [IsCustomQuery]
    FROM ( SELECT 
        [Extent1].[DashboardId] AS [DashboardId], 
        [Extent1].[Userid] AS [Userid], 
        [Extent2].[Id] AS [Id], 
        [Extent3].[Id] AS [Id1], 
        [Extent3].[Name] AS [Name], 
        [Extent3].[Query] AS [Query], 
        [Extent3].[Transpose] AS [Transpose], 
        [Extent3].[X] AS [X], 
        [Extent3].[Y] AS [Y], 
        [Extent3].[Cache] AS [Cache], 
        [Extent3].[CacheExpires] AS [CacheExpires], 
        [Extent3].[CacheLifetime] AS [CacheLifetime], 
        [Extent3].[DashboardId] AS [DashboardId1], 
        [Extent3].[PaletteId] AS [PaletteId], 
        [Extent3].[Created] AS [Created], 
        [Extent3].[Modified] AS [Modified], 
        [Extent3].[IsDeleted] AS [IsDeleted], 
        [Extent3].[Colspan] AS [Colspan], 
        [Extent3].[Rowspan] AS [Rowspan], 
        [Extent3].[Type] AS [Type], 
        [Extent3].[Configuration] AS [Configuration], 
        [Extent3].[KendoUiConfiguration] AS [KendoUiConfiguration], 
        [Extent3].[IsReadOnly] AS [IsReadOnly], 
        [Extent3].[Tooltip] AS [Tooltip], 
        [Extent3].[WidgetBackgroundId] AS [WidgetBackgroundId], 
        [Extent3].[IsCustomQuery] AS [IsCustomQuery], 
        CASE WHEN ([Extent3].[X] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM   [dbo].[DashboardPerUser] AS [Extent1]
        INNER JOIN [dbo].[Dashboards] AS [Extent2] ON [Extent1].[DashboardId] = [Extent2].[Id]
        LEFT OUTER JOIN [dbo].[Widgets] AS [Extent3] ON ([Extent2].[Id] = [Extent3].[DashboardId]) AND ([Extent3].[IsDeleted] <> 1) AND ([Extent3].[IsDeleted] <> 1)
        WHERE ([Extent2].[IsDeleted] <> 1) AND ([Extent1].[Userid] = @Z_1_p__linq__0)
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC, [Project1].[Userid] ASC, [Project1].[DashboardId] ASC, [Project1].[C1] ASC
;

-- EF+ Query Future: 2 of 2
SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[Name] AS [Name], 
    [Project1].[TabIndex] AS [TabIndex], 
    [Project1].[IsPreset] AS [IsPreset], 
    [Project1].[IsInheritable] AS [IsInheritable], 
    [Project1].[Created] AS [Created], 
    [Project1].[Modified] AS [Modified], 
    [Project1].[IsDeleted] AS [IsDeleted]
    FROM ( SELECT 
        [Extent2].[Id] AS [Id], 
        [Extent2].[Name] AS [Name], 
        [Extent2].[TabIndex] AS [TabIndex], 
        [Extent2].[IsPreset] AS [IsPreset], 
        [Extent2].[IsInheritable] AS [IsInheritable], 
        [Extent2].[Created] AS [Created], 
        [Extent2].[Modified] AS [Modified], 
        [Extent2].[IsDeleted] AS [IsDeleted]
        FROM  [dbo].[DashboardPerUser] AS [Extent1]
        INNER JOIN [dbo].[Dashboards] AS [Extent2] ON [Extent1].[DashboardId] = [Extent2].[Id]
        WHERE ([Extent1].[Userid] = @Z_2_p__linq__0) AND ([Extent2].[IsDeleted] <> 1)
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC
```

**Comment by zzzprojects** [comment]
Hello @FilipFilipov ,

I will do some test but I remember the sort was not working due to how relationship manager is made. I'm not 100% positive, so I will check it later today.

Best Regards,

Jonathan

**Comment by FilipFilipov** [comment]
Well, IncludeFilter has no such problems, probably because it only generates a single command. I guess that answers my question of when to use what. If this is a technical limitation of IncludeOptimized you may want to have it throw some error to that effect or at least document it.

**Comment by zzzprojects** [comment]
Hello @FilipFilipov ,

Sorry for the delay, time past too fast!

We finally found what's happening.

- If you try to Order By ascending, you will have a descending order.
- If you try to Order By descending, you will have an ascending order.

That is due because the main query is resolved after "IncludeOptimized" query. If we move the code before IncludeOptimized query, everything works perfectly.

I have not verified why, but I believe it's because the RelationshipManager check latest relation added first. That will explain why we get an inverted order by

We will have some test to do, but a fix should be available within a few days.

Best Regards,

Jonathan

**Comment by FilipFilipov** [comment]
Thank for the update, but I'm actually more concerned with the slow performance of the Query Filter right now. Any news on that front?

**Comment by zzzprojects** [comment]
Yes, a fix should be available today for this one.

In the worse case, today we will revert our change and add options to enable not using the QueryCacheManager from Entity Framework.

**Comment by zzzprojects** [comment]
We did a rollback on the changes we added in v1.4.10

Make sure to read the current [EF6 Limitation with Query Filter](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-Filter-%7C-Entity-Framework-Dynamic-Instance-and-Global-Filters#entity-framework-6---limitations)

Let me know if the performance is now back to normal and if ordering is now working with Query IncludeOptimized

Best Regards,

Jonathan

**Comment by FilipFilipov** [comment]
Performance is back to how it was before. I've only been using the global filter, in fact I'm not sure how to use the instance one. What does the ```this``` in ```this.Filter<Customer>(q => q.Where(x => x.IsActive))``` refer to?

For the order by issue with IncludeOptimized, that still remains. My order wasn't always inverted, rather it kept flipping and I think I figured out why.

I noticed the objects seem to be ordered by their primary key, in this case a guid which randomized on each run. It's not part of the order query, but maybe either sql server or entity framework is doing some kind of default order by the primary key. Doesn't explain why it's not respecting the order defined in the query though.

**Comment by zzzprojects** [comment]
You are currently using "By Instance" filter since you declare it for every context instance.

```csharp
// Global to all instance
QueryFilterManager.Filter<Customer>(q => q.Where(x => x.IsActive));

// By Instance filter
this.Filter<Customer>(q => q.Where(x => x.IsActive));
```

However, you may not be impacted by the concurrency issue reported to us.

If all your context uses the same filters, you are not impacted, since all context will return the same query/result.

The issue happen for using using filter by example for TenantId which is could be different from a context to another.
```csharp
int tenantId = 123; // different from a context to another
this.Filter<Customer>(q => q.Where(x => x.TenantId = 123));
```

We have found a lot of solutions. However, none of them work fully with LazyLoading, so we are still searching... The only solution fully working at this moment is the Empty Dictionary, but it makes everything slower.
