### ISSUE TITLE
Include third level

### ISSUE THREAD

**Issue by arti1zz** [zzzprojects/EntityFramework-Plus#571]
### Description
I'm trying to include third level entities and it's throwing exception

### Code

```
return _context.Lesson
                .IncludeFilter(x => x.LessonTime)
                .IncludeFilter(x => x.Grades)
                .IncludeFilter(x => x.Topics.Where(y => y.IsValid))
                .IncludeFilter(x => x.HomeWorks.Where(y => y.IsValid).Select(q => q.TaskFiles))
                .FirstOrDefaultAsync(x => x.Id == lessonId);
```

### Exception

```
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Processing of the LINQ expression '(source) => (IEnumerable<LessonTime>)source' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlin
k/?linkid=2101433 for more detailed information.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessSelectMany(NavigationExpansionExpression source, LambdaExpression collectionSelector, LambdaExpression resultSelector)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at ?.?(IQueryable ?, Action`1 ?, RelationalQueryContext& ?, Object& ?)
   at Z.EntityFramework.Extensions.EFPlusExtensions.EFPlusCreateCommand(IQueryable source, Action`1 action, RelationalQueryContext& queryContext, Object& compiledQuery)
   at Z.EntityFramework.Plus.BaseQueryFuture.CreateExecutorAndGetCommand(RelationalQueryContext& queryContext)
   at Z.EntityFramework.Plus.QueryFutureBatch.CreateCommandCombined()
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries()
   at Z.EntityFramework.Plus.QueryFutureValue`1.get_Value()
   at Z.EntityFramework.Plus.QueryIncludeFilterProvider`1.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)

```

### Further technical details
- EF version: 3.0.0
- EF Plus version: 3.0.32
- Database Provider: Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0"

**Comment by JonathanMagnan** [comment]
Hello @Jon,

Do you think you could provide a project sample with this issue? I don't think we will be able to reproduce it easily as we might miss a piece of important information about the `LessonTime` collection.

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by arti1zz** [comment]
Hi,
here is the class:
```
public class LessonTime: EntityBase
	{
		[Required]
		public int LessonId { get; set; }
		
		[Required]
		public int Day { get; set; }
		
		[Required]
		public int LessonOrder { get; set; }
	}
}
```

If thats not enough, I will try to create sample project

**Comment by JonathanMagnan** [comment]
Hello @arti1zz ,

Yes, we will need a sample project to look at it.

**Comment by fouadroumieh** [comment]
Is this issue resolved? I'm getting the same error.
