### ISSUE TITLE
EFCore 3.1.1 + FromSqlInterpolated + IQueryable + Count() doenst work

### ISSUE THREAD

**Issue by lixaotec** [zzzprojects/EntityFramework-Plus#575]
Dear fellows,

I´m struggling to use FromCache() in an IQueryable that comes from a FromSqlInterpolated in order to count and retrieve the data further paginated.

Microsoft.EntityFrameworkCore.Query:Error: An exception occurred while iterating over the results of a query for context type '...mycontext..'.
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int64() in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlBuffer.cs:line 351
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()

System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int64() in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlBuffer.cs:line 351
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
Exceção gerada: 'System.InvalidCastException' em Microsoft.EntityFrameworkCore.Relational.dll
Exceção gerada: 'System.InvalidCastException' em System.Private.CoreLib.dll
Exceção gerada: 'System.InvalidCastException' em System.Private.CoreLib.dll
Exceção gerada: 'System.InvalidCastException' em System.Private.CoreLib.dll

**Comment by JonathanMagnan** [comment]
Hello @Jon,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
