### ISSUE TITLE
DeleteAsync thrown System.TypeLoadException exception

### ISSUE THREAD

**Issue by tomasr78** [zzzprojects/EntityFramework-Plus#582]
### Description
DeleteAsync thrown System.TypeLoadException exception.

### Exception
System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.Query.RelationalQueryContextFactory' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 source)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.<>c__DisplayClass3_0`1.<DeleteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---

```
Exception message:
System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.Query.RelationalQueryContextFactory' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Stack trace:
```

### Further technical details
- EF version: 3.1.2
- EF Plus version:
- Database Provider: SQLServer

**Comment by JonathanMagnan** [comment]
Hello @Jon,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

We updated on our side the version to 3.1.2 in our unit test and we don't get any error.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
