### ISSUE TITLE
EFcore 3.1.1 , raw SQL queries + future extension throwing exception

### ISSUE THREAD

**Issue by gabmilg** [zzzprojects/EntityFramework-Plus#585]
### Description
When I'm using raw SQL + future query - an exception is being thrown.
However, when I ran these queries separately everything works perfectly.

```
var futureCount = _dbContext.IntCounts
                .FromSqlInterpolated($@"SELECT Count(*) as [Count] FROM Profile p
                                        WHERE p.Id = {id}"
                .AsNoTracking()
                .FutureValue();

var profiles = _dbContext.Profiles
                .FromSqlInterpolated($@"SELECT...")
                .AsNoTracking()
                .Where(query)
                .Take(take)
                .Skip(skip)
                .Future();

var count = await futureCount.ValueAsync();
var profiles = await profiles.ToListAsync();
```

### Exception
```
Exception message: `No mapping exists from object type System.Object[] to a known managed provider native type.`
Stack trace:

    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Z.EntityFramework.Plus.QueryFutureBatch.<ExecuteQueriesAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Z.EntityFramework.Plus.QueryFutureValue`1.<ValueAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

### Further technical details
- EFCore version: 3.1.1
- EF Plus version: 3.0.40
- Database Provider: SQL server 2012

**Comment by JonathanMagnan** [comment]
Hello @gabmilg ,

Thank you for reporting.

We will look to see if that's possible or not to support it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @gabmilg ,

The v3.0.41 has been released.

This issue should now be fixed.

Could you try the latest version and let us know if everything now works as expected?

**Comment by JonathanMagnan** [comment]
Hello @gabmilg,

Since our last conversation, we haven't heard from you. 

Did you get the chance to try the  v3.0.41?

Don't hesitate to contact us for feedback on the latest version.

**Comment by gabmilg** [comment]
Sorry just got back :(
I've upgraded to latest version, and now I'm getting a different error :
Msg: `The given key 'p0' was not present in the dictionary.`

Trace:

   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Z.EntityFramework.Plus.QueryFutureBatch.CreateCommandCombined()
   at Z.EntityFramework.Plus.QueryFutureBatch.<ExecuteQueriesAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.<ToListAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
...

**Comment by JonathanMagnan** [comment]
Hello @gabmilg ,

Could you provide a project with the issue? So we will make it we fix it correctly.

**Comment by gabmilg** [comment]
unfortunately, I'm not able to provide a project,
but based on my testing any  2 `FromSqlInterpolated`  + future extension calls with SQL params are resulting in this error.

**Comment by JonathanMagnan** [comment]
Hello @gabmilg ,

So can you create an external project with only this issue based on your testing? "based on my testing any 2 FromSqlInterpolated + future extension calls with SQL params are resulting in this error."

I mean, if you cannot create one, I cannot ask my developer either to try to reproduce it (how could possibly he can if you cannot!)

**Comment by gabmilg** [comment]
done : https://github.com/gabmilg/EfcorePlusTest
NetCore 3.1
EFCore 3.1.3
EFCorePlus 3.0.45

**Comment by JonathanMagnan** [comment]
Hello @gabmilg ,

The v3.0.46 has been released.

Let me know if everything is now working.
