### ISSUE TITLE
DeferredAny throwing exception on EFCore 3.1.2

### ISSUE THREAD

**Issue by isen-ng** [zzzprojects/EntityFramework-Plus#588]
### Description
When using `DeferredAny(lambda expression).FutureValue().ValueAsync()`, the following exception is thrown.

This exception is also present for `DeferredAll`, `DeferredAverage` and probably other methods that returns native.

This does not happen when I use `DeferredFirstOrDefault`.

This query was working when we were using EFCore 2.2.

### Exception

```
System.ArgumentException: Expression of type 'System.Boolean' cannot be used for return type 'System.Object'
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Z.EntityFramework.Plus.QueryFutureValue`1.GetResultDirectly()
   at Z.EntityFramework.Plus.QueryFutureValue`1.GetResultDirectlyAsync(CancellationToken cancellationToken)
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueriesAsync(CancellationToken cancellationToken)
   at Z.EntityFramework.Plus.QueryFutureValue`1.ValueAsync(CancellationToken cancellationToken)
   at ... <redacted>
```

### Fiddle or Project
https://dotnetfiddle.net/aU3DSy

Tried to create a fiddle to reproduce this, but it refuses to compile, unless I add the `Z.EntityFramework.Plus.EF6` package. In practise, we are not using `Z.EntityFramework.Plus.EF6`, instead we are using `Z.EntityFramework.Plus.EFCore`

Tried to repo the issue in EF6:
https://dotnetfiddle.net/JgIyfF

it throws a different exception...

### Further technical details
- NetCore: 3.1
- EF version: EFCore 3.1.2
- EF Plus version: 3.0.41
- Database Provider: Npgsql

**Comment by isen-ng** [comment]
I found your dotnetfiddle for efcore, and I'm trying to use it, however, dotnet fiddle seems to be complete not working for me. Can't even sign up properly..

**Comment by isen-ng** [comment]
It's likely due to something in your code, what fails when the linq tries to cast a native value to an object. Eg, cast the result of `DeferredAny` to `FutureValue`.

I have resorted to this workaround:
`await DeferredFirstOrDefault(lambda expression).FutureValue().ValueAsync() != null`

**Comment by JonathanMagnan** [comment]
Thank you for reporting @isen-ng ,

We will look at it with the example you provided.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @isen-ng ,

The v3.0.45 has finally been released.

It should now work as expected.

Best Regards,

Jonathan

**Comment by isen-ng** [comment]
Cool!
Is the the fix that made things work?

https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryDeferred.Shared/QueryDeferred.cs#L109-L115

**Comment by JonathanMagnan** [comment]
Nope, I forget to update the source.

Here is the fix: https://github.com/zzzprojects/EntityFramework-Plus/commit/5220b682e6379d10d111a631814a8c1d81c0c01a#diff-7f68b55da50b02661da96e959b0770ad
