### ISSUE TITLE
EFv6.3 / .NET Core Update() - "A general error has occurred"

### ISSUE THREAD

**Issue by ciaran036** [zzzprojects/EntityFramework-Plus#590]
### Description
I have an ASP.NET Core project which is running as a Windows Service. I am using Entity Framework v6.3 (because it has compatibility with older SQL databases that I need to target).

```
selectedPayments.Update(x => new Payment {Status = PaymentStatus.Pending});
_unitOfWork.Commit();
```

'selectedPayments' is an IQueryable of type Payment, and I am trying to update an enum value, but I've been getting the below exception. 

I originally tried with the deprecated BatchUpdate library (version 1.08), then I tried with the full and latest Z.EntityFramework.Plus library (version 1.12.15) and got an almost identical error. 

I tried a similar operation to update an enum value from a separate .NET Framework ASP.NET MVC5 project with EFv6.2 and the update also failed there also. The common thing is that I'm updating an enum value? Is that why? 

The enum looks like this: 

```
    public enum PaymentStatus
    {
        None,
        [Display(Name="Confirmed")]
        [Description("Confirmed")]
        Confirmed,
        [Description("Payment Pending")]
        Pending,
        Completed,
        [Display(Name="Payment Failed")]
        PaymentFailed
    }
```

### Exception

Exception message:
System.Exception: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com

Stack trace:
 ```
  at Z.EntityFramework.Plus.InternalExtensions.GetObjectQuery[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
   at PaymentBatchProcessorService.Services.PaymentFileGenerator.GeneratePaymentFiles(Int32 paymentBatchId) in C:\Git\ActionRenewables\PaymentBatchProcessorService\Services\PaymentFileGenerator.cs:line 76
   at PaymentBatchProcessorService.GenerateBatchModel.OnGet(Int32 id) in C:\Git\ActionRenewables\PaymentBatchProcessorService\Pages\GenerateBatch.cshtml.cs:line 27
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```
When trying the full library, the exception looked like this: 

```
System.Exception: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com
   at .[](IQueryable`1 )
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at DbContextExtensions.[](IQueryable`1 , Expression`1 , Action`1 , Boolean )
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
   at PaymentBatchProcessorService.Services.PaymentFileGenerator.GeneratePaymentFiles(Int32 paymentBatchId) in C:\Git\ActionRenewables\PaymentBatchProcessorService\Services\PaymentFileGenerator.cs:line 76
   at PaymentBatchProcessorService.GenerateBatchModel.OnGet(Int32 id) in C:\Git\ActionRenewables\PaymentBatchProcessorService\Pages\GenerateBatch.cshtml.cs:line 27
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Fiddle or Project
(Allow me some time to put together a simplified version of the code). 

### Further technical details
- EF version: EFv6.3 (not EF Core)
- EF Plus version: Z.EntityFramework.Plus.EF6 v1.12.15
- Database Provider: SQL Server Express 2017 v14.0.2027

**Comment by JonathanMagnan** [comment]
Hello @ciaran036 ,

This error is often caused by using another third-party library that's not compatible with our current code.

We cannot retrieve the `ObjectQuery` from the `IQueryable` which throws this error.

We will wait for your project to investigate more about it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by ciaran036** [comment]
Thanks for the response! In the same ASP.NET MVC5 project I have Batch update operations which are successful, like this one: 

```
_paymentRepository.All
    .Where(x =>
        x.PaymentBatch.Id == paymentBatchId &&
        x.MeterReading.Station.ClientId == clientId)
    .Update(x => new Payment {Selected = selected});

```

If it works in one place in the application but not the other, would that suggest that it might not be because of an incompatible third-party library? 

Between the MVC5 project and the .NET Core project where the issue occurs there are very few common libraries.

**Comment by JonathanMagnan** [comment]
The easiest way to find out is by received a project that has the error

**Comment by ciaran036** [comment]
I've found the issue. 

This worked: 

_paymentRepository.All
                .Where(x =>
                    x.Id == paymentBatchId &&
                    x.Selected &&
                    x.Status == PaymentStatus.Pending || x.Status == PaymentStatus.PaymentFailed)
                .Update(x => new Payment {Status = PaymentStatus.Confirmed});

This didn't: 

paymentBatch.Payments.AsQueryable().Where(x =>
                    x.Selected &&
                    x.Status == PaymentStatus.Pending || x.Status == PaymentStatus.PaymentFailed)
                .Update(x => new Payment { Status = PaymentStatus.Confirmed });

Perhaps there's a good reason why this wouldn't have worked. I'm not sure. If you think this isn't an issue, I will close this.

**Comment by JonathanMagnan** [comment]
Doing `AsQueryable()` doesn't make it a queryable to the database.

So I'm not exactly sure where is coming the `paymentBatch.Payments`, but it certainly doesn't look like something that can be executed on a database.

So unless I'm missing, that's indeed not a bug.

**Comment by ciaran036** [comment]
Yes, thanks for your assistance anyway, it's appreciated.
