### ISSUE TITLE
"Devart" doesn't necessarily mean "Oracle"

### ISSUE THREAD

**Issue by southlogan** [zzzprojects/EntityFramework-Plus#600]
### Description 
In QueryFutureBatch.CreateCommandCombined, the substring "Devart" is incorrectly taken to be an indication that the db is Oracle.

I'm using Devart dotconnect for PostgreSQL. The command.GetType().FullName for this is "Devart.Data.PostgreSql.Entity.q".

My assumption would be that the line should be changed to:

var isOracleDevArt = command.GetType().FullName.Contains("Devart.Data.Oracle");

but I have no way of testing that that version will correctly detect Oracle.

### Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'type')
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)
   at Z.EntityFramework.Plus.QueryFutureBatch.SetOracleDevArtDbType(Assembly assembly, DbParameter dbParameter, Object type) in D:\Users\Brian\Documents\_NewWork\EntityFramework-Plus\src\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureBatch.cs:line 557

### Further technical details
- EF version: EF Core 3.1.3
- EF Plus version: 3.045
- Database Provider: Devart dotConnect for PostgreSQL 7.17.1612

**Comment by JonathanMagnan** [comment]
Hello @southlogan ,

Thank you for reporting.

Unfortunately at this moment, we only support `Oracle` for `DevArt`. I don't think we want to add more providers for now but we will certainly look at it eventually to support all providers `DevArt` support.

**Comment by southlogan** [comment]
Ok, thanks.

[CTS_Logo (3125x3750 cropped)]
Brian Bell
CTS Asset Management LLC
www.ctsassetmanagement.com<http://www.ctsassetmanagement.com/>
(719) 578-3309 Office
(303) 941-4207 Cell
[cid:image001.png@01D0DFD9.037BD9D0]<http://www.linkedin.com/in/brianbellmanagedfutures>

Past performance is not NECESSARILY indicative of future results.
Commodity trading involves substantial risk of loss.
