### ISSUE TITLE
ArgumentException when using IncludeOptimized

### ISSUE THREAD

**Issue by schuettecarsten** [zzzprojects/EntityFramework-Plus#603]
### Description
The following LINQ query expression gives an ArgumentException when executed:

```
{value(System.Data.Entity.Core.Objects.ObjectQuery`1[Payment]).MergeAs(AppendOnly).Where(x => Not(x.NotificationSent)).OrderBy(x => x.PaymentDate).ThenBy(x => x.PaymentNumber)}
```

Using EF6 with Z.EntityFramework.Extensions v4.0.65 and Z.EntityFramework.Plus.EF6 v1.12.20.

### Exception

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Ein Aufrufziel hat einen Ausnahmefehler verursacht.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Z.EntityFramework.Plus.InternalExtensions.GetCommandTextAndParameters(ObjectQuery objectQuery)
   at Z.EntityFramework.Plus.QueryFutureBatch.CreateCommandCombined()
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.CreateEnumerable()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Z.EntityFramework.Plus.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: A parameter named 'p__linq__0' already exists in the parameter collection. Parameter names must be unique in the parameter collection.
Parametername: item
```

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Do you think you could provide a project sample with this issue?

With your current description, we are not 100% sure how to reproduce it.

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by schuettecarsten** [comment]
Hi Jonathan, I will try to reproduce in a small project, but this might take some time. Please keep in mind that I am re registered user of your libraries with active maintenance - license begins with `1621;100...`.

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Unfortunately, my developer tried but he didn't succeed to reproduce it.

Here is an online example he did: https://dotnetfiddle.net/WSUVuf

Let us know what we are missing to reproduce it.

**Comment by schuettecarsten** [comment]
The sample fails with `Compilation error (line 0, col 0): Metadata file 'C:\Resources\directory\551d2872c49d4959b449f4d78fd30224.DotNetFiddle.Web.LocalResources\NuGetPackages\System.Data.SqlClient\4.5.0.0\lib\net461\System.Data.SqlClient.dll' could not be found` error...

**Comment by JonathanMagnan** [comment]
Yup, it happens sometime in .NET Fiddle until the website restart which fixes it.

The code seem to work again.

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten,

Since our last conversation, we haven't heard from you. 

Don't hesitate to contact us for further assistance. 

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten 

A quick reminder that we are here to assist you. 

don't hesitate to provide a project sample so that we can help you better.

Looking forward to hearing from you, 

Jon
