### ISSUE TITLE
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor

### ISSUE THREAD

**Issue by Tommigun1980** [zzzprojects/EntityFramework-Plus#604]
Using the latest Entity Framework Plus and downloading the just released preview 3 of Entity Framework 5 gives the following error:

```c#
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor Microsoft.EntityFrameworkCore.Query.IQueryableMethodTranslatingExpressionVisitorFactory.Create(Microsoft.EntityFrameworkCore.Metadata.IModel)'.
   at .(IQueryable , RelationalQueryContext& , QuerySqlGenerator& )
   at Z.EntityFramework.Plus.QueryCacheManager.GetCacheKey(IQueryable query, String[] tags)
   at Z.EntityFramework.Plus.QueryCacheExtensions.FromCacheAsync[T](IQueryable`1 query, MemoryCacheEntryOptions options, CancellationToken cancellationToken, String[] tags)
```

when running

```c#
            var something = await this.myContext.MyEntities.AsNoTracking()
                .Where(t => something)
                .GroupBy(t => t.something)
                .Select(t => new { id = t.Key, count = t.Count() })
                .Take(Max).FromCacheAsync(Duration);
```

(problem is probably with .FromCacheAsync()).
This worked fine with preview 2 of EF5.

Thanks.

**Comment by StevenHanquez** [comment]
Same error, but without .FromCacheAsync().

**Comment by JonathanMagnan** [comment]
Hello @Tommigun1980 ,

Thank you for reporting. You are right @StevenHanquez , probably a namespace change in preview 3, we will look at it probably today and release a fix.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Tommigun1980 , @StevenHanquez ,

A new version has been released which should be compatible with the latest preview3.

Let me know if everything works.

Best Regards,

Jon

**Comment by Tommigun1980** [comment]
@JonathanMagnan Works perfectly, thanks! Closing issue.

**Comment by DPiaz** [comment]
I am having a similar issue, but on preview 6 of .NET Core 5.

```
'Method not found: 'Void Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor..ctor(Microsoft.EntityFrameworkCore.Query.IEvaluatableExpressionFilter, Microsoft.EntityFrameworkCore.Query.IParameterValues, System.Type, Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<Query>, Boolean, Boolean)'.'
at .(IQueryable , RelationalQueryContext& , QuerySqlGenerator& )\r\n   
at Z.EntityFramework.Extensions.BatchDelete.CreateCommand(IQueryable query, IEntityType entity)\r\n   
at Z.EntityFramework.Extensions.BatchDelete.Execute[T](IQueryable`1 query)\r\n   
at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)\r\n   
at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query)\r\n   
at KratorLab.Services.EntityService.DeleteEntity(Guid id) in D:\\Lab\\Krator\\KratorLab\\Services\\EntityService.cs:line 114"
```
My code:

```
appDbContext.EntityRelationships
    .Where(r => r.Id == relationship.InverseRelationship.Id)
    .Delete();
```
