### ISSUE TITLE
Use UpdateFromQuery with dynamic paramter will throw exception

### ISSUE THREAD

**Issue by stwilson123** [zzzprojects/EntityFramework-Plus#605]
### Description
The following code can throw exception.
```
                 var initData = new { ttt = "123" };
                dbContext.tESTENTITies.Where(t => t.Id != null).UpdateFromQuery(t => new
                {
                    TESTENTITY2ID = t.TESTENTITY2ID + initData.ttt,
                    COMMENT = "123321"
                });
```

### Exception
Exception message:{"Must declare the scalar variable \"@__ttt_0\".\r\nIncorrect syntax near the keyword 'AS'."}
Stack trace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression, Action`1 batchUpdateBuilde)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression)
   at EFCorePlus.Test.UnitTest1.Test1() in 

### Fiddle or Project
Here is repository
https://github.com/stwilson123/EFCorePlusTest.git

### Further technical details
- EF version:  EF Core 3.1.3
- EF Plus version: Z.EntityFramework.Plus.EFCore 3.0.48
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @stwilson123 ,

After some discussion with my employee, we choose to not yet support it.

The main reason is in case 2 anonymous types is used with the same property name, it causes us too much problem. However, we will eventually try to support it but not right now.

Meanwhile, using a variable will make it works:

```csharp
var initData = new { ttt = "123" };
var ttt = initData.ttt;
dbContext.tESTENTITies.Where(t => t.Id != null).UpdateFromQuery(t => new
{
	TESTENTITY2ID = t.TESTENTITY2ID + ttt,
	COMMENT = "123321"
});
```

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by stwilson123** [comment]
Thanks for your answer.Unfortunatly, I change codes still throw same exception.It doesn't seem to be anonymous types' problem.
```
                 var initData = new test { TESTENTITY2ID = "123" };
                dbContext.tESTENTITies.Where(t => t.Id != null).Update(t => new TESTENTITY
                {
                    TESTENTITY2ID = t.TESTENTITY2ID + initData.TESTENTITY2ID,
                    COMMENT = "123321"
                });
```

**Comment by JonathanMagnan** [comment]
The value must be in a variable, not in an entity

```csharp
var TESTENTITY2ID = "123";
dbContext.tESTENTITies.Where(t => t.Id != null).Update(t => new TESTENTITY
{
TESTENTITY2ID = t.TESTENTITY2ID + TESTENTITY2ID,
COMMENT = "123321"
});
```
