### ISSUE TITLE
Problems with SQLite database and TimeSpan

### ISSUE THREAD

**Issue by leowns** [zzzprojects/EntityFramework-Plus#611]
### Description
I am trying to fetch data from a table of a local SQLite database that includes `TimeSpan`. This works when using EF without EF Plus but when using EF Plus the following error occurs:

```
    public partial class TblMyDates
    {
        public TblMyDates()
        {
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int FkVersionstartdate { get; set; }
        public TimeSpan? Starttime { get; set; }
        public TimeSpan? Endtime { get; set; }
        public TimeSpan? DurationStarttime { get; set; }
        public TimeSpan? DurationEndtime { get; set; }
        public virtual TblAppVersionDates FkVersionstartdateNavigation { get; set; }
     }


    var result = await Db.TblMyDates
                .IncludeOptimized(x => x.FkVersionstartdateNavigation)
                .ToListAsync();
```

### Exception
```
Exception message: 
System.InvalidCastException : Unable to cast object of type 'System.String' to type 'System.TimeSpan'.
Stack trace:
   at Z.EntityFramework.Plus.CreateEntityDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.SetResult(IEnumerator`1 enumerator)
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.SetResult(DbDataReader reader)
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.CreateEnumerable()
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.<GetAsyncEnumerator>b__27_1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Fiddle or Project
https://dotnetfiddle.net/xzABWm

### Further technical details
- EF version: 3.1.4
- EF Plus version: 3.0.50
- Database Provider: Sqlite

**Comment by JonathanMagnan** [comment]
Hello @leowns ,

Thank you for reporting. We will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @leowns ,

Sorry for the long waiting,

The v3.0.51 has been released.

Let us know if everything now works as expected.

Best Regards,

Jon
