### ISSUE TITLE
Is mixing FromSqlRaw and IncludeFilter supported?

### ISSUE THREAD

**Issue by omatrot** [zzzprojects/EntityFramework-Plus#633]
### Description
I'm trying to use FromSQLRaw in conjonction with IncludeFilter and it fails

```
var initialList = await context.AlertDetailsDbSet.FromSqlRaw(@"SELECT dbo.AlertDetail.* FROM dbo.AlertDetail
                        WHERE AlertDetailID IN (
                        select t.AlertDetailID FROM (SELECT
                            ad.AlertDetailID,
                            X.Y.value('(ContextId)[1]', 'varchar(50)') as ContextId,
                            X.Y.value('(Value)[1]', 'varchar(50)') as Value
                        from dbo.AlertDetail as ad
                        OUTER APPLY (SELECT TRY_CAST(CAST(ad.Context AS VARCHAR(MAX)) AS XML)) AS T(Z)
                        OUTER APPLY T.Z.nodes('/SerializableAlertDetail') as X(Y)) as t
                        INNER JOIN dbo.Context c  on t.ContextId = c.ContextId
                        INNER JOIN dbo.EnumDetail e on c.EnumId = e.EnumID
                        WHERE t.ContextId IS NOT NULL AND t.Value IS NOT NULL
                        AND e.IsPreAlert = 1)")
                        // Pouring the TrackedVehicle related graph
                        .IncludeFilter(ad => ad.TrackedVehicule)
                            .IncludeFilter(ad => ad.TrackedVehicule.AlertInstructions.Where(ai => ai.RowEnabled == true))
                            .IncludeFilter(ad => ad.TrackedVehicule.Registration)
                            .IncludeFilter(ad => ad.TrackedVehicule.Device)
                            .IncludeFilter(ad => ad.TrackedVehicule.GpsBox)
                            .IncludeFilter(ad => ad.TrackedVehicule.GpsBox.Icon)
.OrderByDescending(ad => ad.AlertDateTime)

                         .Skip(skip)

                         .Take(take)

                         // We disable the tracking mechanism because the context will be thrown away as soon as we have the data
                         .AsNoTracking()

                         // We want an asynchrounous execution
                         .ToListAsync(cancellationToken)

                         // We do not need to preserve the context because we're immdiately finished
                         .ConfigureAwait(continueOnCapturedContext: false);
```
As soon as I remove the IncludeFilter calls it works.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (No mapping exists from object type System.Object[] to a known managed provider native type.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RTE.Technologies.SafeProtect.Common.DummyConsole.Program.Main(String[] args) in D:\AzureDevops\SafeProtect.Common\SafeProtect.Common.Data.ConsoleTest\Program.cs:line 356

  This exception was originally thrown at this call stack:
    [External Code]
    RTE.Technologies.SafeProtect.Common.Data.DataBridge.Core.AlertDetailDataBridge.GetAlertDetailListAsync(int, int, int, bool, bool, System.Threading.CancellationToken) in AlertDetailDataBridge.cs

Inner Exception 1:
ArgumentException: No mapping exists from object type System.Object[] to a known managed provider native type.

```

### Fiddle or Project
Should be easy to reproduce.

### Further technical details
- EF version: 3.1.8
- EF Plus version: 3.0.61
- Database Provider: MS SQL Server

**Comment by JonathanMagnan** [comment]
Hello @omatrot ,

Unfortunately no, this is not supported.

To support it, we will need to re-write probably fully this feature and even more, investigate if it's still useful as EF Core 5 is bringing a feature similar to include filter.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by omatrot** [comment]
Will it work if I'm using a view instead?

**Comment by JonathanMagnan** [comment]
I don't think it will work either @omatrot ,

As said, when we initially built this feature, it was for pure LINQ, we never did any test with SQL or view
