### ISSUE TITLE
Convention for property names is not taken into account with some InsertFromQuery overloads

### ISSUE THREAD

**Issue by citypermit** [zzzprojects/EntityFramework-Plus#636]
### Description
In our (ORACLE) database alle table names and property names are uppercase. Therefore we use a convention to convert all table and property names from the EF model to uppercase. In some InsertFromQuery overloads the resulting query doesn't have the uppercase property names which will result in an Oracle exception that the column is unknown. The table name is correctly converted to uppercase:
`////context.PermitStates.InsertFromQuery(x => new Tag { Name = x.Name }); // This works
////context.PermitStates.InsertFromQuery("Tag", x => new { NAME = x.Name }); // This works
context.PermitStates.InsertFromQuery("Tag", x => new { x.Name }); // This doesn't work`

It is also possible to disable quoting for queries generated by DevArt instead of using the UpperCaseConvention:
Devart.Data.Oracle.Entity.Configuration.OracleEntityProviderConfig.Instance.Workarounds.DisableQuoting = true;
This also does not work.

### Exception
`Devart.Data.Oracle.OracleException
  HResult=0x80004005
  Message=ORA-00904: "Name": invalid identifier
  Source=Devart.Data.Oracle
  StackTrace:
   at Devart.Data.Oracle.ea.a(j A_0, Int32 A_1)
   at Devart.Data.Oracle.ea.a(Int32 A_0, ef A_1)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.OracleCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<NonQuery>b__4_0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at .(ObjectContext , DbCommand )
   at `1.Execute(IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression, Type tableType)
   at DbContextExtensions.[](IQueryable`1 , String , String , String , Expression`1 , Type )
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression)
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, String tableName, Expression`1 selectFieldsExpression)
   at TestConsoleApplication.Program.Main() in C:\local\TestConsoleApplication\TestConsoleApplication\Program.cs:line 11

  This exception was originally thrown at this call stack:
    [External Code]
    TestConsoleApplication.Program.Main() in Program.cs`

### Fiddle or Project
Included my test project. The connection string is of course changed.
[TestConsoleApplication.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/5305910/TestConsoleApplication.zip)

### Further technical details
- EF version: 6.4.4 (6.3 has the same issue)
- EF Plus version: 4.0.96
- Database Provider: Devart.Data.Oracle

**Comment by JonathanMagnan** [comment]
Hello @citypermit ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @citypermit ,

Sorry for the long waiting, it looks like we forget to answer you.

We already released 1-2 weeks ago this fix and the `DisableQuoting` should now be supported for `InsertFromQuery` and a few more methods.

Could you try it and let us know if everything is correctly fixed?

**Comment by citypermit** [comment]
Both the UpperCaseConvention and the Devart specific DisableQuoting option are working. Thank you very much.
