### ISSUE TITLE
Problem with Z.EntityFramework.Plus Generated Query not following Ef Core Relational Names

### ISSUE THREAD

**Issue by tdolgyras** [zzzprojects/EntityFramework-Plus#643]
# Description
We use multiple Database Providers in our project. Our naming conventions in our c# code is PascalCase. In PostgreSql, we have a fix setting PascalCase in lower_case_with_underscores. So, we can have easier sql code in PostgreSql. 
We had a possible same issue here #issue: #487 

### Exception
In this case when we execute this code:
`await db.Blogs.Where(x => x.Rating > 10).UpdateAsync(x => new Blog { Rating = 11 });`
we receive an error like below.
```
Exception message From Our Project:  42703: column b.blog_id does not exist
Npgsql.PostgresException (0x80004005): 42703: column b.blog_id  does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Extensions.BatchUpdate.<>c.?(DbCommand ?, Nullable`1 ?)
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.<>c__DisplayClass2_0`1.<UpdateAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
 
  Exception data:
    Severity: ERROR
    SqlState: 42703
    MessageText: column b.blog_id does not exist
    Position: 1491
    File: parse_relation.c
    Line: 3359

```

### Further technical details
- EF version: Microsoft.EntityFrameworkCore 3.1
- EF Plus version: Z.EntityFramework.Plus.EFCore 3.0.65
- Database Provider: MsSql, Pomelo.EntityFrameworkCore.MySql, Npgsql.EntityFrameworkCore.PostgreSQL

I have created a sample project with this  issue and i have attached it here

[Z.EntityFramework.Plus.Issue.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/5372151/Z.EntityFramework.Plus.Issue.zip)

**Comment by JonathanMagnan** [comment]
Hello @tdolgyras ,

Thank you for reporting, my developer will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @tdolgyras 

We tried to reproduce it but your project looks to work like a charm on our side.

All we did is modified the connection string.

---

This is currently not an issue in your project but usually in test, after an `Update`, you should use `AsNoTracking()`

The problem is the `Update` method directly updates the value in the database, so without modifying the `ChangeTracker`. So if the entity has already been loaded in the `ChangeTracker`, even if the value has been modified in the database, the `ChangeTracker` will still contain the entity with the old value since he is not aware a modification has been made (even if you query the database). As said, that's currently not a problem in your test but just in case.

---

Is there anything in mind you believe we are missing to reproduce the issue?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @tdolgyras ,

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, do you believe we are missing something to reproduce the issue?

Looking forward to hearing from you, 

Jon

**Comment by tdolgyras** [comment]
Hello @JonathanMagnan,
sorry for the delay. It seems that the problem never existed. I didn't check the Database entries but only the sample project console logs. 

The sample project in console, logs the last value before update(the value is 16 for example), even if the updateAsync() command has been already executed and the console has to log the new value for Rating(the value has to be 17). See the picture below.
![ex](https://user-images.githubusercontent.com/37415911/96458495-a9ffba00-1229-11eb-975e-a3638d8f3ca4.PNG)

I am sorry for the inconvenience caused.

**Comment by JonathanMagnan** [comment]
Hello @tdolgyras ,

That's because of the explanation we provided about `AsNoTracking()`. You need to use it if you re-use the same context otherwise, the value from the loaded entity will be taken even if differently from the database.
