### ISSUE TITLE
Deferred/QueryFutureValue fails in EF Core 5 with RetryExecutionStrategy

### ISSUE THREAD

**Issue by bfbrown** [zzzprojects/EntityFramework-Plus#651]
### Description
After upgrading to EF Core 5 and while using the SqlServer option _.EnableRetryOnFailure()_, the execution of a QueryFutureValue<> with more than one deferred query composed throws an exception. 

### Exception
System.InvalidOperationException
```
Exception message: The underlying reader doesn't have as many fields as expected. Expected: 1, actual: 0.
Stack trace:
at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeFields()
       at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.Initialize(DbDataReader reader, IReadOnlyList`1 columns)
       at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.Initialize(IReadOnlyList`1 columns)
       at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
       at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
       at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
       at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
       at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
       at Z.EntityFramework.Plus.QueryFutureValue`1.SetResult(DbDataReader reader)
       at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueriesAsync(CancellationToken cancellationToken)
       at Z.EntityFramework.Plus.QueryFutureValue`1.ValueAsync(CancellationToken cancellationToken)

```

### CSPROJ
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!--PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.10" /-->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.0" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!--PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="3.1.0" /-->
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="5.1.0]" />
  </ItemGroup>
</Project>
```

### Unit Test

```cs
using Microsoft.EntityFrameworkCore;
using NUnit.Framework;
using System.Collections.Generic;
using Z.EntityFramework.Plus;

namespace MyTests
{
    [TestFixture]
    public sealed class FutureTests
    {
        private const string ConnectionString = "Data Source=LOCALHOST;Initial Catalog=tempdb;Integrated Security=True;";

        private QueryFutureValue<bool> GetFutureQuery(TestDbContext context)
        {
            return context.SysTables.DeferredAny().FutureValue();
        }

        [TestCase(1)]   //always passes
        [TestCase(2)]   //always passes
        public void Multiple_futures(int count)
        {
            var options = new DbContextOptionsBuilder().UseSqlServer(ConnectionString).Options;
            using var context = new TestDbContext(options);

            var futures = new List<QueryFutureValue<bool>>(count);

            for (int i = 0; i < count; i++)
                futures.Add(GetFutureQuery(context));

            Assert.DoesNotThrowAsync(async () => await futures[0].ValueAsync());
        }

        [TestCase(1)]   //always passes
        [TestCase(2)]   //EF Core 5: <System.InvalidOperationException: The underlying reader doesn't have as many fields as expected. Expected: 1, actual: 0.
        public void Multiple_futures_with_retry(int count)
        {
            var options = new DbContextOptionsBuilder().UseSqlServer(ConnectionString, more => more.EnableRetryOnFailure()).Options;
            using var context = new TestDbContext(options);

            var futures = new List<QueryFutureValue<bool>>(count);

            for (int i = 0; i < count; i++)
                futures.Add(GetFutureQuery(context));

            Assert.DoesNotThrowAsync(async () => await futures[0].ValueAsync());
        }

        private sealed class TestDbContext : DbContext
        {
            public TestDbContext(DbContextOptions options) : base(options) { }

            public DbSet<SysTable> SysTables { get; set; }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<SysTable>().HasNoKey().ToView("tables", "sys");

                base.OnModelCreating(modelBuilder);
            }

            public class SysTable { }
        }
    }
}

```

### Further technical details
- EF version: Core 5.0.0
- EF Plus version: 3.1.0
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @bfbrown ,

Thank you for reporting, we will look at it and check if that could be possible to support it or not.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @bfbrown ,

It took us time but starting with the v3.1.6 it should now be fixed.

If you have the chance to try it, let me know if my developer successfully fixed it.

Best Regards,

Jon

**Comment by SergeyBalanEmpeek** [comment]
Thank you Jonathan. I had a bit different scenario with similar error message.
I've tried v5.1.6 and looks like problem is solved in my case

**Comment by JonathanMagnan** [comment]
Great! 

Don't hesitate to contact us if you need further assistance. 

Best regards, 

Jon
