### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException: 'Conversion failed when converting the nvarchar value 'Value1' to data type int.'

### ISSUE THREAD

**Issue by t11omas** [zzzprojects/EntityFramework-Plus#664]
### Description
When using an enum which has the enum as string conversion turned on and making use of that in a future query then it fails with a conversion error.

//This works ok
`dbContext.Examples.Where(x => x.ExampleEnumValue == ExampleEnum.Value1);`

//This doesn't work
```
 QueryRequest request = new QueryRequest();
request.ExampleEnum = ExampleEnum.Value1;
dbContext.Examples.Where(x => x.ExampleEnumValue == request.ExampleEnum);
```

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Conversion failed when converting the nvarchar value 'Value1' to data type int.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Z.EntityFramework.Plus.CreateEntityDataReader.Read()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at Z.EntityFramework.Plus.QueryFutureValue`1.SetResult(DbDataReader reader)
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFPlusConversion.Program.Main(String[] args) in C:\Users\t11om\source\repos\EFPlusConversion\EFPlusConversion\Program.cs:line 55

  This exception was originally thrown at this call stack:
    [External Code]
    EFPlusConversion.Program.Main(string[]) in Program.cs
```
Exception message:
Stack trace:
```

### Fiddle or Project
[EFPlusConversion.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/5738726/EFPlusConversion.zip)

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- EF version:
- EF Plus version:
- Database Provider:

**Comment by JonathanMagnan** [comment]
Hello @t11omas ,

Thank you for the project, my developer will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @t11omas ,

The v5.1.11 has been released.

Could you try it and let me know if my developer successfully fixed your issue correctly?
