### ISSUE TITLE
EFcore 5.0.1+FromSqlRaw + Future() extension causes System.ArgumentException (similar to #585)

### ISSUE THREAD

**Issue by Thundarr1974** [zzzprojects/EntityFramework-Plus#666]
### Description
When using "FromSqlRaw" to populate an entity from a derived query, a System.ArgumentException exception is thrown.

        public virtual DbSet<LocalEnum> LocalEnums { get; set; }

        modelBuilder.Entity<LocalEnum>().HasNoKey().ToView("_no_table");

        public IQueryable<LocalEnum> FromEnum<T>()
        {
            var typeT = typeof(T);

            var selects = Enum.GetValues(typeT)
                .Cast<T>()
                .Select(e => $"({Convert.ToInt32(e)}, '{e}')"); // Todo localize

            var sql = $"SELECT * FROM (VALUES {string.Join(", ", selects)}) AS {typeT.Name}([Value], [Name])";

            return LocalEnums.FromSqlRaw(sql);
        }

        public static async Task<(int Count, T[] Items)> GetPaged<T, TSort>(this IQueryable<T> qry, int page, Expression<Func<T, TSort>> defaultSort, CancellationToken cancellationToken) where T : class
        {
            var skip = (page - 1) * PAGE_SIZE;

            var ftrCount = qry
                .DeferredCount()
                .FutureValue();

            var ftrItems = qry
                .OrderBy(defaultSort)
                .Skip(skip)
                .Take(PAGE_SIZE)
                .Future();

            var count = await ftrCount.ValueAsync(cancellationToken);
            var items = await ftrItems.ToArrayAsync(cancellationToken);

            return (count, items);
        }

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.ArgumentException: No mapping exists from object type System.Object[] to a known managed provider native type.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueriesAsync(CancellationToken cancellationToken)
   at Z.EntityFramework.Plus.QueryFutureValue`1.ValueAsync(CancellationToken cancellationToken)
   at ZEFPlusTest.Extensions.GetPaged[T,TSort](IQueryable`1 qry, Int32 page, Expression`1 defaultSort, CancellationToken cancellationToken) in C:\Users\terickson\Source\repos\EfcorePlusTest2\ZEFPlusTest\Extensions.cs:line 28
   at ZEFPlusTest.Program.MainAsync() in C:\Users\terickson\Source\repos\EfcorePlusTest2\ZEFPlusTest\Program.cs:line 62P
```

### Fiddle or Project
https://github.com/Thundarr1974/EfcorePlusTest

### Further technical details
- EF version: 5.0.1
- EF Plus version: 5.1.11
- Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by JonathanMagnan** [comment]
Thank you for your project,

My developer will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Thundarr1974 ,

The v5.1.12 has been released.

Could you try it and let me know if my developer successfully fixed your issue?

**Comment by Thundarr1974** [comment]
I updated the test solution to use 5.1.12, but I'm still seeing the error message:

![image](https://user-images.githubusercontent.com/77063909/104191379-70cf8400-53eb-11eb-82d4-aaf6299b24c2.png)

**Comment by JonathanMagnan** [comment]
Thank, I will follow-up with my developer.

He already got a project, so I will check with him why this is working on his side.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Thundarr1974 ,

The v5.1.13 has been released.

Could you try this version and let me know if this time the right issue has been fixed?

**Comment by Thundarr1974** [comment]
Hi Jonathan,

The test solution did work, but my project still had the error.  After some digging, I found the issue still happens if a strongly typed projection is used in the query.  So this works now...

`
                var qry = from p in context.Profiles
                          join pid in context.FromEnum<ProfileId>() on p.Id equals pid.Value
                          select new
                          {
                              p.Id,
                              pid.Name
                          };
`
but it fails if we remove the anonymous select

`
                          select new ProfileView
                          {
                              Id = p.Id,
                              Name = pid.Name
                          }
`

I updated the test solution to replicate the new finding.

**Comment by JonathanMagnan** [comment]
Thank,

My developer will look at this case.

**Comment by JonathanMagnan** [comment]
Hello @Thundarr1974 ,

A new version is now available.

My developer changed the way he initially solved this issue, let hope everything is fine this time ;)

Best Regards,

Jon

**Comment by Thundarr1974** [comment]
Thanks Jon, I pulled the latest and the issue has been resolved - closing.

**Comment by musabsudan** [comment]
@JonathanMagnan  I have the same issue:
EF version: 6.0.1
EF Plus version: 6.13.5
Database Provider: Microsoft.EntityFrameworkCore.SqlServer


```
No mapping exists from object type System.Object[] to a known managed provider native type.

   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)     at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)  --- End of stack trace from previous location ---     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)  --- End of stack trace from previous location ---     at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueriesAsync(CancellationToken cancellationToken)     at Z.EntityFramework.Plus.QueryFutureEnumerable`1.ToListAsync(CancellationToken cancellationToken)     at Connect.Web.Paging.PagedList`1.GetPagedList(IQueryable`1 source, PagingParameters query) in C:\Users\Musab\source\repos\connect\Connect.Web\Paging\PagedList.cs:line 39     at Connect.Web.Utilities.IQueryableExtensions.ToPagedResultAsync[T](IQueryable`1 source, PagingParameters query) in C:\Users\Musab\source\repos\connect\Connect.Web\Utilities\IQueryableExtensions.cs:line 17     at Connect.Web.Controllers.InfrastructureController.Get(PagingParameters paging, InfrastructureFilter filters, IEnumerable`1 qf) in C:\Users\Musab\source\repos\connect\Connect.Web\Controllers\InfrastructureController.cs:line 60     at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)     at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)     at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)     at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)     at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)     at Connect.Web.Utilities.ErrorHandlingMiddleware.Invoke(HttpContext context, ErrorsDbContext dbContext) in 
```

**Comment by JonathanMagnan** [comment]
Hello @musabsudan ,

My developer tell me he tested this version and everything work as expected. 

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here info@zzzprojects.com

Best Regards,

Jon
