### ISSUE TITLE
Query Filter help

### ISSUE THREAD

**Issue by SamWalkerRxSense** [zzzprojects/EntityFramework-Plus#672]
## 1. Description
Trying to reproduce this example on this page.
https://entityframework-plus.net/ef6-query-filter-logical-data-partitioning

```
// myCategoryID = 9

// using Z.EntityFramework.Plus; // Don't forget to include this.
var ctx = new EntitiesContext();
ctx.Filter<Product>(x => ctx.ProductByCategory.Any(
                          y => y.CategoryID == myCategoryID 
                               && y.ProductID == x.ProductID))

// SELECT * FROM Product AS X WHERE EXISTS
//   (SELECT 1 FROM ProductByCategory AS Y 
//        WHERE Y.CategoryID = 9 AND Y.ProductID = X.ProductID)
var list = ctx.Products.ToList();
```

But I get an exception.

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Run-time exception (line 32): An error occurred while preparing the command definition. See the inner exception for details.

Stack Trace:

[System.ArgumentException: The ResultType of the referenced variable 'LQ6' does not match the type specified in this variable reference expression.
Parameter name: query]
   at System.Data.Entity.Core.Common.CommandTrees.Internal.DbExpressionValidator.Visit(DbVariableReferenceExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbVariableReferenceExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbExpressionRebinder.Visit(DbPropertyExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbPropertyExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitBinary(DbBinaryExpression expression, Func`3 callback)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbComparisonExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbComparisonExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitBinary(DbBinaryExpression expression, Func`3 callback)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbAndExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbAndExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbQuantifierExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbQuantifierExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbFilterExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbQueryCommandTree..ctor(MetadataWorkspace metadata, DataSpace dataSpace, DbExpression query, Boolean validate, Boolean useDatabaseNullSemantics)

[System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.]
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Z.EntityFramework.Plus.QueryFilterInterceptorDbCommandTree.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.<Created>b__0(IDbCommandTreeInterceptor i, DbCommandTreeInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)

[System.Data.Entity.Core.EntityCommandCompilationException: An error occurred while preparing the command definition. See the inner exception for details.]
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main() :line 32
```

## 3. Fiddle or Project
https://dotnetfiddle.net/rA8Ba7

## 4. Any further technical details
I can't figure out what I'm doing wrong.

Thanks for the help.

**Comment by JonathanMagnan** [comment]
Your syntax and logic are right and there is nothing wrong.

However, the expression is limited by either Entity Framework or our library. You currently use a context query in another query which might work in many cases but doesn't look compatible with our library and the way we do it.

Here is a working example: https://dotnetfiddle.net/EU2Ji7

Basically, I just added a list reference to be able to directly filter it instead of trying to join it with another queryiable.

Let me know if that answer correctly to your issue.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by SamWalkerRxSense** [comment]
Thanks for the help.  So, by adding `List<ProductByCategory> Categories` Entity Framework is implicitly joining the entities because it follows convention.

Is it possible without adding the List<T> reference?  

I have a legacy system with many relationships that don't follow conventions.  These are joined explicitly, resulting in a lot of repetitious looking code.  I was hoping the query filters would help eliminate some of that, but it may just be the penalty for being unconventional.

Thanks for the assistance,

**Comment by JonathanMagnan** [comment]
Hello @SamWalkerRxSense ,

One alternative solution would simple to don't use our library and do it on your side.

Here is an example: https://dotnetfiddle.net/883Eh6

So the "ProductsFiltered" will always use your specific filter.

Perhaps that could be a better solution for you?

Best Regards,

Jon

**Comment by SamWalkerRxSense** [comment]
Thanks for the example.  That may be what we'll have to do.

**Comment by JonathanMagnan** [comment]
Awesome @SamWalkerRxSense 

Don't hesitate to contact us with any questions or further assistance!
