### ISSUE TITLE
Not Compatible With Latest Version of Entity Framework Core

### ISSUE THREAD

**Issue by ooples** [zzzprojects/EntityFramework-Plus#675]
Exception Type:
System.MissingMethodException

Exception Message:
Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(Microsoft.EntityFrameworkCore.Metadata.IModel, System.Type)'.

Exception StackTrace:
at ?.?[?](DbContext this, IEnumerable1 ?, List1 ?)
at ?.BulkUpdate[T](DbContext this, IEnumerable1 entities, Action1 options, Boolean isBulkSaveChanges)
at DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable1 entities, Action1 options)
at DbContextExtensions.?1.?() at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj) at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location --- at DbContextExtensions.BulkUpdateAsync[T](DbContext this, IEnumerable1 entities, Action1 options, CancellationToken cancellationToken) at OoplesFinanceAdminClient.Utils.<>c__DisplayClass30_11.<b__0>d.MoveNext() in D:\Code Projects\OoplesFinanceAdminClient\Utils.cs:line 633
--- End of stack trace from previous location ---
at Polly.AsyncPolicy.<>c__DisplayClass40_0.<b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates1 shouldRetryResultPredicates, Func5 onRetryAsync, Int32 permittedRetryCount, IEnumerable1 sleepDurationsEnumerable, Func4 sleepDurationProvider, Boolean continueOnCapturedContext) at Polly.AsyncPolicy.ExecuteAsync(Func3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass4_0.<b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Polly.Fallback.AsyncFallbackPolicy.<>c__DisplayClass3_0.<b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Polly.Fallback.AsyncFallbackEngine.ImplementationAsync[TResult](Func3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates1 shouldHandleResultPredicates, Func3 onFallbackAsync, Func4 fallbackAction, Boolean continueOnCapturedContext)

Exception Target Site:
?

Exception Source:
Z.EntityFramework.Extensions.EFCore

I get the above exception when I try to use the BulkUpdate command and I'm using the following versions in my proejct:

Microsoft.EntityFrameworkCore.SqlServer v6.0.0-preview.2.21154.2
Z.EntityFramework.Plus.EFCore v6.0.0-preview.1.21102.2-01

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

Thank you for reporting.

We are indeed not yet compatible with the `preview2`, only the `preview.`.

We already have a fix that we hope to merge later this week to support the `preview2`.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

Just to let you know that the latest version is now compatible with the `preview2`. We still have a small issue to fix on our side but we do not believe that will impact anyone.

If you have a problem, just let us know.

Best Regards,

Jon

**Comment by ooples** [comment]
I did receive that update and it did fix the issue but it turns out that they just released a newer version for Entity Framework Core that also isn't compatible with your latest version

**Comment by JonathanMagnan** [comment]
No problem,

We will look at it to make it compatible with the latest version

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

We upgraded our project to the latest version of EF Core: 6.0.0-preview.3.21201.2

However, we didn't found any issue.

Could you give us more information about the issue you got? We will release a new version next Monday with the dependencies upgraded, however, no change has been done so far besides this one since everything look to work fine on our side.

**Comment by ooples** [comment]
I will try out the newer version you released and see if that fixes the issue. I forgot to save the exception I got when I tried your older version

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

A new version for the preview 3 has been released.

As said, beside dependencies, nothing has been modified so if you still have an issue, we will surely need your exception message.

Best Regards,

Jon
