### ISSUE TITLE
Update not working with ObjectContext

### ISSUE THREAD

**Issue by Coder3333** [zzzprojects/EntityFramework-Plus#681]
## 1. Description
I have a very simple query that uses the old ObjectContext, instead of DbContext, and it fails when I try to perform an Update.

## 2. Exception
```
Exception message:
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com

Stack trace:
at .[](IQueryable`1 )
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at DbContextExtensions.[](IQueryable`1 , Expression`1 , Action`1 , Boolean )
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)

```

## 4. Any further technical details
I have traced the server, and no SQL is being executed.

Z.EntityFramework.Plus.EF6 5.1.31.0

**Comment by JonathanMagnan** [comment]
Hello @Coder3333 ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Coder3333 ,

We didn't successfully implement it in our library.

However, we have a public extension method that could help you: `GetOrCreateDbContext`

Such as:

```csharp
objectContext.GetOrCreateDbContext().Set<Customer>().Update(x => new Customer {Code = "zzz"});
```

Let me know if this workaround is working for you.

As you understand, this method returns a `DbContext` even if you are using purely an `ObjectContext`.

Best Regards,

Jon
