### ISSUE TITLE
Z.EntityFramework.Plus.EFCore: Postgres database, JSONB data type and FutureValue (InvalidCastException)

### ISSUE THREAD

**Issue by thebestgin** [zzzprojects/EntityFramework-Plus#688]
Hi, 

I have a problem with Z.EntityFramework.Plus.EFCore in combination with Postgres database, JSONB data type and EFPlus FutureValue.

I got this exeption: System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 

Is there any change to fix the problem?

```
public class SomeClass
{
	publig int Id { get; set; }

    [Column(TypeName = "jsonb")]
    public SummeryPlain SummeryPlain { get; set; }		
}
```

**Comment by JonathanMagnan** [comment]
Hello @thebestgin ,
 
Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.

_Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by thebestgin** [comment]
> Hello @thebestgin ,
> 
> Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.
> 
> _Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._
> 
> _Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._
> 
> You can send it to [info@zzzprojects.com](mailto:info@zzzprojects.com) if you need to keep the source private
> 
> Best Regards,
> 
> Jon
> 

Sounds good. I will prepare an executable ASP Core Visual Studio project.

**Comment by JonathanMagnan** [comment]
Hello @thebestgin 

A simple reminder that we are here to assist you!

Don't hesitate to send your runnable project sample to our support team info@zzzprojects.com

Best regards,

Jon

**Comment by thebestgin** [comment]
Hello Jon,

I have programmed an example project for you.

In the sample project everything works fine.

I first have to figure out what is different in my big project.

Thank you for your support.

**Comment by thebestgin** [comment]
Hello Jon,

I have reproduced the error.
[EFPlusFutureProblemPostgres.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/6681416/EFPlusFutureProblemPostgres.zip)


![image](https://user-images.githubusercontent.com/10037845/122657243-2a344180-d162-11eb-9ec9-22df146a4de3.png)

This is the reason of the error
![image](https://user-images.githubusercontent.com/10037845/122657279-85663400-d162-11eb-9ea8-713b2bc38de6.png)

**Comment by JonathanMagnan** [comment]
Thank a lot,

My developer will look at this.

**Comment by thebestgin** [comment]
Do you have plans to make this feature available?

**Comment by JonathanMagnan** [comment]
Unfortunately, we have currently way more requests than we can handle during the summer.

This request is currently in a pending state on our side.

Once we complete all the current requests, we will look at this list but for this moment, there is no short-term plan to make it happens. That's unfortunately impossible due to resource/time available ;(

**Comment by ipostanogov** [comment]
Hi, @JonathanMagnan

Here is another [example](https://github.com/zzzprojects/EntityFramework-Plus/files/7008220/IncludeFilterDemo.zip) of an error related to postgres json mapping:

```
Unable to cast object of type 'System.String' to type 'System.Text.Json.JsonDocument'.
   at Z.EntityFramework.Plus.CreateEntityDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.SetResult(IEnumerator`1 enumerator)
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.SetResult(DbDataReader reader)
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Z.EntityFramework.Plus.QueryIncludeFilterParentQueryable`1.CreateEnumerable()
   at Z.EntityFramework.Plus.QueryIncludeFilterParentQueryable`1.<GetAsyncEnumerator>b__25_1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Z.EntityFramework.Plus.LazyAsyncEnumerator`1.FirstMoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at IncludeFilterDemo.Program.Main(String[] args) in ~/IncludeFilterDemo/Program.cs:line 42
   at IncludeFilterDemo.Program.Main(String[] args) in ~/IncludeFilterDemo/Program.cs:line 43
   at IncludeFilterDemo.Program.<Main>(String[] args)
```

**Comment by thebestgin** [comment]
Hi @JonathanMagnan,

Your paid Entity Framework Extension Library has the same problem with the jsonb / json data type in FutureAction.
https://entityframework-extensions.net/bulk-merge#merge-with-future-action
The error occurs when there is more than one entity in a batch transaction.

We want to use Entity Framework Plus / Extension for our next products. 
The missing feature with jsonb / json is really a pain point. 
Entity Framework Plus / Extension with Postgres and jsonb would be such a booster.

I hope for a solution. Then we will invest in your paid Entity Framework Extension library.

Many thanks for your effort.

**Comment by JonathanMagnan** [comment]
Hello @thebestgin ,

The `FutureAction` in EFE works very differently than `FutureValue` in `EF Plus`.

In fact, `FutureAction` just creates a pending list that will be executed later. So on this feature, there is nothing we can do or improve as the only thing this feature does is `I will execute this same exact code but only when you call the Execute method`. 

`FutureValue` work differently as this is the one that batches multiple SQL Statement in the same command.

**Comment by colleonimattia** [comment]
I have the exact same problem.
Any updates on that?
Thanks,

M

**Comment by JonathanMagnan** [comment]
Thank you for reaching out to ZZZ Projects, due to the holiday vacation we will have limited email access which may cause some delays from December 23 to January 2. 
We are sorry for any inconvenience and will get back to you shortly.

**Comment by thebestgin** [comment]
> I have the exact same problem. Any updates on that? Thanks,
> 
> M

Unfortunately not.

There are only ugly workarounds.
Use a string data type instead of JSON. Use plain SQL or Dapper. 

Maybe it is worth to open the issue in the Postgres community.

**Comment by wisedf** [comment]
![image](https://github.com/user-attachments/assets/f04158d5-fd1f-434c-84b0-d0eb13171838)
![image](https://github.com/user-attachments/assets/a4cdfa13-f4ab-446b-8dcb-624e28c7217e)

 
Error occurs when trying to update any jsonb type field in postgresql, any solution to this problem?

**Comment by wisedf** [comment]
Solution in https://github.com/zzzprojects/EntityFramework-Plus/issues/812
