### ISSUE TITLE
Error with IncludeFilter() when executed in an ambient transaction.

### ISSUE THREAD

**Issue by mlhuong** [zzzprojects/EntityFramework-Plus#691]
## 1. Description
Error with IncludeFilter() when executed in an ambient transaction.

## 2. Exception

```
Exception message:
An exception occurred while iterating over the results of a query for context type 'Dpx.Core.Data.Referential.Test.ReferentialDbContext'.
System.NotSupportedException: Specified method is not supported.
   
Stack trace:
at System.Data.Common.DbConnection.EnlistTransaction(Transaction transaction)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.HandleAmbientTransactions()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
```

## 3. Fiddle or Project

using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                var result = await Context.Set<MyUser>()
                .IncludeFilter(x => x.Reports.Where(y => y.IsActive))
                .ToArrayAsync().ConfigureAwait(false);
                transaction.Complete();
                return result;
            }

## 4. Any further technical details
If I remove the using(transaction..) block, the code works prefectly.

**Comment by JonathanMagnan** [comment]
Hello @mlhuong ,

Thank you for reporting, we successfully reproduced it.

We will check if there is something we can change to make it works.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @mlhuong ,

The v5.2.3 has been released.

Could you test it and let us know if we fixed this issue correctly?

Best Regards,

Jon

**Comment by mlhuong** [comment]
Hello,

Thanks for the fix. 
It works well now :)

**Comment by JonathanMagnan** [comment]
Awesome @mlhuong !

We are glad to hear that the issue has been fixed!

Don't hesitate to contact us with any questions or further assistance. 

Best regards,

Jon
