### ISSUE TITLE
Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 3 near ".IncludeFilter

### ISSUE THREAD

**Issue by gabrielfreire** [zzzprojects/EntityFramework-Plus#699]
## 1. Description
I am trying to use `IncludeFilter` but with no success, i keep getting the following error even though i am registering the extension method
```bash
EvalException: Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 3 near ".IncludeFilter(x => x.GpN".
```

## 2. Exception
```bash
{"Oops! No applicable member has been found for the expression. The error occurred for expression \".\" at position 3 near \".IncludeFilter(x => x.GpN\"."}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Domain.Extensions.QueryBuilderExtensions.BuildQueryableFromRequestBody(DbContext dbContext, QueryBuilderRequestBody body) in C:\Users\xxxx\Documents\workspace\xxx\xxx.xxx\src\Domain\Extensions\QueryBuilderExtensions.cs:line 83
```

```
Exception message:
`{"Oops! No applicable member has been found for the expression. The error occurred for expression \".\" at position 3 near \".IncludeFilter(x => x.GpN\"."}`
Stack trace:
`   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Domain.Extensions.QueryBuilderExtensions.BuildQueryableFromRequestBody(DbContext dbContext, QueryBuilderRequestBody body) in C:\Users\xxxx\Documents\workspace\xxx\xxx.xxx\src\Domain\Extensions\QueryBuilderExtensions.cs:line 83`
```

## 4. Any further technical details
**Code**
```csharp
// below results in something like IncludeFilter(x => x.GpNavigation.Select(y => new(y.X, yX2, yX3)))
var _includeStr = $"IncludeFilter(x => x.{_joinTablePropertyMetadata.Item1}{(_joinSelects.Count > 0 ? $".Select(y => new({string.Join(',', _joinSelects)})))" : ")")}"; 

// register (i have also tried to register this before DbContext is created but with no success)
EvalManager.DefaultContext.RegisterExtensionMethod(typeof(QueryIncludeFilterExtensions));

// here i need to use reflection because i don't know the generic type for the IQueryable
var _executeDynQuery = typeof(IQueryable).GetExtensionMethod("Execute");

// below line throws the exception above
_iQueryable = (IQueryable)_executeDynQuery.Invoke(null, new object[] { _iQueryable, _includeStr });
```

**Comment by gabrielfreire** [comment]
## Update

I would like to also mention that the reason i'm trying to using include filter is because i want to select the fields in a collection and I couldn't find a way to do it in Dynamic LINQ so i was trying multiple ways like so :
- `.Select(new(it.Prop1, it.Prop2, it.Collection.Prop1))`
- `.Select(new(it.Prop1, it.Prop2, it.Collection.0.Prop1))`
- `.Select(new(it.Prop1, it.Prop2, it.Collection.[0].Prop1))`
- `.Select(new(it.Prop1, it.Prop2, it.Collection.{0}.Prop1))`

But i managed to do it by doing like so:
- `.Select(new(it.Prop1, it.Prop2, it.Collection.First().Prop1))`

Which is great, unfortunately i couldn't find any documentation about how to make string selects on collections but i managed to figure out this way by trial and error and it seems to work fine.

**Comment by JonathanMagnan** [comment]
Hello @gabrielfreire ,

Is it possible for you to provide a runnable project with the minimum code for the first issue with the `C# Eval Expression` library.

It will be easier for my developer to investigate it. You can send it in private here: info@zzzprojects.com

Best Regards,

Jon
