### ISSUE TITLE
EFCore 6 + FromSqlRaw + UpdateFromQuery

### ISSUE THREAD

**Issue by itan-mcp** [zzzprojects/EntityFramework-Plus#720]
## 1. Description
When using "FromSqlRaw" to populate an entity from a derived query, a System.ArgumentException exception is thrown

EFCore: 6.0.2/6.0.1
Z.EntityFramework.Plus.EFCore: 6.13.10

Code sample:
```
IQueryable<ExportedOrder> exportedOrdersQuery = dbContext.ExportedOrders.FromSqlRaw("SELECT * FROM ExportedOrders");

exportedOrdersQuery.UpdateFromQuery(x => new ExportedOrder
{
    SomeProp = "Some Text"
});
```
## 2. Exception
```
Exception message: No mapping exists from object type System.Object[] to a known managed provider native type.
Stack trace: 
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromType(Type dataType)
   at Microsoft.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   at Microsoft.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at Microsoft.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters, Boolean includeReturnValue)
   at Microsoft.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Extensions.BatchUpdate.<>c.(DbCommand , Nullable`1 )
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory)
```
## 4. Any further technical details
Same happens for DeleteFromQuery

**Comment by JonathanMagnan** [comment]
Hello @itan-mcp ,

Thank you for reporting, we will look at this.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by itan-mcp** [comment]
Hello @JonathanMagnan 

After quick look using with Executing Interceptor, I found that for FromSqlRaw case both UpdateFromQuery/DeleteFromQuery always add  **additional redundant parameter** to DbCommand.Parameters (at 0 position) with empty object array value (object[0]) which is not supported by Microsoft.Data.SqlClient.

So, for now the workaround might be just to remove this parameters from collection by using Executing Interceptor, **until the fix**

```
IQueryable<ExportedOrder> exportedOrdersQuery = dbContext.ExportedOrders.FromSqlRaw("SELECT * FROM ExportedOrders");

exportedOrdersQuery.UpdateFromQuery(x => new ExportedOrder
{
    SomeProp = "Some Text"
},
(batch) =>
{
    batch.Executing += (dbCommand) =>
    {
        var sqlCommand = dbCommand as Microsoft.Data.SqlClient.SqlCommand;

        if (sqlCommand?.Parameters?.Count > 0)
        {
            var firstParameter = sqlCommand.Parameters[0];

            if (firstParameter.Value != null && firstParameter.Value is object[] objectArr && objectArr.Length == 0)
            {
                sqlCommand.Parameters.Remove(firstParameter);
            }
        }
    };
});
```

**Comment by itan-mcp** [comment]
Hello @JonathanMagnan 

After quick look using with Executing Interceptor, I found that for FromSqlRaw case both UpdateFromQuery/DeleteFromQuery always add  **additional redundant parameter** to DbCommand.Parameters with empty object array value (object[0]) which is not supported by Microsoft.Data.SqlClient.

So, for now the workaround might be just to remove such parameters from collection by using Executing Interceptor, **until the fix**

```
IQueryable<ExportedOrder> exportedOrdersQuery = dbContext.ExportedOrders.FromSqlRaw("SELECT * FROM ExportedOrders");

exportedOrdersQuery.UpdateFromQuery(x => new ExportedOrder
{
    SomeProp = "Some Text"
},
(batch) =>
{
    batch.Executing = (dbCommand) =>
    {
        var sqlCommand = dbCommand as Microsoft.Data.SqlClient.SqlCommand;

        if (sqlCommand?.Parameters?.Count > 0)
        {
            var parameters = sqlCommand.Parameters.OfType<Microsoft.Data.SqlClient.SqlParameter>().ToArray(); 

            foreach(var parameter in parameters)
            {
                if (parameter.Value != null && parameter.Value is object[] objectArr && objectArr.Length == 0)
                {
                    sqlCommand.Parameters.Remove(parameter);
                }
            }
        }
    };
});
```
_when using only one db provider (MSSQL) it can be done without casting_
