### ISSUE TITLE
In EF6 using IncludeOptimized and WithHint NOLOCK together throws an exception.

### ISSUE THREAD

**Issue by chz160** [zzzprojects/EntityFramework-Plus#725]
## 1. Description
In EF6 using IncludeOptimized and WithHint(SqlServerTableHintFlags.NOLOCK) together throws an exception.

## 2. Exception
Unexpected exception occurred: Incorrect syntax near the keyword 'WITH'.
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Incorrect syntax near the keyword 'WITH'.
Incorrect syntax near the keyword 'AS'.

```
Exception message:
Stack trace:
```
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.CreateEnumerable()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Z.EntityFramework.Plus.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ToArrayAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ...Services....Service.<GetEntitiesAsync>d__33.MoveNext() in C:\Projects\...\Services\...Service.cs:line 721
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Services.EntityService.<GetByEntitiesAsync>d__22.MoveNext() in C:\Projects\...\Services\...Service.cs:line 288
ClientConnectionId:3a522358-6519-48b8-ad49-37b25eb31982
Error Number:156,State:1,Class:15
2022-04-01 12:40:46,321 [20] ERROR EntityProcessor.Consumer [(null)] - [EntityProcessor]Consumer - ConsumerMessage error encountered (Incorrect syntax near the keyword 'WITH'.
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Incorrect syntax near the keyword 'AS'.)

## 3. Sample Code
var results = await context.People
                .WithHint(SqlServerTableHintFlags.NOLOCK)
                .IncludeOptimized(c => c.Addresses)
                .IncludeOptimized(c => c.Phones)
                .Where(m => m.Id = id)
                .ToArrayAsync(cancellationToken);

## 4. Any further technical details
It should be noted, that if you do not use the provided WithHint extension to add WITH(NOLOCK) and add the NOLOCKs some other way, say with an EF Interceptor, the same exception is thrown when using IncludeOptimized.

**Comment by JonathanMagnan** [comment]
Hello @chz160 ,

Thank you for reporting, that's currently the same exact issue as this one: https://github.com/zzzprojects/EntityFramework-Plus/issues/723

We are currently looking at it.

Best Regards,

Jon

**Comment by chz160** [comment]
I did a little more digging and here's what I found. I used the existing QueryIncludeOptimized_Where_Async.Single_ThenQuery_EnumeratorAsync test in the Z.Test.EntityFramework.Plus.EF6 test project to write a new test for this issue and the SQL that is being generate appears to have WITH (NOLOCK) add in each location twice. See below:

```SQL
-- EF+ Query Future: 1 of 2
SELECT 
    [Project1].[ID] AS [ID], 
    [Project1].[ColumnInt] AS [ColumnInt]
    FROM ( SELECT 
        [Extent1].[ID] AS [ID], 
        [Extent1].[ColumnInt] AS [ColumnInt]
        FROM [dbo].[Association_OneToMany_Left] AS [Extent1] WITH (NOLOCK) WITH (NOLOCK)
        WHERE ( NOT ((N'ZZZQueryHook;' = @Z_1_p__linq__0) AND (@Z_1_p__linq__0 IS NOT NULL))) AND ([Extent1].[ColumnInt] < 5)
    )  AS [Project1]
    ORDER BY [Project1].[ID] ASC
;

-- EF+ Query Future: 2 of 2
SELECT 
    [Project1].[ID] AS [ID], 
    [Project1].[C1] AS [C1], 
    [Project1].[ID1] AS [ID1], 
    [Project1].[ColumnInt] AS [ColumnInt], 
    [Project1].[Left_ID] AS [Left_ID]
    FROM ( SELECT 
        [Extent1].[ID] AS [ID], 
        [Extent2].[ID] AS [ID1], 
        [Extent2].[ColumnInt] AS [ColumnInt], 
        [Extent2].[Left_ID] AS [Left_ID], 
        CASE WHEN ([Extent2].[ID] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM  [dbo].[Association_OneToMany_Left] AS [Extent1] WITH (NOLOCK) WITH (NOLOCK)
        LEFT OUTER JOIN [dbo].[Association_OneToMany_Right] AS [Extent2] ON ([Extent1].[ID] = [Extent2].[Left_ID]) AND ([Extent2].[ColumnInt] > 2)
        WHERE ( NOT ((N'ZZZQueryHook;' = @Z_2_p__linq__0) AND (@Z_2_p__linq__0 IS NOT NULL))) AND ([Extent1].[ColumnInt] < 5)
    )  AS [Project1]
    ORDER BY [Project1].[ID] ASC, [Project1].[C1] ASC
;
```

I also noticed that the join to Association_OneToMany_Right in the second query was not given a hint at all.

I attempted to look into it deeper to see if I could make a PR with a fix, however the source for Z.EntityFramework.Extensions appears to be in a private repo.

**Comment by chz160** [comment]
This issue appears to be resolved.

Thank you.
