### ISSUE TITLE
[QUESTION] When WhereBulkContains will support Oracle ?

### ISSUE THREAD

**Issue by fededim** [zzzprojects/EntityFramework-Plus#728]
I tried to use WhereBulkContains on a query on a Oracle database, yet when I run it an exception is generated stating the "UseBulkInsertToCopyTable option" is only available in Sql Server and PostgreSQL. Do you have any plan in supporting also Oracle ?

```
[05/24/2022 17:48:26 +02:00 ERR] -  - Connection ID "17870283340196610202", Request ID "8000009b-0004-f800-b63f-84710c7967bb": An unhandled exception was thrown by the application. 
System.Exception: Oops! The `UseBulkInsertToCopyTable` option is only available for SQL Server, and PostgreSQL.
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at Z.EntityFramework.Plus.WhereBulkContainsBuilder`1.BulkCopy(DbContext context, List`1 keyNames)
   at Z.EntityFramework.Plus.WhereBulkContainsBuilder`1.WhereBulkContains(DbContext context, String commandText, List`1 commandTableBuilders, Boolean isNotCTE)
   at Z.EntityFramework.Plus.QueryHookCommandInterceptor.InterceptorForAllExecuting(DbCommand command, DbContext context, Boolean isNotCTE)
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
   at TravelTime_API.Controllers.TravelTimeController.StoreTravelTimes(StoreTravelTimesRequest req) in C:\Users\dimarco\source\repos\Impianti\TravelTime\TravelTime_Api\Controllers\TravelTimeController.cs:line 409
   at TravelTime_API.Controllers.TravelTimeController.TestStoreTravelTimes() in C:\Users\dimarco\source\repos\Impianti\TravelTime\TravelTime_Api\Controllers\TravelTimeController.cs:line 330
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at TravelTime_Api.Middleware.LogApiMiddleware.InvokeAsync(HttpContext context) in C:\Users\dimarco\source\repos\Impianti\TravelTime\TravelTime_Api\Middleware\LogApiMiddleware.cs:line 62
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

```

**Comment by JonathanMagnan** [comment]
Hello @fededim ,

At this moment there is no plan to support Oracle.

We currently mainly focus on re-writing some part of our code to improve the performance and make sure that we will be able to support better EF Core 7 when it will be released.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
