### ISSUE TITLE
WhereBulkContains and navigation property

### ISSUE THREAD

**Issue by Chaosbit** [zzzprojects/EntityFramework-Plus#732]
## 1. Description
I have a query that looks like this:
```csharp
var targetDeviceTags = await context.DimDeviceTags
                .Include(x => x.BlockFkNavigation.DeviceIdFkNavigation)
                .Where(ddt=> ddt.BlockFkNavigation.DeviceIdFkNavigation.OrderIdFk == targetOrderId)
                .WhereBulkContains(myList,
                x => new {x.DeviceTagName, DeviceTagBlock = x.BlockFkNavigation.Name}).ToListAsync(cancellationToken);
```
And I get the exception below.
After looking at the decompiled code it seems that only direct field of the target table are supported with `WhereBulkContains`.
Is that correct?
I couldn't find it documented and the error message is kind of misleading in this case.

## 2. Exception

```
Exception message:
Oops! The following property names 'Property: DimDeviceTags.DeviceTagIdPk (int) Required PK AfterSave:Throw ValueGenerated.OnAdd,Property: DimDeviceTags.BlockFk (int) Required FK Index,Property: DimDeviceTags.Deleted (bool) Required,Property: DimDeviceTags.DeviceTagComment (string) MaxLength(256),Property: DimDeviceTags.DeviceTagCreatTime (Nullable<DateTime>),Property: DimDeviceTags.DeviceTagDataType (string) Required MaxLength(32),Property: DimDeviceTags.DeviceTagExtAccessible (Nullable<bool>),Property: DimDeviceTags.DeviceTagExtVisible (bool) Required,Property: DimDeviceTags.DeviceTagExtWritable (Nullable<bool>),Property: DimDeviceTags.DeviceTagNameGeneric (string) Required MaxLength(256),Property: DimDeviceTags.DeviceTagParent (string) Required MaxLength(256),Property: DimDeviceTags.DeviceTagResolution (string) MaxLength(32),Property: DimDeviceTags.DeviceTagSetpoint (Nullable<bool>),Property: DimDeviceTags.DeviceTagStartvalue (string) MaxLength(32),Property: DimDeviceTags.DeviceTagTraceValue (Nullable<int>) FK Index,Property: DimDeviceTags.DeviceTagUnit (string) MaxLength(16),Property: DimDeviceTags.DeviceTagUpdatTime (Nullable<DateTime>),Property: DimDeviceTags.Digits (int[]),Property: DimDeviceTags.Error (bool) Required ValueGenerated.OnAdd,Property: DimDeviceTags.Ignore (bool) Required,Property: DimDeviceTags.Internal (Nullable<bool>),Property: DimDeviceTags.LoadIdFk (int) Required FK Index,Property: DimDeviceTags.MachineComponentFk (Nullable<int>) FK Index,Property: DimDeviceTags.Processing (bool) Required ValueGenerated.OnAdd,Property: DimDeviceTags.Testing (bool) Required ValueGenerated.OnAdd' has not been found in the entity type 'DataWarehouse.Data.Dto.DimDeviceTags'.
Stack trace:
at Z.EntityFramework.Plus.WhereBulkContainsBuilder`1.WhereBulkContains(DbContext context, String commandText, List`1 commandTableBuilders, Boolean isNotCTE)
   at Z.EntityFramework.Plus.QueryHookCommandInterceptor.InterceptorForAllExecuting(DbCommand command, DbContext context, Boolean isNotCTE)
   at Z.EntityFramework.Plus.QueryHookCommandInterceptor.ReaderExecuting(DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
   at Z.EntityFramework.Extensions.InternalDbCommandInterceptorObserver.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.BroadcastCommandExecuting(IDiagnosticsLogger`1 diagnostics, DbConnection connection, DbCommand command, DbContext context, DbCommandMethod executeMethod, Guid commandId, Guid connectionId, Boolean async, DateTimeOffset startTime, EventDefinition`5 definition, Boolean diagnosticSourceEnabled, Boolean simpleLogEnabled)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.CommandReaderExecutingAsync(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DbCommand command, DbContext context, Guid commandId, Guid connectionId, DateTimeOffset startTime, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

**Comment by JonathanMagnan** [comment]
Hello @Chaosbit ,

My developer told me that we currently not yet support navigation property for the key. 

However, here is a workaround:

```csharp
var targetDeviceTags = context.DimDeviceTags
                                .Include(x => x.BlockFkNavigation.DeviceIdFkNavigation)
                                .Where(ddt => ddt.BlockFkNavigation.DeviceIdFkNavigation.OrderIdFk == targetOrderId)
                                .WhereBulkContains(myList.Select(x => new { x.DeviceTagName, DeviceTagBlock = x.BlockFkNavigation.Name }),
                                x => new { x.DeviceTagName, x.DeviceTagBlock }).ToList();
```

Doing this trick by already setting the right value on your `myList` and using the property name directly for the key should now make this kind of scenario work.

Let me know if that workaround could work for you.

Best Regards,

Jon
