### ISSUE TITLE
Unable to bulk insert multiple class types via common base class

### ISSUE THREAD

**Issue by Snazzie** [zzzprojects/EntityFramework-Plus#738]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
Im trying to bulk insert a load of different types of metrics data that all extends the same base class.
I am able to insert all these data via `AddRangeAsync` from entity framework core without an issue, it is able to figure out which table each data belongs to. 
Doing so with `BulkInsertAsync` from this package results in getting an "Unable to cast object of type 'x' to type 'x'."

i would stick with `AddRangeAsync` but the reason im trying to use this package is to access the options your function provides.

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Exception message: Unable to cast object of type 'TimeSeriesShared.Timescale.MemoryMetrics' to type 'TimeSeriesShared.Timescale.CpuMetrics'.
Stack trace: 
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetter`2.GetClrValue(Object entity)
   at .`1.( , String )
   at .( , DbConnection , DbTransaction )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.`1.MoveNext()
   at TimeSeriesShared.TimeScaleWriterClient.<InsertMetrics>d__7.MoveNext() in F:\Repo\Pluto\Source\MicroServices\TimeSeriesShared\TimeScaleWriterClient.cs:line 31
```

## 3. Fiddle or Project
```c#
    public async Task InsertMetrics(IEnumerable<TimescaleBase> metrics)
    {
          var context = DbContext.CreateDbContext();
                
          // await context.AddRangeAsync(metrics); <- works
          await context.BulkInsertAsync(metrics); // <- exception thrown!
                
          await context.SaveChangesAsync();
    }

    public class CpuMetrics: TimescaleBase
    {
        public int CpuPercentage { get; set; }

        public int? CpuTemperature { get; set; }
    }
    public abstract class TimescaleBase
    {
        [Required]
        [HypertableColumn]
        [Column(TypeName = "timestamp with time zone")]
        public DateTime TimeStamp { get; set; } 

        [Required]
        [HypertableColumn]
        [Column(TypeName = "TEXT")]
        public string TargetId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; } = new Guid();
    }
    
    public class MemoryMetrics : TimescaleBase
    {
        public uint TotalMemoryKB { get; set; }

        public uint TotalMemoryUsedKB { get; set; }

        public uint? TotalSwapKB { get; set; }

        public uint? TotalSwapUsedKB { get; set; }
    }
```
## 4. Any further technical details

Package version: Z.EntityFramework.Plus.EFCore 6.14.4
DB: Postgresql

**Comment by JonathanMagnan** [comment]
Hello @Snazzie ,

The `BulkInsert` method is an immediate operation exactly like `SaveChanges`. So you should not call `SaveChanges` after calling the `BulkInsert` method as the data would already have been inserted.

That being said, you are probably looking for the `BulkSaveChanges` method:

```csharp
var context = DbContext.CreateDbContext();
	
await context.AddRangeAsync(metrics);
	
await context.BulkSaveChangesAsync();
```

Since you use different classes, that means entities must be added to different `DbSet,` and a saving order needs to be created as they might have some dependencies. The `BulkSaveChanges` methods will be able to handle this.

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by Snazzie** [comment]
Yes that fixed it, thanks!.
