### ISSUE TITLE
Cannot be converted to type error when trying to use global filter with interface

### ISSUE THREAD

**Issue by sw-ch** [zzzprojects/EntityFramework-Plus#74]
I tried to setup a global filter to implement soft delete filtering accross all my entity types in the progress of migrating a project to NET Core.

Used versions:
Microsoft.EntityFrameworkCore 1.0.1
Z.EntityFramework.Plus.EFCore 1.4.9

The entity inheritance tree looks like this:
Interface: IEntityBase -> Abstract class: EntityBase -> Entity classes: Address, Offers...

When I try to initialize a global filter:
`
QueryFilterManager.Filter<IEntityBase>("IsActive", pe => pe.Where(e => e.State == null));
QueryFilterManager.InitilizeGlobalFilter(ctx);
`

I get the following error:

`System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Object of type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable'1[Tst.IEntityBase]' cannot be converted to type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable'1[Test.Entities.Address]'.
  Source=System.Private.CoreLib
  StackTrace:
       at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
       at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
       at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
       at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
       at Z.EntityFramework.Plus.QueryFilterSet.UpdateInternalQuery(DbContext context, Object query)
       at Z.EntityFramework.Plus.QueryFilterQueryable'1.UpdateInternalQuery()
       at Z.EntityFramework.Plus.QueryFilterContext.EnableFilter(BaseQueryFilter filter, Type[] types)
       at Z.EntityFramework.Plus.QueryFilterManager.InitilizeGlobalFilter(DbContext context)

**Comment by zzzprojects** [comment]
Hello @sw-ch ,

Unfortunately, this is a documented limitation for EF Core: [EF+ Query Filter - Limitations](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-Filter-%7C-Entity-Framework-Dynamic-Instance-and-Global-Filters#limitations)

This issue is due because EF Core cannot handle simple casting: https://github.com/aspnet/EntityFramework/issues/3736

I will take one hour or two today to see if I can use a workaround since the fix has been reported to milestone 7.00 -> 1.00 -> 1.01 -> 1.1.0-preview1 -> 1.2.0 by the EF Team.

**Comment by sw-ch** [comment]
Hi Jonathan

Thanks for your quick reply. Sorry for bothering, should have seen that in the documentation.

Regards
Stephan

**Comment by zzzprojects** [comment]
Hello Stephan ,

Don't be sorry for that. It's always good to have a reminder from time to time to check if Cast method has been fixed or not.

A 'ForceCast' option has been added which may or not help you with this issue.

```csharp
QueryFilterManager.ForceCast = true;
```

When enabled, Inherited class will now work and you will not longer get this error. However, some LINQ method will not longer work with Filtered query:
- Aggregate
- Max
- Min
- Sum

Let me know if that can partially fix your situation for now.

Best Regards,

Jonathan

**Comment by sw-ch** [comment]
Hi Jonathan

Thanks for the new version. Currently, I should be able to work around the limitations. It also seems to work with single table-per-hierarchy inheritance entities. I will need some time to figure out how much ground I can cover without hitting another wall...

Should I close the issue for now or do you want to keep it open as a reminder?

Regards
Stephan

**Comment by zzzprojects** [comment]
Hello @sw-ch ,

Let close it, that will make it easier to track other issues.

Best Regards,

Jonathan
