### ISSUE TITLE
UpdateAsync does not work with EF 7.0.0-rc.1.22426.7

### ISSUE THREAD

**Issue by haoleanh** [zzzprojects/EntityFramework-Plus#740]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
It seems that EntityType property has been removed in QueryRootExpression class in EF (7.0.0-rc.1.22426.7) but it still use in Z.EntityFramework.Plus.EFCore (7.0.0-preview.7.22376.2-01)
https://github.com/dotnet/efcore/blob/v7.0.0-rc.1.22426.7/src/EFCore/Query/QueryRootExpression.cs

## 2. Exception
```
Exception message:
Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.Query.QueryRootExpression.get_EntityType()'.
Stack trace:
at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.<>c__DisplayClass8_0`1.<UpdateAsync>b__0()
```

**Comment by haoleanh** [comment]
@JonathanMagnan Nice, cant wait and thanks for quick response :)

**Comment by JonathanMagnan** [comment]
Hello @haoleanh ,

A new version has been released, which should now support the `RC1`.

If you have the chance to try it, let us know if everything is now working.

Best Regards,

Jon

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by haoleanh** [comment]
@JonathanMagnan the latest version fixed the issue. Thanks for the help :)
