### ISSUE TITLE
.NET 7 is out

### ISSUE THREAD

**Issue by christallire** [zzzprojects/EntityFramework-Plus#744]
It's time to release .NET 7 compatible library

**Comment by JonathanMagnan** [comment]
Hello @christallire ,

Yup, it's coming next Monday or Tuesday.

The latest preview of our library should already be compatible with the official version of EF Core 7.

Best Regards,

Jon

**Comment by dragnilar** [comment]
@JonathanMagnan  Thanks for looking into this one, we'll be waiting for the official release next week.

And for what it is worth, the preview version of EF Extensions definitely does work with dot net 7 (we ran into issues earlier today with ef extensions testing out dot net 7 in dev).

**Comment by JonathanMagnan** [comment]
Hello @dragnilar , @christallire 

The stable version of EF Plus/EF Extensions v7 has been released today.

If you have any problem, let us know.

Best Regards,

Jon

**Comment by mgattei** [comment]
Hello @JonathanMagnan ,
I've just updated my project to .NET 7 and seems that there is a problem with the Caching Extensions.

This is the partial stacktrace:
```
       System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Storage.IRelationalCommand Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression)'.
          at .(IQueryable , RelationalQueryContext& )
          at Z.EntityFramework.Extensions.PublicExtensions.CreateCommand(IQueryable source, RelationalQueryContext& queryContext)
          at Z.EntityFramework.Plus.QueryCacheManager.GetCacheKey(IQueryable query, String[] tags)
          at Z.EntityFramework.Plus.QueryCacheExtensions.FromCache[T](IQueryable`1 query, MemoryCacheEntryOptions options, String[] tags)
          at RAO.Service.Services.Tenant.HostTenantIdentificationService.GetTenantIdFromName(String tenantName) in /app/XX.Service/Services/Tenant/HostTenantIdentificationService.cs:line 63
```

**Comment by JonathanMagnan** [comment]
Hello @mgattei ,

Which version exactly of EF Core and EF Plus are you using? It looks like an issue which some mismatch in the version such as you are using EF Plus 7.x with EF Core 6.x or vice-versa.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Awesome,

We will close this issue and re-open it if someone find an error.

Best Regards,

Jon
