### ISSUE TITLE
Complex queries are with mistakes

### ISSUE THREAD

**Issue by Soteyl** [zzzprojects/EntityFramework-Plus#754]
Code:
```c#
await _context.OrganizationServices
            .Include(x => x.Specialities)
            .Include(x => x.IncludedResources)
            .Include(x => x.ExcludedResources)
            .Where(s => 
                s.OrganizationId.Equals(request.OrganizationId) && 
                s.Specialities.Any(sp => changedSpecialities.Contains(sp.SpecialityId)) &&
                 !s.IncludedResources.Any(r => r.ResourceId.Equals(request.ResourceId)) &&
                !s.ExcludedResources.Any(r => r.ResourceId.Equals(request.ResourceId)))
            .UpdateAsync(x => new OrganizationServiceEntity()
            {
                DoctorsCount = x.Specialities.Any(sp => onlyOld.Contains(sp.SpecialityId)) ? x.DoctorsCount - 1 : 
                    x.Specialities.Any(sp => onlyNew.Contains(sp.SpecialityId)) ? x.DoctorsCount + 1 
                    : x.DoctorsCount
            }, cancellationToken);
```

It generates next query:

```SQL
UPDATE "OrganizationServices"
SET "DoctorsCount" = CASE
    WHEN EXISTS (
        SELECT 1
        FROM "OrganizationServiceSpecialities" AS o3
        WHERE ("Id" = o3."ServiceId") AND (o3."SpecialityId" = 'specialityId_89')) THEN "DoctorsCount" - 1
    ELSE "DoctorsCount"
END
FROM "OrganizationServices" AS o
WHERE ((("OrganizationId" = @__request_OrganizationId_0) AND EXISTS (
    SELECT 1
WHERE EXISTS ( SELECT 1 FROM (SELECT o."Id", o."AchiId", o."ArchivedAt", o."CreatedAt", o."Description", o."DoctorsCount", o."IsEHealthRepaymentAllowed", o."LastUpdatedAt", o."Name", o."OrganizationId", o."ProvidingMethod", o."PublishStatus", o."RemovedAt", o."ServicePackageId", o."TableKey", o."VisibilityStatus", o3."SpecialityId", o3."ServiceId", o4."ResourceId", o4."ServiceId", o5."ResourceId", o5."ServiceId"
FROM "OrganizationServices" AS o
LEFT JOIN "OrganizationServiceSpecialities" AS o3 ON o."Id" = o3."ServiceId"
LEFT JOIN "OrganizationServiceIncludedResources" AS o4 ON o."Id" = o4."ServiceId"
LEFT JOIN "OrganizationServiceExcludedResources" AS o5 ON o."Id" = o5."ServiceId"
WHERE (((o."OrganizationId" = @__request_OrganizationId_0) AND EXISTS (
    SELECT 1
    FROM "OrganizationServiceSpecialities" AS o0
    WHERE (o."Id" = o0."ServiceId") AND (o0."SpecialityId" = 'specialityId_89'))) AND NOT (EXISTS (
    SELECT 1
    FROM "OrganizationServiceIncludedResources" AS o1
    WHERE (o."Id" = o1."ServiceId") AND (o1."ResourceId" = @__request_ResourceId_2)))) AND NOT (EXISTS (
    SELECT 1
    FROM "OrganizationServiceExcludedResources" AS o2
    WHERE (o."Id" = o2."ServiceId") AND (o2."ResourceId" = @__request_ResourceId_2)))
ORDER BY o."Id", o3."SpecialityId", o3."ServiceId", o4."ResourceId", o4."ServiceId", o5."ResourceId") B
               WHERE "OrganizationServices"."Id" = B."Id"
           )
```

The query doesn't contain some closing brackets. I tried to remake the query but without a success.

Here is an error which i receive:
```
Npgsql.PostgresException (0x80004005): 42601: syntax error at end of input

POSITION: 1761
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Extensions.BatchUpdate.<>c.(DbCommand , Nullable`1 )
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.<>c__DisplayClass8_0`1.<UpdateAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

Upd: Reproducable on 6.18.3 and 6.18.4 versions of Z.EntityFramework.Plus.EFCore

**Comment by JonathanMagnan** [comment]
Hello @Soteyl ,

Thank you for reporting. Indeed it seems to miss some closing brackets. 

My developer will look if he can find something that could cause this.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by Soteyl** [comment]
@JonathanMagnan Thank you. I'll provide more information, if it is required

**Comment by JonathanMagnan** [comment]
Hello @Soteyl ,

The way the query is generated by Entity Framework is currently not supported and cause us some problem.

We tried to fix it to make our library compatible, but unfortunately, my developer was unable.

That's sure something we will explore again in the future as this is sure douable, but at this moment, we will have to abandon it until we review and re-write that features to support more case

Best Regards,

Jon
