### ISSUE TITLE
Future broke pooled DbContext instance because previous Future query was cancelled

### ISSUE THREAD

**Issue by stukselbax** [zzzprojects/EntityFramework-Plus#777]
## 1. Description
When:
- using DbContext pooling,
- and transactions,
- and inside that transaction the `Future` feature is used to query database,
- and exception occurs inside future query enumerable (e.g. OperationCancelledException),

Then

this DbContext instance is not usable anymore inside other transactions, and any attempts to repeat a query inside new transaction will fail with exception.

Hitting this error with 7.22.6 version of library, and on postgresql, but probably that doesn't matter.

## 2. Exception

```
Exception message: The specified transaction is not associated with the current connection. Only transactions associated with the current connection may be used.
Stack trace:
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction..ctor(IRelationalConnection connection, DbTransaction transaction, Guid transactionId, IDiagnosticsLogger`1 logger, Boolean transactionOwned, ISqlGenerationHelper sqlGenerationHelper) in /_/src/EFCore.Relational/Storage/RelationalTransaction.cs:line 51
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransactionFactory.Create(IRelationalConnection connection, DbTransaction transaction, Guid transactionId, IDiagnosticsLogger`1 logger, Boolean transactionOwned) in /_/src/EFCore.Relational/Storage/RelationalTransactionFactory.cs:line 58
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CreateRelationalTransaction(DbTransaction transaction, Guid transactionId, Boolean transactionOwned) in /_/src/EFCore.Relational/Storage/RelationalConnection.cs:line 452
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<BeginTransactionAsync>d__51.MoveNext() in /_/src/EFCore.Relational/Storage/RelationalConnection.cs:line 412
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext() in /_/src/EFCore.PG/Storage/Internal/NpgsqlExecutionStrategy.cs:line 65
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__Get|1>d.MoveNext() in \FutureBug\FutureBug\Program.cs:line 48
   at Program.<<Main>$>d__0.MoveNext() in \FutureBug\FutureBug\Program.cs:line 40
   at Program.<Main>(String[] args)

```

## 3. Project
Single-file project which reproduces the issue:
https://github.com/stukselbax/FutureBug

To start the project, ensure you have postgres server and edit connection string accordingly.

## 4. Any further technical details

![FutureBug](https://github.com/zzzprojects/EntityFramework-Plus/assets/2863944/94e18b1e-f990-4614-a201-2983c9a4df0d)

**Comment by JonathanMagnan** [comment]
Hello @stukselbax ,

Thank you again for the project, it surely helps us to find out the cause of the issue.

A fix will be released next week (2023-09-12).

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @stukselbax ,

The v7.100.0.0 has been released.

Let us know if the issue was correctly fixed in our latest version.

Best Regards,

Jon

**Comment by arex388** [comment]
I use future queries extensively in my projects. One of them, after a major update, was plagued by this exact same exception. It was only happening on saves and I initially blamed EntityFrameworkCore.Triggered and even removed it from the app after taking the time to implement it in the major update. It helped, but then eventually I solved it by simply switching to non-pooled DbContext. I wonder if it was Future queries and EFP causing the instability now that I'm reading this issue?...

https://github.com/koenbeuk/EntityFrameworkCore.Triggered/issues/173#event-9557500684

**Comment by stukselbax** [comment]
We have updated our environment to the 7.100.0.0 and turn on `Future` again, to see if the issue resolved. We should take a look how it behaves now, and I will let you know about the results in a couple of days.

**Comment by stukselbax** [comment]
The project which reproduced the source problem with new version is working as expected, at least.

Pretty interesting about the commit history - there is no any PR or direct commit to this repo, but the release is here. Magic.

**Comment by JonathanMagnan** [comment]
Hello @stukselbax ,

This is because our real source repository is on Visual Studio Online (or whatever it's called now). We will eventually move some part of the code to point on GitHub as there is a few stuff that we want to keep private (mainly some lab).

I committed the code, the important part on this issue was about the connection not being in a `finally` block (so was not restoring when an issue happened): https://github.com/zzzprojects/EntityFramework-Plus/commit/69a991b56e0b477511d3d33443c526c8990eb0f6#diff-a147b71f4a9f0a880c4f938c0abe6350ba3ee1208a1a7ec0eb8ee8aa9430595eR353

(To make this feature work, we temporarily change the connection to our connection): https://github.com/zzzprojects/EntityFramework-Plus/commit/69a991b56e0b477511d3d33443c526c8990eb0f6#diff-c6c1d9df8e972c413f862e712580579ad201f5d8a2de2aad77c159835a1417e7R461

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @arex388 ,

I'm not sure if this was caused by us or not. But I believe it's fair to assume that our library was caused this and not `EntityFrameworkCore.Triggered`

I will surely give this library a second chance to see if the issue is still happening.

If yes, I recommend you create a new issue with a prototype project like @stukselbax  did. We will look at it if we are the cause or not.

Best Regards,

Jon

**Comment by stukselbax** [comment]
Hi @JonathanMagnan - the `Future` now works as expected, we didn't faced this issue anymore.
