### ISSUE TITLE
Is IN clause supported?

### ISSUE THREAD

**Issue by temp-impl** [zzzprojects/EntityFramework-Plus#88]
I try DELETE by IN clause but it does not work. (EF Core 1.1 & localdb)

This is my code: https://github.com/temp-impl/ZEFPlusUpdateTest/blob/master/src/ZEFPlusUpdateTest/Program.cs

Exception:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (No mapping exists from object type System.Int32[] to a known managed provider native type.) ---> System.ArgumentException: No mapping exists from object type System.Int32[] to a known managed provider native type.
   at System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Object value, Boolean inferLen, Boolean streamAllowed)
   at System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters)
   at System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ZEFPlusUpdateTest.Program.<MainAsync>d__1.MoveNext() in C:\src_test\ZEFPlusUpdateTest\src\ZEFPlusUpdateTest\Program.cs:line 40
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ZEFPlusUpdateTest.Program.Main(String[] args) in C:\src_test\ZEFPlusUpdateTest\src\ZEFPlusUpdateTest\Program.cs:line 14
```

Is something wrong with my code, or IN clause is not supported?

**Comment by zzzprojects** [comment]
Hello @temp-impl ,

We successfully reproduced this issue. 

It seems some parameter provided by SQL Core are removed later.

So we will need now to look if the parameter should be removed or not.

In your example, the SQL generated is good. However, the parameter with a value of type int array is not a valid parameter.

We will try to look and fix this issue next weekend.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @temp-impl ,

The issue has been fixed, it will be available on the Monday release.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @temp-impl ,

Sorry for the delay,

The v1.4.13 should fix this issue.

Let me know if it's successfully fixed.

Best Regards,

Jonathan

**Comment by temp-impl** [comment]
Thanks a lot Jonathan, it worked perfect !!
